import {
  Wrench,
  Plug,
  Paintbrush,
  Hammer,
  Wind,
  DoorOpen,
  Flower,
  Computer,
  Building,
  SprayCan,
  Truck,
  Sparkles,
  PartyPopper,
  GraduationCap,
  HeartHandshake,
  Palette,
  ChefHat,
  Tractor,
  Lightbulb,
  ShieldCheck,
  Briefcase,
  Brush,
} from 'lucide-react';
import type { Category, Professional, Banner } from '@/lib/types';
import { placeholderImages } from './placeholder-images';

const getImage = (id: string) =>
  placeholderImages.find((img) => img.id === id) || {
    imageUrl: '',
    imageHint: '',
  };

export const CATEGORIES: Category[] = [
  {
    id: 1,
    name: 'Construcción y Mantenimiento',
    icon: Building,
    description: 'Expertos en construcción, reformas y mantenimiento general del hogar.',
  },
  {
    id: 2,
    name: 'Jardinería y Paisajismo',
    icon: Flower,
    description: 'Cuidado y diseño de espacios verdes, desde jardines hasta parques.',
  },
  {
    id: 3,
    name: 'Limpieza y Mantenimiento',
    icon: Sparkles,
    description: 'Servicios de limpieza profunda para hogares, oficinas y más.',
  },
  {
    id: 4,
    name: 'Transporte y Logística',
    icon: Truck,
    description: 'Soluciones de mudanza, fletes y transporte de mercaderías.',
  },
  {
    id: 5,
    name: 'Reparaciones y Servicios Técnicos',
    icon: Wrench,
    description: 'Técnicos especializados en la reparación de todo tipo de equipos.',
  },
  {
    id: 6,
    name: 'Eventos y Entretenimiento',
    icon: PartyPopper,
    description: 'Todo lo que necesitas para que tu evento sea un éxito.',
  },
  {
    id: 7,
    name: 'Educación y Clases',
    icon: GraduationCap,
    description: 'Profesores y tutores para todas las edades y niveles.',
  },
  {
    id: 8,
    name: 'Salud, Bienestar y Estética',
    icon: HeartHandshake,
    description: 'Cuidado personal, masajes, y terapias para tu bienestar.',
  },
  {
    id: 9,
    name: 'Arte, Diseño y Comunicación',
    icon: Palette,
    description: 'Creativos para diseño gráfico, web, fotografía y más.',
  },
  {
    id: 10,
    name: 'Alimentación y Comercio',
    icon: ChefHat,
    description: 'Desde panaderías hasta delivery, todo para el deleite de tu paladar.',
  },
  {
    id: 11,
    name: 'Plomería',
    icon: Wrench,
    description: 'Soluciones para tuberías, grifos y filtraciones.',
  },
  {
    id: 12,
    name: 'Gasista',
    icon: Wind,
    description: 'Instalación y reparación de redes de gas.',
  },
  {
    id: 13,
    name: 'Albañilería',
    icon: Hammer,
    description: 'Construcción y reformas.',
  },
  {
    id: 14,
    name: 'Electricidad',
    icon: Plug,
    description: 'Instalaciones y reparaciones eléctricas.',
  },
  {
    id: 15,
    name: 'Carpintería',
    icon: Hammer,
    description: 'Muebles, reparaciones en madera y metal.',
  },
  {
    id: 16,
    name: 'Herrería',
    icon: Hammer,
    description: 'Trabajos en hierro y soldaduras.',
  },
  {
    id: 17,
    name: 'Pintura',
    icon: Paintbrush,
    description: 'Servicios de pintura para interiores y exteriores.',
  },
  {
    id: 18,
    name: 'Techistas',
    icon: Hammer,
    description: 'Reparación y construcción de techos.',
  },
  {
    id: 19,
    name: 'Impermeabilización',
    icon: SprayCan,
    description: 'Protección contra filtraciones en techos y terrazas.',
  },
  {
    id: 20,
    name: 'Revestimientos',
    icon: Brush,
    description: 'Instalación de pisos y cerámicos.',
  },
  {
    id: 21,
    name: 'Reparación de Baños y Cocinas',
    icon: Wrench,
    description: 'Arreglos y renovaciones completas.',
  },
  {
    id: 22,
    name: 'Iluminación LED',
    icon: Lightbulb,
    description: 'Instalación de sistemas de iluminación eficientes.',
  },
  {
    id: 23,
    name: 'Aire Acondicionado y Calefacción',
    icon: Wind,
    description: 'Instalación y mantenimiento de equipos.',
  },
  {
    id: 24,
    name: 'Reparación de Calefones y Termotanques',
    icon: Wrench,
    description: 'Servicio técnico para agua caliente.',
  },
  {
    id: 25,
    name: 'Energía Solar',
    icon: Lightbulb,
    description: 'Instalación de paneles solares.',
  },
  {
    id: 26,
    name: 'Corte de Césped',
    icon: Tractor,
    description: 'Mantenimiento de césped y jardines.',
  },
  {
    id: 27,
    name: 'Poda y Tala de Árboles',
    icon: Hammer,
    description: 'Servicios de poda y remoción de árboles.',
  },
  {
    id: 28,
    name: 'Riego Automático',
    icon: Flower,
    description: 'Instalación de sistemas de riego.',
  },
  {
    id: 29,
    name: 'Plantas y Macetas',
    icon: Flower,
    description: 'Venta y asesoramiento en plantas.',
  },
  {
    id: 30,
    name: 'Limpieza de Vidrios',
    icon: Sparkles,
    description: 'Limpieza profesional de ventanas y vidrios.',
  },
  {
    id: 31,
    name: 'Limpieza de Alfombras',
    icon: Sparkles,
    description: 'Limpieza profunda de alfombras y tapizados.',
  },
  {
    id: 32,
    name: 'Limpieza de Techos y Canaletas',
    icon: Sparkles,
    description: 'Mantenimiento y limpieza de techos.',
  },
  {
    id: 33,
    name: 'Repartidor / Delivery',
    icon: Truck,
    description: 'Servicios de entrega y mensajería.',
  },
  {
    id: 34,
    name: 'Fletes y Transportes Pequeños',
    icon: Truck,
    description: 'Transporte de objetos y pequeñas mudanzas.',
  },
  {
    id: 35,
    name: 'Guardamuebles / Depósitos',
    icon: Building,
    description: 'Almacenamiento seguro de tus pertenencias.',
  },
  {
    id: 36,
    name: 'Alquiler de Maquinaria',
    icon: Tractor,
    description: 'Alquiler de camiones, grúas y andamios.',
  },
  {
    id: 37,
    name: 'Reparación de Electrodomésticos',
    icon: Wrench,
    description: 'Servicio técnico para tus aparatos.',
  },
  {
    id: 38,
    name: 'Reparación de Computadoras y Celulares',
    icon: Computer,
    description: 'Soporte técnico para tus dispositivos.',
  },
  {
    id: 39,
    name: 'Mecánica de Autos y Motos',
    icon: Wrench,
    description: 'Servicios de mecánica ligera y pesada.',
  },
  {
    id: 40,
    name: 'Lavado y Pintura de Autos',
    icon: SprayCan,
    description: 'Detallado y pintura automotriz.',
  },
  {
    id: 41,
    name: 'Tapicería',
    icon: Brush,
    description: 'Renovación de tapizados de autos y muebles.',
  },
  {
    id: 42,
    name: 'Soldadura y Tornería',
    icon: Hammer,
    description: 'Trabajos de precisión en metal.',
  },
  {
    id: 43,
    name: 'Sistemas de Seguridad y Cámaras',
    icon: ShieldCheck,
    description: 'Instalación de sistemas de vigilancia.',
  },
  {
    id: 44,
    name: 'Seguridad Informática',
    icon: ShieldCheck,
    description: 'Protección de datos y sistemas.',
  },
  {
    id: 45,
    name: 'Electricidad y Plomería Industrial',
    icon: Briefcase,
    description: 'Servicios especializados para industrias.',
  },
  {
    id: 46,
    name: 'Catering y Organización de Eventos',
    icon: PartyPopper,
    description: 'Planificación y servicio gastronómico.',
  },
  {
    id: 47,
    name: 'Animación y Shows',
    icon: PartyPopper,
    description: 'Entretenimiento para fiestas y eventos.',
  },
  {
    id: 48,
    name: 'Música, Sonido e Iluminación',
    icon: PartyPopper,
    description: 'Equipamiento y DJs para eventos.',
  },
  {
    id: 49,
    name: 'Fotografía y Video para Eventos',
    icon: PartyPopper,
    description: 'Cobertura profesional de tus momentos.',
  },
  {
    id: 50,
    name: 'Decoración de Eventos',
    icon: PartyPopper,
    description: 'Ambientación y decoración para fiestas.',
  },
  {
    id: 51,
    name: 'Clases Particulares',
    icon: GraduationCap,
    description: 'Apoyo escolar y clases de diversas materias.',
  },
  {
    id: 52,
    name: 'Clases de Arte y Música',
    icon: GraduationCap,
    description: 'Aprende a tocar un instrumento o a pintar.',
  },
  {
    id: 53,
    name: 'Talleres',
    icon: GraduationCap,
    description: 'Cerámica, carpintería, costura y más.',
  },
  {
    id: 54,
    name: 'Clases de Idiomas y Cocina',
    icon: GraduationCap,
    description: 'Aprende nuevas habilidades.',
  },
  {
    id: 55,
    name: 'Cuidado de Personas y Mascotas',
    icon: HeartHandshake,
    description: 'Cuidadores para niños, adultos mayores y mascotas.',
  },
  {
    id: 56,
    name: 'Estética a Domicilio',
    icon: HeartHandshake,
    description: 'Peluquería, manicuría y más en tu casa.',
  },
  {
    id: 57,
    name: 'Terapias y Bienestar',
    icon: HeartHandshake,
    description: 'Masajes, fisioterapia, psicología y más.',
  },
  {
    id: 58,
    name: 'Entrenamiento y Coaching',
    icon: HeartHandshake,
    description: 'Yoga, Pilates y entrenamiento personal.',
  },
  {
    id: 59,
    name: 'Diseño Gráfico y Web',
    icon: Palette,
    description: 'Diseño de logos y desarrollo de sitios web.',
  },
  {
    id: 60,
    name: 'Desarrollo de Apps y Programación',
    icon: Computer,
    description: 'Programadores freelance para tus proyectos.',
  },
  {
    id: 61,
    name: 'Marketing Digital y Cartelería',
    icon: Palette,
    description: 'Promociona tu negocio.',
  },
  {
    id: 62,
    name: 'Fotografía, Video e Impresión 3D',
    icon: Palette,
    description: 'Servicios creativos y de producción.',
  },
  {
    id: 63,
    name: 'Artesanía y Manualidades',
    icon: Palette,
    description: 'Productos únicos hechos a mano.',
  },
];


export const PROFESSIONALS: Professional[] = [
  {
    id: 1,
    name: 'Carlos Rodriguez',
    phone: '2914123456',
    photoUrl: getImage('prof-1').imageUrl,
    photoHint: getImage('prof-1').imageHint,
    specialties: ['Reparación de Fugas', 'Instalación de Grifería'],
    avgRating: 4.8,
    categoryId: 11,
    priceInfo: 'Hora de trabajo desde $2500 ARS. Presupuestos sin cargo.',
    isSubscriptionActive: false, // Subscription expired
    subscriptionTier: 'standard',
    testimonials: [
      {
        id: 1,
        clientName: 'Ana Gomez',
        clientPhotoUrl: getImage('client-1').imageUrl,
        clientPhotoHint: getImage('client-1').imageHint,
        rating: 5,
        text: 'Excelente servicio. Rápido y muy profesional.',
      },
      {
        id: 2,
        clientName: 'Juan Pérez',
        clientPhotoUrl: getImage('client-3').imageUrl,
        clientPhotoHint: getImage('client-3').imageHint,
        rating: 4,
        text: 'Buen trabajo, resolvió el problema de la tubería eficientemente.',
      },
    ],
  },
  {
    id: 2,
    name: 'Lucía Fernandez',
    phone: '2914123457',
    photoUrl: getImage('prof-2').imageUrl,
    photoHint: getImage('prof-2').imageHint,
    specialties: ['Instalaciones Eléctricas', 'Tableros'],
    avgRating: 5.0,
    categoryId: 14,
    priceInfo: 'Consultar por instalación. Revisiones desde $2000 ARS.',
    isSubscriptionActive: true,
    subscriptionTier: 'premium',
    testimonials: [
      {
        id: 3,
        clientName: 'María López',
        clientPhotoUrl: getImage('client-2').imageUrl,
        clientPhotoHint: getImage('client-2').imageHint,
        rating: 5,
        text: '¡Impecable! Muy prolija y atenta a los detalles.',
      },
      {
        id: 4,
        clientName: 'Pedro Martins',
        clientPhotoUrl: getImage('client-4').imageUrl,
        clientPhotoHint: getImage('client-4').imageHint,
        rating: 5,
        text: 'La mejor electricista de la ciudad. Totalmente recomendada.',
      },
    ],
  },
  {
    id: 3,
    name: 'Miguel Torres',
    photoUrl: getImage('prof-3').imageUrl,
    photoHint: getImage('prof-3').imageHint,
    specialties: ['Pintura de Interiores', 'Empapelado'],
    avgRating: 4.5,
    categoryId: 17,
    priceInfo: 'Presupuestos a medida según m2. Incluye materiales.',
    isSubscriptionActive: true,
    subscriptionTier: 'standard',
    testimonials: [
      {
        id: 5,
        clientName: 'Laura Sanchez',
        clientPhotoUrl: getImage('client-1').imageUrl,
        clientPhotoHint: getImage('client-1').imageHint,
        rating: 4,
        text: 'El departamento quedó como nuevo, aunque tardó un poco más de lo esperado.',
      },
    ],
  },
  {
    id: 4,
    name: 'Jorge Herrera',
    phone: '2914123459',
    photoUrl: getImage('prof-4').imageUrl,
    photoHint: getImage('prof-4').imageHint,
    specialties: ['Muebles a Medida'],
    avgRating: 4.9,
    categoryId: 15,
    isSubscriptionActive: true,
    subscriptionTier: 'premium',
    testimonials: [
      {
        id: 6,
        clientName: 'Sofía Castro',
        clientPhotoUrl: getImage('client-2').imageUrl,
        clientPhotoHint: getImage('client-2').imageHint,
        rating: 5,
        text: 'El ropero que diseñó es perfecto. Un verdadero artesano.',
      },
    ],
  },
   {
    id: 5,
    name: 'Marta Diaz',
    photoUrl: getImage('prof-6').imageUrl,
    photoHint: getImage('prof-6').imageHint,
    specialties: ['Cambio de Cerraduras', 'Aperturas de emergencia'],
    avgRating: 4.7,
    categoryId: 34,
    isSubscriptionActive: true,
    subscriptionTier: 'standard',
    testimonials: [
      {
        id: 7,
        clientName: 'Roberto "Tito" Ramirez',
        clientPhotoUrl: getImage('client-3').imageUrl,
        clientPhotoHint: getImage('client-3').imageHint,
        rating: 5,
        text: 'Me salvó a las 3 AM cuando perdí las llaves. ¡Una genia!',
      },
    ],
  },
   {
    id: 6,
    name: 'Raúl Benitez',
    photoUrl: getImage('prof-5').imageUrl,
    photoHint: getImage('prof-5').imageHint,
    specialties: ['Instalación de Split', 'Mantenimiento'],
    avgRating: 4.6,
    categoryId: 23,
    isSubscriptionActive: false,
    subscriptionTier: 'standard',
    testimonials: [],
  },
  {
    id: 7,
    name: 'Alberto Gómez',
    phone: '2914123450',
    photoUrl: getImage('prof-1').imageUrl,
    photoHint: getImage('prof-1').imageHint,
    specialties: ['Paredes y Cimientos', 'Reformas'],
    avgRating: 4.9,
    categoryId: 13,
    priceInfo: 'Construcción desde $5000/m2. Consulte por reformas.',
    isSubscriptionActive: true,
    subscriptionTier: 'premium',
    testimonials: [
      {
        id: 8,
        clientName: 'Ricardo Diaz',
        clientPhotoUrl: getImage('client-3').imageUrl,
        clientPhotoHint: getImage('client-3').imageHint,
        rating: 5,
        text: 'Un trabajo de primera. Muy responsable y detallista.',
      },
    ],
  },
  {
    id: 8,
    name: 'Susana Giménez',
    photoUrl: getImage('prof-2').imageUrl,
    photoHint: getImage('prof-2').imageHint,
    specialties: ['Losa y Viguetas', 'Encadenados'],
    avgRating: 4.7,
    categoryId: 13,
    priceInfo: 'Presupuestos a medida.',
    isSubscriptionActive: true,
    subscriptionTier: 'standard',
    testimonials: [
      {
        id: 9,
        clientName: 'Mirtha Legrand',
        clientPhotoUrl: getImage('client-2').imageUrl,
        clientPhotoHint: getImage('client-2').imageHint,
        rating: 5,
        text: 'Cumplió en tiempo y forma. Muy recomendable.',
      },
       {
        id: 10,
        clientName: 'Marcelo Tinelli',
        clientPhotoUrl: getImage('client-4').imageUrl,
        clientPhotoHint: getImage('client-4').imageHint,
        rating: 4,
        text: 'Buen trabajo en general.',
      },
    ],
  },
  {
    id: 9,
    name: 'Esteban Quito',
    phone: '2914123451',
    photoUrl: getImage('prof-3').imageUrl,
    photoHint: getImage('prof-3').imageHint,
    specialties: ['Colocación de Ladrillos', 'Revoque'],
    avgRating: 4.2,
    categoryId: 13,
    priceInfo: 'Revoque fino y grueso. Consulte precios.',
    isSubscriptionActive: true,
    subscriptionTier: 'standard',
    testimonials: [
      {
        id: 11,
        clientName: 'Elsa Pato',
        clientPhotoUrl: getImage('client-1').imageUrl,
        clientPhotoHint: getImage('client-1').imageHint,
        rating: 4,
        text: 'Quedó bien el revoque.',
      },
    ],
  },
];

export const BANNERS: Banner[] = [
  {
    id: 1,
    title: 'Descuentos de Invierno en Calefacción',
    description:
      'Prepara tu hogar para el frío. 20% de descuento en instalación y mantenimiento de sistemas de calefacción.',
    imageUrl: getImage('promo-banner-1').imageUrl,
    imageHint: getImage('promo-banner-1').imageHint,
    buttonText: 'Ver Profesionales',
    buttonLink: '/servicios/aire-acondicionado-y-calefaccion',
  },
  {
    id: 2,
    title: 'Renueva tu Hogar',
    description:
      'Servicios de pintura y carpintería para darle una nueva vida a tus espacios. Pide tu presupuesto sin cargo.',
    imageUrl: getImage('promo-banner-3').imageUrl,
    imageHint: getImage('promo-banner-3').imageHint,
    buttonText: 'Explorar Servicios',
    buttonLink: '/servicios',
  },
  {
    id: 3,
    title: '¿Emergencia Eléctrica?',
    description: 'Electricistas matriculados disponibles 24/7 para urgencias.',
    imageUrl: getImage('promo-banner-2').imageUrl,
    imageHint: getImage('promo-banner-2').imageHint,
    buttonText: 'Buscar Electricista',
    buttonLink: '/servicios/electricidad',
  },
];

    