import {
  Wrench,
  Plug,
  Paintbrush,
  Hammer,
  Wind,
  DoorOpen,
  Flower,
  Computer,
  Building,
  SprayCan,
  Truck,
  Sparkles,
  PartyPopper,
  GraduationCap,
  HeartHandshake,
  Palette,
  ChefHat,
  Tractor,
  Lightbulb,
  ShieldCheck,
  Briefcase,
  Brush,
} from 'lucide-react';
import type { Category, Professional, Banner, Client } from '@/lib/types';
import { placeholderImages } from './placeholder-images';
import { subMonths, subDays } from 'date-fns';

const getImage = (id: string) =>
  placeholderImages.find((img) => img.id === id) || {
    imageUrl: '',
    imageHint: '',
    description: '',
  };

export const CATEGORIES: Category[] = [
  {
    id: 1,
    name: 'Construcción y Mantenimiento',
    icon: Building,
    description: 'Expertos en construcción, reformas y mantenimiento general del hogar.',
  },
  {
    id: 2,
    name: 'Jardinería y Paisajismo',
    icon: Flower,
    description: 'Cuidado y diseño de espacios verdes, desde jardines hasta parques.',
  },
  {
    id: 3,
    name: 'Limpieza y Mantenimiento',
    icon: Sparkles,
    description: 'Servicios de limpieza profunda para hogares, oficinas y más.',
  },
  {
    id: 4,
    name: 'Transporte y Logística',
    icon: Truck,
    description: 'Soluciones de mudanza, fletes y transporte de mercaderías.',
  },
  {
    id: 5,
    name: 'Reparaciones y Servicios Técnicos',
    icon: Wrench,
    description: 'Técnicos especializados en la reparación de todo tipo de equipos.',
  },
  {
    id: 6,
    name: 'Eventos y Entretenimiento',
    icon: PartyPopper,
    description: 'Todo lo que necesitas para que tu evento sea un éxito.',
  },
  {
    id: 7,
    name: 'Educación y Clases',
    icon: GraduationCap,
    description: 'Profesores y tutores para todas las edades y niveles.',
  },
  {
    id: 8,
    name: 'Salud, Bienestar y Estética',
    icon: HeartHandshake,
    description: 'Cuidado personal, masajes, y terapias para tu bienestar.',
  },
  {
    id: 9,
    name: 'Arte, Diseño y Comunicación',
    icon: Palette,
    description: 'Creativos para diseño gráfico, web, fotografía y más.',
  },
  {
    id: 10,
    name: 'Alimentación y Comercio',
    icon: ChefHat,
    description: 'Desde panaderías hasta delivery, todo para el deleite de tu paladar.',
  },
  {
    id: 11,
    name: 'Plomería',
    icon: Wrench,
    description: 'Soluciones para tuberías, grifos y filtraciones.',
  },
  {
    id: 12,
    name: 'Gasista',
    icon: Wind,
    description: 'Instalación y reparación de redes de gas.',
  },
  {
    id: 13,
    name: 'Albañilería',
    icon: Hammer,
    description: 'Construcción y reformas.',
  },
  {
    id: 14,
    name: 'Electricidad',
    icon: Plug,
    description: 'Instalaciones y reparaciones eléctricas.',
  },
  {
    id: 15,
    name: 'Carpintería',
    icon: Hammer,
    description: 'Muebles, reparaciones en madera y metal.',
  },
  {
    id: 16,
    name: 'Herrería',
    icon: Hammer,
    description: 'Trabajos en hierro y soldaduras.',
  },
  {
    id: 17,
    name: 'Pintura',
    icon: Paintbrush,
    description: 'Servicios de pintura para interiores y exteriores.',
  },
  {
    id: 18,
    name: 'Techistas',
    icon: Hammer,
    description: 'Reparación y construcción de techos.',
  },
  {
    id: 19,
    name: 'Impermeabilización',
    icon: SprayCan,
    description: 'Protección contra filtraciones en techos y terrazas.',
  },
  {
    id: 20,
    name: 'Revestimientos',
    icon: Brush,
    description: 'Instalación de pisos y cerámicos.',
  },
  {
    id: 21,
    name: 'Reparación de Baños y Cocinas',
    icon: Wrench,
    description: 'Arreglos y renovaciones completas.',
  },
  {
    id: 22,
    name: 'Iluminación LED',
    icon: Lightbulb,
    description: 'Instalación de sistemas de iluminación eficientes.',
  },
  {
    id: 23,
    name: 'Aire Acondicionado y Calefacción',
    icon: Wind,
    description: 'Instalación y mantenimiento de equipos.',
  },
  {
    id: 24,
    name: 'Reparación de Calefones y Termotanques',
    icon: Wrench,
    description: 'Servicio técnico para agua caliente.',
  },
  {
    id: 25,
    name: 'Energía Solar',
    icon: Lightbulb,
    description: 'Instalación de paneles solares.',
  },
  {
    id: 26,
    name: 'Corte de Césped',
    icon: Tractor,
    description: 'Mantenimiento de césped y jardines.',
  },
  {
    id: 27,
    name: 'Poda y Tala de Árboles',
    icon: Hammer,
    description: 'Servicios de poda y remoción de árboles.',
  },
  {
    id: 28,
    name: 'Riego Automático',
    icon: Flower,
    description: 'Instalación de sistemas de riego.',
  },
  {
    id: 29,
    name: 'Plantas y Macetas',
    icon: Flower,
    description: 'Venta y asesoramiento en plantas.',
  },
  {
    id: 30,
    name: 'Limpieza de Vidrios',
    icon: Sparkles,
    description: 'Limpieza profesional de ventanas y vidrios.',
  },
  {
    id: 31,
    name: 'Limpieza de Alfombras',
    icon: Sparkles,
    description: 'Limpieza profunda de alfombras y tapizados.',
  },
  {
    id: 32,
    name: 'Limpieza de Techos y Canaletas',
    icon: Sparkles,
    description: 'Mantenimiento y limpieza de techos.',
  },
  {
    id: 33,
    name: 'Repartidor / Delivery',
    icon: Truck,
    description: 'Servicios de entrega y mensajería.',
  },
  {
    id: 34,
    name: 'Fletes y Transportes Pequeños',
    icon: Truck,
    description: 'Transporte de objetos y pequeñas mudanzas.',
  },
  {
    id: 35,
    name: 'Guardamuebles / Depósitos',
    icon: Building,
    description: 'Almacenamiento seguro de tus pertenencias.',
  },
  {
    id: 36,
    name: 'Alquiler de Maquinaria',
    icon: Tractor,
    description: 'Alquiler de camiones, grúas y andamios.',
  },
  {
    id: 37,
    name: 'Reparación de Electrodomésticos',
    icon: Wrench,
    description: 'Servicio técnico para tus aparatos.',
  },
  {
    id: 38,
    name: 'Reparación de Computadoras y Celulares',
    icon: Computer,
    description: 'Soporte técnico para tus dispositivos.',
  },
  {
    id: 39,
    name: 'Mecánica de Autos y Motos',
    icon: Wrench,
    description: 'Servicios de mecánica ligera y pesada.',
  },
  {
    id: 40,
    name: 'Lavado y Pintura de Autos',
    icon: SprayCan,
    description: 'Detallado y pintura automotriz.',
  },
  {
    id: 41,
    name: 'Tapicería',
    icon: Brush,
    description: 'Renovación de tapizados de autos y muebles.',
  },
  {
    id: 42,
    name: 'Soldadura y Tornería',
    icon: Hammer,
    description: 'Trabajos de precisión en metal.',
  },
  {
    id: 43,
    name: 'Sistemas de Seguridad y Cámaras',
    icon: ShieldCheck,
    description: 'Instalación de sistemas de vigilancia.',
  },
  {
    id: 44,
    name: 'Seguridad Informática',
    icon: ShieldCheck,
    description: 'Protección de datos y sistemas.',
  },
  {
    id: 45,
    name: 'Electricidad y Plomería Industrial',
    icon: Briefcase,
    description: 'Servicios especializados para industrias.',
  },
  {
    id: 46,
    name: 'Catering y Organización de Eventos',
    icon: PartyPopper,
    description: 'Planificación y servicio gastronómico.',
  },
  {
    id: 47,
    name: 'Animación y Shows',
    icon: PartyPopper,
    description: 'Entretenimiento para fiestas y eventos.',
  },
  {
    id: 48,
    name: 'Música, Sonido e Iluminación',
    icon: PartyPopper,
    description: 'Equipamiento y DJs para eventos.',
  },
  {
    id: 49,
    name: 'Fotografía y Video para Eventos',
    icon: PartyPopper,
    description: 'Cobertura profesional de tus momentos.',
  },
  {
    id: 50,
    name: 'Decoración de Eventos',
    icon: PartyPopper,
    description: 'Ambientación y decoración para fiestas.',
  },
  {
    id: 51,
    name: 'Clases Particulares',
    icon: GraduationCap,
    description: 'Apoyo escolar y clases de diversas materias.',
  },
  {
    id: 52,
    name: 'Clases de Arte y Música',
    icon: GraduationCap,
    description: 'Aprende a tocar un instrumento o a pintar.',
  },
  {
    id: 53,
    name: 'Talleres',
    icon: GraduationCap,
    description: 'Cerámica, carpintería, costura y más.',
  },
  {
    id: 54,
    name: 'Clases de Idiomas y Cocina',
    icon: GraduationCap,
    description: 'Aprende nuevas habilidades.',
  },
  {
    id: 55,
    name: 'Cuidado de Personas y Mascotas',
    icon: HeartHandshake,
    description: 'Cuidadores para niños, adultos mayores y mascotas.',
  },
  {
    id: 56,
    name: 'Estética a Domicilio',
    icon: HeartHandshake,
    description: 'Peluquería, manicuría y más en tu casa.',
  },
  {
    id: 57,
    name: 'Terapias y Bienestar',
    icon: HeartHandshake,
    description: 'Masajes, fisioterapia, psicología y más.',
  },
  {
    id: 58,
    name: 'Entrenamiento y Coaching',
    icon: HeartHandshake,
    description: 'Yoga, Pilates y entrenamiento personal.',
  },
  {
    id: 59,
    name: 'Diseño Gráfico y Web',
    icon: Palette,
    description: 'Diseño de logos y desarrollo de sitios web.',
  },
  {
    id: 60,
    name: 'Desarrollo de Apps y Programación',
    icon: Computer,
    description: 'Programadores freelance para tus proyectos.',
  },
  {
    id: 61,
    name: 'Marketing Digital y Cartelería',
    icon: Palette,
    description: 'Promociona tu negocio.',
  },
  {
    id: 62,
    name: 'Fotografía, Video e Impresión 3D',
    icon: Palette,
    description: 'Servicios creativos y de producción.',
  },
  {
    id: 63,
    name: 'Artesanía y Manualidades',
    icon: Palette,
    description: 'Productos únicos hechos a mano.',
  },
];


export const PROFESSIONALS: Professional[] = [
  {
    id: 1,
    name: 'Carlos Rodriguez',
    email: 'carlos.rodriguez@oficios.com',
    phone: '2914123456',
    photoUrl: getImage('prof-1').imageUrl,
    photoHint: getImage('prof-1').imageHint,
    specialties: ['Reparación de Fugas', 'Instalación de Grifería', 'Destapaciones'],
    avgRating: 4.8,
    categoryId: 11,
    priceInfo: 'Hora de trabajo desde $2500 ARS. Presupuestos sin cargo.',
    isSubscriptionActive: false,
    subscriptionTier: 'standard',
    registrationDate: subMonths(new Date(), 2),
    lastPaymentDate: subMonths(new Date(), 2),
    isActive: true,
    testimonials: [
      {
        id: 1,
        clientName: 'Ana Gomez',
        clientPhotoUrl: getImage('client-1').imageUrl,
        clientPhotoHint: getImage('client-1').imageHint,
        rating: 5,
        text: 'Excelente servicio. Rápido y muy profesional.',
      },
      {
        id: 2,
        clientName: 'Juan Pérez',
        clientPhotoUrl: getImage('client-3').imageUrl,
        clientPhotoHint: getImage('client-3').imageHint,
        rating: 4,
        text: 'Buen trabajo, resolvió el problema de la tubería eficientemente.',
      },
    ],
    workPhotos: [
      getImage('work-3'),
    ],
  },
  {
    id: 2,
    name: 'Lucía Fernandez',
    email: 'lucia.fernandez@oficios.com',
    phone: '2914123457',
    photoUrl: getImage('prof-2').imageUrl,
    photoHint: getImage('prof-2').imageHint,
    specialties: ['Instalaciones Eléctricas', 'Tableros', 'Reparación de Cortocircuitos'],
    avgRating: 5.0,
    categoryId: 14,
    priceInfo: 'Consultar por instalación. Revisiones desde $2000 ARS.',
    isSubscriptionActive: true,
    subscriptionTier: 'premium',
    registrationDate: subDays(new Date(), 15),
    lastPaymentDate: subDays(new Date(), 10),
    isActive: true,
    testimonials: [
      {
        id: 3,
        clientName: 'María López',
        clientPhotoUrl: getImage('client-2').imageUrl,
        clientPhotoHint: getImage('client-2').imageHint,
        rating: 5,
        text: '¡Impecable! Muy prolija y atenta a los detalles.',
      },
      {
        id: 4,
        clientName: 'Pedro Martins',
        clientPhotoUrl: getImage('client-4').imageUrl,
        clientPhotoHint: getImage('client-4').imageHint,
        rating: 5,
        text: 'La mejor electricista de la ciudad. Totalmente recomendada.',
      },
    ],
    workPhotos: [
      getImage('work-5'),
    ]
  },
  {
    id: 3,
    name: 'Miguel Torres',
    email: 'miguel.torres@oficios.com',
    phone: '2914123458',
    photoUrl: getImage('prof-3').imageUrl,
    photoHint: getImage('prof-3').imageHint,
    specialties: ['Pintura de Interiores', 'Empapelado', 'Pintura de Exteriores'],
    avgRating: 4.5,
    categoryId: 17,
    priceInfo: 'Presupuestos a medida según m2. Incluye materiales.',
    isSubscriptionActive: true,
    subscriptionTier: 'standard',
    registrationDate: subMonths(new Date(), 6),
    lastPaymentDate: subDays(new Date(), 5),
    isActive: true,
    testimonials: [
      {
        id: 5,
        clientName: 'Laura Sanchez',
        clientPhotoUrl: getImage('client-1').imageUrl,
        clientPhotoHint: getImage('client-1').imageHint,
        rating: 4,
        text: 'El departamento quedó como nuevo, aunque tardó un poco más de lo esperado.',
      },
    ],
    workPhotos: [
        getImage('work-2'),
    ]
  },
  {
    id: 4,
    name: 'Jorge Herrera',
    email: 'jorge.herrera@oficios.com',
    phone: '2914123459',
    photoUrl: getImage('prof-4').imageUrl,
    photoHint: getImage('prof-4').imageHint,
    specialties: ['Muebles a Medida', 'Restauración de Muebles'],
    avgRating: 4.9,
    categoryId: 15,
    isSubscriptionActive: true,
    subscriptionTier: 'premium',
    registrationDate: subMonths(new Date(), 1),
    lastPaymentDate: subDays(new Date(), 20),
    isActive: false,
    testimonials: [
      {
        id: 6,
        clientName: 'Sofía Castro',
        clientPhotoUrl: getImage('client-2').imageUrl,
        clientPhotoHint: getImage('client-2').imageHint,
        rating: 5,
        text: 'El ropero que diseñó es perfecto. Un verdadero artesano.',
      },
    ],
    workPhotos: [
        getImage('work-4'),
    ]
  },
];

export const BANNERS: Banner[] = [
  {
    id: 1,
    title: 'Dejá tu casa como nueva',
    description: 'Encontrá pintores y albañiles para renovar tus espacios.',
    imageUrl: getImage('work-1').imageUrl,
    imageHint: getImage('work-1').imageHint,
    buttonText: 'Ver Profesionales',
    buttonLink: '/servicios/construccion-y-mantenimiento',
  },
  {
    id: 2,
    title: 'Soluciones para el hogar',
    description: 'Plomeros, gasistas y electricistas listos para ayudarte.',
    imageUrl: getImage('work-3').imageUrl,
    imageHint: getImage('work-3').imageHint,
    buttonText: 'Buscar Técnicos',
    buttonLink: '/servicios/reparaciones-y-servicios-tecnicos',
  },
  {
    id: 3,
    title: 'Dale vida a tu jardín',
    description:
      'Expertos en paisajismo y mantenimiento de espacios verdes.',
    imageUrl: getImage('work-6').imageUrl,
    imageHint: getImage('work-6').imageHint,
    buttonText: 'Contratar Jardineros',
    buttonLink: '/servicios/jardineria-y-paisajismo',
  },
  {
    id: 4,
    title: 'Servicios de Pintura',
    description: 'Dale un nuevo color a tu vida con pintores expertos.',
    imageUrl: 'https://i0.wp.com/villamariavivo.com/wp-content/uploads/2025/05/Chamtac-Pintores-en-Cordoba.png?fit=600%2C315&ssl=1',
    imageHint: 'painter working',
    buttonText: 'Ver Pintores',
    buttonLink: '/servicios/pintura',
  },
];

export const CLIENTS: Client[] = [
    {
        id: 1,
        name: 'Ana Gomez',
        email: 'ana.gomez@cliente.com',
        photoUrl: getImage('client-1').imageUrl,
        registrationDate: subDays(new Date(), 5),
        isActive: true,
    },
    {
        id: 2,
        name: 'Juan Pérez',
        email: 'juan.perez@cliente.com',
        photoUrl: getImage('client-3').imageUrl,
        registrationDate: subMonths(new Date(), 3),
        isActive: true,
    },
    {
        id: 3,
        name: 'María López',
        email: 'maria.lopez@cliente.com',
        photoUrl: getImage('client-2').imageUrl,
        registrationDate: subDays(new Date(), 90),
        isActive: false,
    }
]

    
