// src/lib/keywords/aire-acondicionado.ts
export const AIRE_ACONDICIONADO_KEYWORDS = [
  "instalar aire acondicionado",
  "instalar aire split",
  "instalar aire ventana",
  "instalar aire portátil",
  "instalar aire frío calor",
  "instalar aire frío",
  "instalar aire calor",
  "instalar aire nuevo",
  "instalar aire en casa",
  "instalar aire en depto",
  "instalar aire en oficina",
  "instalar aire en local",
  "instalar aire en comercio",
  "instalar aire en habitación",
  "instalar aire en dormitorio",
  "instalar aire en living",
  "instalar aire en cocina",
  "instalar aire en salón",
  "instalar aire en taller",
  "instalar aire en garage",
  "reparar aire acondicionado",
  "reparar aire split",
  "reparar aire ventana",
  "reparar aire portátil",
  "reparar aire frío calor",
  "reparar aire que no enfría",
  "reparar aire que no calienta",
  "reparar aire que gotea",
  "reparar aire que hace ruido",
  "reparar aire que pierde gas",
  "reparar aire que tira agua",
  "reparar aire que no prende",
  "reparar aire que corta luz",
  "reparar aire que tira olor",
  "mantenimiento aire acondicionado",
  "mantenimiento aire split",
  "mantenimiento aire ventana",
  "mantenimiento aire portátil",
  "mantenimiento aire frío calor",
  "limpiar aire acondicionado",
  "limpiar aire split",
  "limpiar aire ventana",
  "limpiar aire portátil",
  "limpiar filtros aire",
  "limpiar filtros split",
  "limpiar filtros ventana",
  "limpiar filtros portátil",
  "cargar gas aire",
  "cargar gas split",
  "cargar gas ventana",
  "cargar gas portátil",
  "recargar gas aire",
  "recargar gas split",
  "recargar gas ventana",
  "recargar gas portátil",
  "cargar gas refrigerante",
  "recargar gas refrigerante",
  "recarga de gas aire",
  "recarga de gas split",
  "recarga de gas ventana",
  "recarga de gas portátil",
  "revisar aire acondicionado",
  "revisar aire split",
  "revisar aire ventana",
  "revisar aire portátil",
  "revisar aire frío calor",
  "revisar compresor aire",
  "reparar compresor aire",
  "cambiar compresor aire",
  "cambiar motor aire",
  "cambiar motor split",
  "cambiar motor ventana",
  "cambiar motor portátil",
  "reparar motor aire",
  "instalar compresor aire",
  "instalar motor aire",
  "cambiar termostato aire",
  "reparar termostato aire",
  "instalar termostato aire",
  "cambiar filtro aire",
  "cambiar filtro split",
  "cambiar filtro ventana",
  "cambiar filtro portátil",
  "cambiar válvula aire",
  "reparar válvula aire",
  "instalar válvula aire",
  "revisar gas aire",
  "revisar presión gas aire",
  "revisar presión split",
  "revisar presión ventana",
  "revisar presión portátil",
  "aire acondicionado gotea",
  "aire split gotea",
  "aire ventana gotea",
  "aire portátil gotea",
  "aire acondicionado tira agua",
  "aire split tira agua",
  "aire ventana tira agua",
  "aire portátil tira agua",
  "aire acondicionado no enfría",
  "aire split no enfría",
  "aire ventana no enfría",
  "aire portátil no enfría",
  "aire acondicionado no calienta",
  "aire split no calienta",
  "aire ventana no calienta",
  "aire portátil no calienta",
  "aire acondicionado ruido",
  "aire split ruido",
  "aire ventana ruido",
  "aire portátil ruido",
  "aire acondicionado olor",
  "aire split olor",
  "aire ventana olor",
  "aire portátil olor",
  "aire acondicionado mantenimiento",
  "aire split mantenimiento",
  "aire ventana mantenimiento",
  "aire portátil mantenimiento",
  "aire acondicionado limpieza",
  "aire split limpieza",
  "aire ventana limpieza",
  "aire portátil limpieza",
  "aire acondicionado instalación urgente",
  "aire split instalación urgente",
  "aire ventana instalación urgente",
  "aire portátil instalación urgente",
  "técnico aire acondicionado",
  "técnico aire split",
  "técnico aire ventana",
  "técnico aire portátil",
  "servicio aire acondicionado",
  "servicio aire split",
  "servicio aire ventana",
  "servicio aire portátil",
  "reparación aire a domicilio",
  "carga de gas aire a domicilio",
  "mantenimiento a domicilio aire",
  "limpieza a domicilio aire",
  "instalación a domicilio aire",
  "instalar aire frío",
  "instalar aire calor",
  "instalar aire frio/calor",
  "reparar aire frio",
  "reparar aire calor",
  "reparar aire frio/calor",
  "aire acondicionado portátil",
  "aire acondicionado split",
  "aire acondicionado ventana",
  "aire acondicionado frio calor",
  "aire split frio calor",
  "aire split no funciona",
  "aire split descompuesto",
  "aire split roto",
  "aire split instalación",
  "aire split mantenimiento",
  "aire split limpieza",
  "aire split reparación",
  "aire split urgente",
  "aire ventana no funciona",
  "aire ventana descompuesto",
  "aire ventana roto",
  "aire ventana instalación",
  "aire ventana mantenimiento",
  "aire ventana limpieza",
  "aire ventana reparación",
  "aire ventana urgente",
  "aire portátil no funciona",
  "aire portátil descompuesto",
  "aire portátil roto",
  "aire portátil instalación",
  "aire portátil mantenimiento",
  "aire portátil limpieza",
  "aire portátil reparación",
  "aire portátil urgente",
  "aire acondicionado split",
  "aire acondicionado ventana",
  "aire acondicionado portátil",
  "aire acondicionado frío",
  "aire acondicionado calor",
  "aire acondicionado frío/calor",
  "aire acondicionado goteando",
  "aire split goteando",
  "aire ventana goteando",
  "aire portátil goteando",
  "aire acondicionado filtrado",
  "aire split filtrado",
  "aire ventana filtrado",
  "aire portátil filtrado",
  "aire acondicionado gas",
  "aire split gas",
  "aire ventana gas",
  "aire portátil gas",
  "recarga de gas aire acondicionado",
  "recarga de gas split",
  "recarga de gas ventana",
  "recarga de gas portátil",
  "limpieza de filtros aire acondicionado",
  "limpieza de filtros split",
  "limpieza de filtros ventana",
];
