// src/lib/keywords/albanileria.ts
export const ALBANILERIA_KEYWORDS = [
  "Albañil a domicilio",
  "Construcción de paredes",
  "Levantamiento de muros",
  "Revoque",
  "Revoque grueso",
  "Revoque fino",
  "Revoque exterior",
  "Revoque interior",
  "Enlucido de paredes",
  "Enlucido fino",
  "Enlucido grueso",
  "Revoque con cemento",
  "Revoque con cal",
  "Revoque impermeable",
  "Revoque con arena",
  "Revoque hidrófugo",
  "Reparación de paredes",
  "Reparación de muros",
  "Reparación de revoque",
  "Reparación de grietas",
  "Sellado de grietas",
  "Nivelación de paredes",
  "Nivelación de muros",
  "Construcción de casas",
  "Construcción de paredes internas",
  "Construcción de paredes externas",
  "Construcción de muros de contención",
  "Construcción de cimientos",
  "Cimiento de hormigón",
  "Cimiento armado",
  "Cimiento tradicional",
  "Levantamiento de columnas",
  "Columnas de hormigón",
  "Columnas de ladrillo",
  "Columnas de block",
  "Construcción de tabiques",
  "Tabiques de ladrillo",
  "Tabiques de block",
  "Tabiques de yeso",
  "Paredes de ladrillo",
  "Paredes de block",
  "Paredes de cemento",
  "Paredes de ladrillo hueco",
  "Paredes de ladrillo macizo",
  "Paredes reforzadas",
  "Paredes de mampostería",
  "Paredes exteriores",
  "Paredes interiores",
  "Construcción de paredes divisorias",
  "Construcción de paredes medianeras",
  "Revestimiento de paredes",
  "Revestimiento de muros",
  "Revestimiento cerámico",
  "Revestimiento de yeso",
  "Revestimiento de cemento",
  "Revestimiento de ladrillo",
  "Alicatado",
  "Alicatado de baños",
  "Alicatado de cocinas",
  "Colocación de cerámicos",
  "Colocación de azulejos",
  "Colocación de pisos",
  "Colocación de porcelanato",
  "Colocación de mosaico",
  "Colocación de venecita",
  "Colocación de piedra",
  "Colocación de ladrillos",
  "Colocación de block",
  "Colocación de revoque",
  "Colocación de yeso",
  "Colocación de revoque exterior",
  "Colocación de revoque interior",
  "Colocación de molduras",
  "Colocación de cenefas",
  "Colocación de guardas",
  "Colocación de bordes",
  "Construcción de escalera",
  "Escaleras de hormigón",
  "Escaleras de ladrillo",
  "Escaleras de madera",
  "Escaleras de metal",
  "Construcción de parrilla",
  "Parrilla de ladrillo",
  "Parrilla de cemento",
  "Parrilla con ladrillos refractarios",
  "Parrilla con acero",
  "Construcción de garaje",
  "Construcción de quincho",
  "Construcción de deck",
  "Construcción de pérgola",
  "Construcción de galpón",
  "Construcción de depósito",
  "Construcción de tinglado",
  "Construcción de cerramiento",
  "Construcción de muro de contención",
  "Construcción de tapial",
  "Construcción de ladrillo común",
  "Construcción de ladrillo hueco",
  "Construcción de ladrillo macizo",
  "Construcción de block hueco",
  "Construcción de block macizo",
  "Construcción de pared reforzada",
  "Impermeabilización de paredes",
  "Impermeabilización de techos",
  "Impermeabilización de terrazas",
  "Impermeabilización de balcones",
  "Impermeabilización de cimientos",
  "Sellado de filtraciones",
  "Sellado de grietas",
  "Reparación de humedad",
  "Reparación de goteras",
  "Reparación de filtraciones",
  "Reparación de muros",
  "Reparación de paredes",
  "Reparación de pisos",
  "Reparación de techos",
  "Reparación de revoque",
  "Reparación de enlucido",
  "Reparación de albañilería",
  "Refacción de casa",
  "Refacción de departamento",
  "Refacción de edificio",
  "Refacción de local",
  "Refacción de oficina",
  "Refacción de baño",
  "Refacción de cocina",
  "Refacción de quincho",
  "Refacción de parrilla",
  "Refacción de galpón",
  "Refacción de depósito",
  "Refacción de fachada",
  "Refacción de terraza",
  "Refacción de balcón",
  "Refacción de muro",
  "Refacción de tabique",
  "Refacción de pared",
  "Refacción de piso",
  "Refacción de escalera",
  "Refacción de muro de contención",
  "Levantamiento de muro",
  "Levantamiento de pared",
  "Levantamiento de tabique",
  "Levantamiento de columna",
  "Levantamiento de cimiento",
  "Levantamiento de piso",
  "Levantamiento de escalera",
  "Levantamiento de parrilla",
  "Levantamiento de galpón",
  "Levantamiento de depósito",
  "Levantamiento de quincho",
  "Colocación de hormigón",
  "Colocación de cemento",
  "Colocación de arena",
  "Colocación de cal",
  "Colocación de piedra",
  "Colocación de ladrillo",
  "Colocación de block",
  "Colocación de cerámico",
  "Colocación de porcelanato",
  "Colocación de mosaico",
  "Colocación de venecita",
  "Colocación de yeso",
  "Colocación de revoque",
  "Colocación de moldura",
  "Colocación de cenefa",
  "Colocación de guarda",
  "Colocación de borde",
  "Mezcla de cemento",
  "Mezcla de hormigón",
  "Mezcla de arena",
  "Mezcla de cal",
  "Mezcla para revoque",
  "Mezcla para enlucido",
  "Mezcla para pared",
  "Mezcla para piso",
  "Mezcla para escalera",
  "Mezcla para muro",
  "Mezcla para columnas",
  "Mezcla para cimientos",
  "Hormigonado",
  "Hormigonado de piso",
  "Hormigonado de escalera",
  "Hormigonado de muro",
  "Hormigonado de columna",
  "Hormigonado de cimiento",
  "Colocación de ladrillos",
  "Colocación de bloques",
  "Colocación de piedra",
  "Colocación de cerámica",
  "Colocación de azulejos",
  "Colocación de porcelanato",
  "Colocación de mosaico",
  "Colocación de venecita",
  "Colocación de yeso",
  "Colocación de revoque",
  "Colocación de molduras",
  "Colocación de cenefas",
  "Colocación de guardas",
  "Colocación de bordes",
  "Albañilería residencial",
  "Albañilería comercial",
  "Albañilería industrial",
  "Albañilería en obra nueva",
  "Albañilería en refacción",
  "Albañilería rápida",
  "Albañilería económica",
  "Albañilería con garantía",
  "Albañilería profesional",
  "Albañilería con materiales propios",
  "Albañilería con materiales del cliente",
  "Albañilería de confianza",
  "Albañilería a medida",
  "Albañilería urgente",
  "Albañilería en fin de semana",
  "Albañilería nocturna",
  "Albañilería diurna",
  "Albañilería de paredes",
  "Albañilería de muros",
  "Albañilería de tabiques",
  "Albañilería de columnas",
  "Albañilería de cimientos",
  "Albañilería de pisos",
  "Albañilería de escalera",
  "Albañilería de parrilla",
  "Albañilería de galpón",
  "Albañilería de depósito",
  "Albañilería de quincho",
  "Albañilería de fachada",
  "Albañilería de terraza",
  "Albañilería de balcón",
  "Albañilería de muro de contención",
  "Albañilería decorativa",
  "Albañilería artística",
  "Albañilería con ladrillo visto",
  "Albañilería con ladrillo pintado",
  "Albañilería con ladrillo revestido",
  "Albañilería con revoque",
  "Albañilería con yeso",
  "Albañilería con molduras",
  "Albañilería con cenefas",
  "Albañilería con guardas",
  "Albañilería con bordes",
  "Albañilería de baños",
  "Albañilería de cocinas",
  "Albañilería de livings",
  "Albañilería de dormitorios",
  "Albañilería de comedores",
  "Albañilería de oficinas",
  "Albañilería de locales comerciales",
  "Albañilería de industrias",
  "Albañilería de talleres",
  "Albañilería de depósitos",
  "Albañilería de galpones",
  "Albañilería de escuelas",
  "Albañilería de colegios",
  "Albañilería de hospitales",
  "Albañilería de clínicas",
  "Albañilería de laboratorios",
  "Albañilería de bibliotecas",
  "Albañilería de archivos",
  "Albañilería de centros culturales",
  "Albañilería de iglesias",
  "Albañilería de capillas",
  "Albañilería de templos",
  "Albañilería de patios",
  "Albañilería de jardines",
  "Albañilería de parques",
  "Albañilería de plazas",
  "Albañilería de veredas",
  "Albañilería de calles",
  "Albañilería de aceras",
  "Albañilería de senderos",
  "Albañilería de caminos",
  "Albañilería de rampas",
  "Albañilería de bordes",
  "Albañilería de muros medianeros",
  "Albañilería de muros exteriores",
  "Albañilería de muros interiores",
  "Albañilería de paredes divisorias",
  "Albañilería de tabiques divisores",
  "Albañilería de techos",
  "Albañilería de cielorrasos",
  "Albañilería de revestimientos",
  "Albañilería de pisos",
  "Albañilería de escaleras",
  "Albañilería de barandas",
  "Albañilería de pasamanos",
  "Albañilería de balcones",
  "Albañilería de terrazas",
  "Albañilería de galerías",
  "Albañilería de patios",
  "Albañilería de quinchos",
  "Albañilería de parrillas",
  "Albañilería de decks",
  "Albañilería de pérgolas",
  "Albañilería de galpones",
  "Albañilería de depósitos",
  "Albañilería de cerramientos",
  "Albañilería integral",
  "Albañilería profesional a domicilio"
];
