// src/lib/keywords/arreglo-heladeras.ts
export const ARREGLO_HELADERAS_KEYWORDS = [
  "no enfría",
  "enfría poco",
  "no congela",
  "congela de más",
  "hace ruido",
  "vibra",
  "pierde agua",
  "junta agua abajo",
  "pierde frío",
  "pierde gas",
  "no corta",
  "corta y arranca seguido",
  "no arranca",
  "no enciende",
  "se apaga",
  "motor caliente",
  "motor no arranca",
  "freezer no enfría",
  "heladera no enfría y freezer sí",
  "heladera enfría y freezer no",
  "forma hielo",
  "exceso de escarcha",
  "desagote tapado",
  "burlete roto",
  "puerta no cierra",
  "luz no prende",
  "olor feo"
];
