// src/lib/keywords/arreglo-lavarropas.ts
export const ARREGLO_LAVARROPAS_KEYWORDS = [
  "diagnóstico de fallas",
  "reparación general",
  "service técnico",
  "revisión completa",
  "puesta a punto",
  "no enciende",
  "no carga agua",
  "no desagota",
  "no centrifuga",
  "pierde agua",
  "hace ruido",
  "vibra en exceso",
  "corta el programa",
  "cambio de bomba de desagote",
  "cambio de rulemanes",
  "cambio de correas",
  "cambio de polea",
  "cambio de válvula de carga",
  "cambio de presostato",
  "cambio de plaqueta",
  "cambio de motor",
  "cambio de retenes",
  "limpieza de filtro",
  "destape de mangueras",
  "cambio de mangueras",
  "reparación de entrada de agua",
  "trabajos a domicilio",
  "mantenimiento preventivo",
  "reparación urgente",
  "lavarropas roto",
  "arreglar lavarropas"
];
