// src/lib/keywords/astrologia.ts
export const ASTROLOGIA_KEYWORDS = [
"carta natal",
"carta astral",
"lectura de carta natal",
"revolución solar",
"retorno solar",
"compatibilidad de signos",
"sinastría",
"tránsitos",
"luna en signos",
"luna llena",
"luna nueva",
"eclipse solar",
"eclipse lunar",
"mercurio retrógrado",
"venus retrógrado",
"marte retrógrado",
"ascendente",
"medio cielo",
"nodo norte",
"nodo sur",
"casas astrológicas",
"planetas en signos",
"astrología moderna",
"astrología psicológica",
"astrología kármica",
"astrología evolutiva",
"astrología terapéutica",
"lectura astrológica",
"sesión de carta natal",
"interpretación de carta",
"energía de los signos",
"signos del zodíaco",
"signos compatibles",
"energía lunar",
"temporada de eclipses",
"vibra de mercurio retrógrado",
"temporada escorpio",
"temporada libra",
"temporada leo",
"temporada acuario",
"energía capricorniana",
"energía pisciana",
"energía geminiana",
"energía canceriana",
"energía virginiana",
"astróloga",
"astrólogo",
"sesión de astrología",
"energía del universo",
"entendé tu carta"
];
