// src/lib/keywords/belleza.ts
export const BELLEZA_KEYWORDS = [
"Peluquería y cabello",
"corte de pelo",
"corte mujer",
"corte hombre",
"corte infantil",
"peluquería unisex",
"peluquería cerca mío",
"estilista",
"estilista en casa",
"tintura",
"coloración",
"mechas",
"balayage",
"reflejos",
"baño de luz",
"alisado",
"alisado definitivo",
"keratina",
"botox capilar",
"shock de keratina",
"nutrición capilar",
"hidratación capilar",
"tratamiento capilar",
"brushing",
"peinado",
"peinado de novia",
"peinado para fiesta",
"recogido",
"planchado",
"barbería",
"corte de barba",
"perfilado de barba",
"afeitado tradicional",
"barbero",
"peluquero a domicilio",
"corte en seco",
"cambio de look",
"corte moderno",
"flequillo",
"color fantasía",
"retoque de raíces",
"Uñas, manos y pies",
"manicura",
"manicurista",
"manicura express",
"manicura completa",
"esmaltado común",
"esmaltado semipermanente",
"uñas esculpidas",
"uñas acrílicas",
"uñas de gel",
"uñas soft gel",
"nail art",
"decoración de uñas",
"diseño de uñas",
"uñas francesas",
"pedicura",
"pedicuría profesional",
"pedicura spa",
"pies cuidados",
"limado de uñas",
"cutículas",
"uñas cortas",
"uñas largas",
"uñas naturales",
"uñas postizas",
"uñas cápsula",
"mantenimiento de uñas",
"retoque de uñas",
"retiro de esmalte",
"servicio de uñas",
"salón de uñas",
"uñas a domicilio",
"pintado de uñas",
"esmalte rojo",
"esmalte nude",
"uñas con brillo",
"uñas mate",
"uñas de colores",
"uñas decoradas",
"uñas para eventos",
"uñas elegantes",
"Estética facial y corporal",
"limpieza facial",
"limpieza profunda",
"tratamiento facial",
"hidratación facial",
"exfoliación facial",
"mascarilla facial",
"antiage",
"rejuvenecimiento",
"radiofrecuencia",
"peeling",
"lifting facial",
"perfilado de cejas",
"depilación de cejas",
"laminado de cejas",
"lifting de pestañas",
"extensión de pestañas",
"tinte de pestañas",
"belleza de cejas y pestañas",
"depilación",
"depilación con cera",
"depilación definitiva",
"depilación láser",
"depilación de bozo",
"depilación de piernas",
"depilación de axilas",
"depiladora",
"depilación en casa",
"masajes",
"masaje relajante",
"drenaje linfático",
"masaje descontracturante",
"masajes reductores",
"tratamientos reductores",
"tratamientos corporales",
"exfoliación corporal",
"fangoterapia",
"tratamientos reafirmantes",
"spa corporal",
"cuidados corporales",
"cuerpo y bienestar",
"Maquillaje y eventos",
"maquillaje",
"makeup artist",
"maquilladora profesional",
"maquillaje social",
"maquillaje para eventos",
"maquillaje de novia",
"maquillaje de día",
"maquillaje de noche",
"maquillaje para fotos",
"maquillaje artístico",
"maquillaje natural",
"maquillaje glam",
"peinado y maquillaje",
"makeup y peinado",
"servicio de makeup",
"maquillaje a domicilio",
"make up express",
"maquillaje para 15",
"maquillaje para fiesta",
"maquillaje de pasarela",
"Bienestar, spa y cuidado personal",
"spa",
"día de spa",
"centro de estética",
"estética integral",
"belleza y bienestar",
"tratamientos de belleza",
"belleza facial",
"belleza corporal",
"cuidado personal",
"rutina de belleza",
"skincare",
"cuidado de la piel",
"productos naturales",
"cosmética natural",
"cosmética vegana",
"aromaterapia",
"reflexología",
"masoterapia",
"belleza natural",
"tratamientos orgánicos",
"exfoliante natural",
"aceites esenciales",
"hidratación corporal",
"crema facial",
"crema corporal",
"cuidado capilar",
"cuidados de belleza",
"piel saludable",
"rostro luminoso",
"belleza profesional",
"Profesionales y negocios",
"esteticista",
"cosmetóloga",
"cosmetólogo",
"manicurista profesional",
"peluquero",
"peluquera",
"barbero",
"maquillador",
"maquilladora",
"técnica en belleza",
"profesional de estética",
"centro de estética",
"salón de belleza",
"estética móvil",
"estética a domicilio",
"estética en Bahía Blanca",
"profesional de belleza",
"especialista en uñas",
"especialista en piel",
"especialista en cejas",
"gabinete de estética",
"consultora de belleza",
"asesora de imagen",
"curso de belleza",
"curso de uñas",
"curso de maquillaje",
"curso de peluquería",
"curso de estética",
"belleza argentina",
"servicios de belleza"
];
