// src/lib/keywords/calefaccion.ts
export const CALEFACCION_KEYWORDS = [
  "instalación de radiadores",
  "reparación de radiadores",
  "purga de radiadores",
  "cambio de válvulas de radiador",
  "balanceo de radiadores",
  "instalación de caldera",
  "mantenimiento de caldera",
  "reparación de caldera",
  "limpieza de caldera",
  "losa radiante",
  "piso radiante",
  "instalación de piso radiante",
  "reparación de piso radiante",
  "mantenimiento de piso radiante",
  "instalación de estufas",
  "reparación de estufas",
  "cambio de estufa",
  "mantenimiento de estufas",
  "termostatos",
  "instalación de termostato",
  "cambio de termostato",
  "termostato digital",
  "bombas de circulación",
  "cambio de bomba de calefacción",
  "reparación de bomba",
  "calefacción domiciliaria",
  "calefacción central",
  "calefacción por radiadores",
  "calefacción por agua",
];
