// src/lib/keywords/carpinteria.ts
export const CARPINTERIA_KEYWORDS = [
  "Carpintero de muebles",
  "reparación de muebles",
  "fabricación de muebles",
  "Carpintero de casas",
  "Carpintero de puertas",
  "reparación de puertas",
  "fabricación de puertas",
  "Carpintero de ventanas",
  "reparación de ventanas",
  "fabricación de ventanas",
  "Carpintero de cocina",
  "reparación de cocina",
  "fabricación de cocina",
  "Carpintero de placares",
  "reparación de placares",
  "fabricación de placares",
  "Carpintero de estanterías",
  "reparación de estanterías",
  "fabricación de estanterías",
  "Carpintero de decks",
  "reparación de decks",
  "fabricación de decks",
  "Carpintero de pisos de madera",
  "reparación de pisos de madera",
  "fabricación de pisos de madera",
  "Carpintero de cercas de madera",
  "reparación de cercas de madera",
  "fabricación de cercas de madera",
  "Carpintero de muebles a medida",
  "reparación de muebles a medida",
  "fabricación de muebles a medida",
  "Carpintero de bibliotecas",
  "reparación de bibliotecas",
  "fabricación de bibliotecas",
  "Carpintero de muebles rústicos",
  "reparación de muebles rústicos",
  "fabricación de muebles rústicos",
  "Carpintero de muebles modernos",
  "reparación de muebles modernos",
  "fabricación de muebles modernos",
  "Carpintero de muebles infantiles",
  "reparación de muebles infantiles",
  "fabricación de muebles infantiles",
  "Carpintero de muebles de oficina",
  "reparación de muebles de oficina",
  "fabricación de muebles de oficina",
  "Carpintero de muebles para restaurante",
  "reparación de muebles para restaurante",
  "fabricación de muebles para restaurante",
  "Carpintero de muebles para comercio",
  "reparación de muebles para comercio",
  "fabricación de muebles para comercio",
  "Carpintero de muebles de melamina",
  "reparación de muebles de melamina",
  "fabricación de muebles de melamina",
  "Carpintero de muebles de MDF",
  "reparación de muebles de MDF",
  "fabricación de muebles de MDF",
  "Carpintero de muebles de madera maciza",
  "reparación de muebles de madera maciza",
  "fabricación de muebles de madera maciza",
  "Carpintero de muebles reciclados",
  "reparación de muebles reciclados",
  "fabricación de muebles reciclados",
  "Carpintero de muebles personalizados",
  "reparación de muebles personalizados",
  "fabricación de muebles personalizados",
  "Carpintero de muebles vintage",
  "reparación de muebles vintage",
  "fabricación de muebles vintage",
  "Carpintero de mesas",
  "reparación de mesas",
  "fabricación de mesas",
  "Carpintero de sillas",
  "reparación de sillas",
  "fabricación de sillas",
  "Carpintero de bancos",
  "reparación de bancos",
  "fabricación de bancos",
  "Carpintero de camas",
  "reparación de camas",
  "fabricación de camas",
  "Carpintero de cabeceras",
  "reparación de cabeceras",
  "fabricación de cabeceras",
  "Carpintero de cómodas",
  "reparación de cómodas",
  "fabricación de cómodas",
  "Carpintero de mesas de comedor",
  "reparación de mesas de comedor",
  "fabricación de mesas de comedor",
  "Carpintero de mesas de centro",
  "reparación de mesas de centro",
  "fabricación de mesas de centro",
  "Carpintero de mesas de luz",
  "reparación de mesas de luz",
  "fabricación de mesas de luz",
  "Carpintero de escritorios",
  "reparación de escritorios",
  "fabricación de escritorios",
  "Carpintero de estantes flotantes",
  "reparación de estantes flotantes",
  "fabricación de estantes flotantes",
  "Carpintero de estantes de pared",
  "reparación de estantes de pared",
  "fabricación de estantes de pared",
  "Carpintero de bibliotecas empotradas",
  "reparación de bibliotecas empotradas",
  "fabricación de bibliotecas empotradas",
  "Carpintero de placares empotrados",
  "reparación de placares empotrados",
  "fabricación de placares empotrados",
  "Carpintero de armarios",
  "reparación de armarios",
  "fabricación de armarios",
  "Carpintero de vestidores",
  "reparación de vestidores",
  "fabricación de vestidores",
  "Carpintero de cajoneras",
  "reparación de cajoneras",
  "fabricación de cajoneras",
  "Carpintero de puertas corredizas",
  "reparación de puertas corredizas",
  "fabricación de puertas corredizas",
  "Carpintero de puertas plegables",
  "reparación de puertas plegables",
  "fabricación de puertas plegables",
  "Carpintero de puertas de entrada",
  "reparación de puertas de entrada",
  "fabricación de puertas de entrada",
  "Carpintero de puertas interiores",
  "reparación de puertas interiores",
  "fabricación de puertas interiores",
  "Carpintero de ventanas corredizas",
  "reparación de ventanas corredizas",
  "fabricación de ventanas corredizas",
  "Carpintero de ventanas de madera",
  "reparación de ventanas de madera",
  "fabricación de ventanas de madera",
  "Carpintero de ventanas de PVC",
  "reparación de ventanas de PVC",
  "fabricación de ventanas de PVC",
  "Carpintero de ventanas de aluminio",
  "reparación de ventanas de aluminio",
  "fabricación de ventanas de aluminio",
  "Carpintero de rejas de madera",
  "reparación de rejas de madera",
  "fabricación de rejas de madera",
  "Carpintero de portones",
  "reparación de portones",
  "fabricación de portones",
  "Carpintero de decks de jardín",
  "reparación de decks de jardín",
  "fabricación de decks de jardín",
  "Carpintero de pérgolas",
  "reparación de pérgolas",
  "fabricación de pérgolas",
  "Carpintero de quinchos",
  "reparación de quinchos",
  "fabricación de quinchos",
  "Carpintero de gazebos",
  "reparación de gazebos",
  "fabricación de gazebos",
  "Carpintero de techos de madera",
  "reparación de techos de madera",
  "fabricación de techos de madera",
  "Carpintero de cielorrasos",
  "reparación de cielorrasos",
  "fabricación de cielorrasos",
  "Carpintero de molduras",
  "reparación de molduras",
  "fabricación de molduras",
  "Carpintero de marcos de puertas",
  "reparación de marcos de puertas",
  "fabricación de marcos de puertas",
  "Carpintero de marcos de ventanas",
  "reparación de marcos de ventanas",
  "fabricación de marcos de ventanas",
  "Carpintero de barandas",
  "reparación de barandas",
  "fabricación de barandas",
  "Carpintero de escaleras de madera",
  "reparación de escaleras de madera",
  "fabricación de escaleras de madera",
  "Carpintero de barandas de escaleras",
  "reparación de barandas de escaleras",
  "fabricación de barandas de escaleras",
  "Carpintero de pisos flotantes",
  "reparación de pisos flotantes",
  "fabricación de pisos flotantes",
  "Carpintero de tarimas",
  "reparación de tarimas",
  "fabricación de tarimas",
  "Carpintero de revestimientos de pared",
  "reparación de revestimientos de pared",
  "fabricación de revestimientos de pared",
  "Carpintero de revestimientos de techo",
  "reparación de revestimientos de techo",
  "fabricación de revestimientos de techo",
  "Carpintero de muebles de cocina",
  "reparación de muebles de cocina",
  "fabricación de muebles de cocina",
  "Carpintero de muebles de baño",
  "reparación de muebles de baño",
  "fabricación de muebles de baño",
  "Carpintero de muebles de living",
  "reparación de muebles de living",
  "fabricación de muebles de living",
  "Carpintero de muebles de dormitorio",
  "reparación de muebles de dormitorio",
  "fabricación de muebles de dormitorio",
  "Carpintero de muebles de comedor",
  "reparación de muebles de comedor",
  "fabricación de muebles de comedor",
  "Carpintero de muebles de jardín",
  "reparación de muebles de jardín",
  "fabricación de muebles de jardín",
  "Carpintero de muebles para balcón",
  "reparación de muebles para balcón",
  "fabricación de muebles para balcón",
  "Carpintero de muebles de terraza",
  "reparación de muebles de terraza",
  "fabricación de muebles de terraza",
  "Carpintero de bancos de exterior",
  "reparación de bancos de exterior",
  "fabricación de bancos de exterior",
  "Carpintero de sillas de exterior",
  "reparación de sillas de exterior",
  "fabricación de sillas de exterior",
  "Carpintero de mesas de exterior",
  "reparación de mesas de exterior",
  "fabricación de mesas de exterior",
  "Carpintero de pérgolas de madera",
  "reparación de pérgolas de madera",
  "fabricación de pérgolas de madera",
  "Carpintero de decks de terraza",
  "reparación de decks de terraza",
  "fabricación de decks de terraza",
  "Carpintero de muebles para bar",
  "reparación de muebles para bar",
  "fabricación de muebles para bar",
  "Carpintero de muebles para cafetería",
  "reparación de muebles para cafetería",
  "fabricación de muebles para cafetería",
];
