// src/lib/keywords/carpinteria.ts
export const CARPINTERIA_KEYWORDS = [
  "Carpintero de muebles",
  "Carpintero de casas",
  "Carpintero de puertas",
  "Carpintero de ventanas",
  "Carpintero de cocina",
  "Carpintero de placares",
  "Carpintero de estanterías",
  "Carpintero de decks",
  "Carpintero de pisos de madera",
  "Carpintero de cercas de madera",
  "Carpintero de muebles a medida",
  "Carpintero de bibliotecas",
  "Carpintero de muebles rústicos",
  "Carpintero de muebles modernos",
  "Carpintero de muebles infantiles",
  "Carpintero de muebles de oficina",
  "Carpintero de muebles para restaurante",
  "Carpintero de muebles para comercio",
  "Carpintero de muebles de melamina",
  "Carpintero de muebles de MDF",
  "Carpintero de muebles de madera maciza",
  "Carpintero de muebles reciclados",
  "Carpintero de muebles personalizados",
  "Carpintero de muebles vintage",
  "Carpintero de mesas",
  "Carpintero de sillas",
  "Carpintero de bancos",
  "Carpintero de camas",
  "Carpintero de cabeceras",
  "Carpintero de cómodas",
  "Carpintero de mesas de comedor",
  "Carpintero de mesas de centro",
  "Carpintero de mesas de luz",
  "Carpintero de escritorios",
  "Carpintero de estantes flotantes",
  "Carpintero de estantes de pared",
  "Carpintero de bibliotecas empotradas",
  "Carpintero de placares empotrados",
  "Carpintero de armarios",
  "Carpintero de vestidores",
  "Carpintero de cajoneras",
  "Carpintero de puertas corredizas",
  "Carpintero de puertas plegables",
  "Carpintero de puertas de entrada",
  "Carpintero de puertas interiores",
  "Carpintero de ventanas corredizas",
  "Carpintero de ventanas de madera",
  "Carpintero de ventanas de PVC",
  "Carpintero de ventanas de aluminio",
  "Carpintero de rejas de madera",
  "Carpintero de portones",
  "Carpintero de decks de jardín",
  "Carpintero de pérgolas",
  "Carpintero de quinchos",
  "Carpintero de gazebos",
  "Carpintero de techos de madera",
  "Carpintero de cielorrasos",
  "Carpintero de molduras",
  "Carpintero de marcos de puertas",
  "Carpintero de marcos de ventanas",
  "Carpintero de barandas",
  "Carpintero de escaleras de madera",
  "Carpintero de barandas de escaleras",
  "Carpintero de pisos flotantes",
  "Carpintero de tarimas",
  "Carpintero de revestimientos de pared",
  "Carpintero de revestimientos de techo",
  "Carpintero de muebles de cocina",
  "Carpintero de muebles de baño",
  "Carpintero de muebles de living",
  "Carpintero de muebles de dormitorio",
  "Carpintero de muebles de comedor",
  "Carpintero de muebles de jardín",
  "Carpintero de muebles para balcón",
  "Carpintero de muebles de terraza",
  "Carpintero de bancos de exterior",
  "Carpintero de sillas de exterior",
  "Carpintero de mesas de exterior",
  "Carpintero de pérgolas de madera",
  "Carpintero de decks de terraza",
  "Carpintero de muebles para bar",
  "Carpintero de muebles para cafetería",
];
