// src/lib/keywords/celulares.ts
export const CELULARES_KEYWORDS = [
  "arreglo de celulares",
  "reparación de celulares",
  "service técnico",
  "mantenimiento",
  "diagnóstico",
  "reparación express",
  "cambio de pantalla",
  "cambio de módulo",
  "cambio de vidrio",
  "cambio de táctil",
  "cambio de batería",
  "problemas de carga",
  "cambio de pin de carga",
  "reparación de micrófono",
  "reparación de parlante",
  "reparación de auricular",
  "problemas de señal",
  "sin servicio",
  "problemas de WiFi",
  "problemas de Bluetooth",
  "no enciende",
  "se apaga",
  "pantalla en negro",
  "equipo mojado",
  "limpieza por humedad",
  "actualización de software",
  "reinstalación de sistema",
  "liberación",
  "desbloqueo",
  "recuperación de datos",
  "reparación de cámaras",
  "cambio de tapa",
  "cambio de botones",
];
