// src/lib/keywords/cerrajeria.ts
export const CERRAJERIA_KEYWORDS = [
  "abrir puerta",
  "abrir puerta trabada",
  "abrir puerta cerrada",
  "abrir puerta sin llave",
  "abrir puerta blindada",
  "abrir puerta acorazada",
  "abrir puerta chapa",
  "abrir puerta antigua",
  "abrir puerta de garage",
  "abrir cerradura",
  "abrir cerradura sin llave",
  "abrir cerradura atascada",
  "abrir cerradura de seguridad",
  "abrir cerradura de puerta",
  "abrir cerradura blindada",
  "abrir cerradura electrónica",
  "abrir cerradura digital",
  "abrir caja fuerte",
  "abrir caja fuerte vieja",
  "abrir caja fuerte con llave",
  "abrir caja fuerte combinacion",
  "abrir cajon",
  "abrir candado",
  "abrir candado sin llave",
  "abrir reja",
  "abrir porton",
  "abrir porton sin llave",
  "abrir porton electrico",
  "abrir porton automatico",
  "abrir persiana metalica",
  "cambiar cerradura",
  "cambiar cerradura puerta",
  "cambiar cerradura blindada",
  "cambiar cerradura antigua",
  "cambiar cerradura digital",
  "cambiar cerradura de seguridad",
  "cambiar cilindro",
  "cambiar bombin",
  "cambiar bombin puerta",
  "cambiar bombin blindado",
  "cambiar bombin cilindro",
  "cambiar bombin cerradura",
  "cambiar llave",
  "cambiar llave perdida",
  "cambiar llave antigua",
  "cambiar llave puerta",
  "duplicar llave",
  "hacer duplicado de llave",
  "hacer copia de llave",
  "hacer llave copia",
  "hacer llave reserva",
  "cortar llave",
  "cortar llave de seguridad",
  "cortar llave antigua",
  "cortar llave puerta",
  "abrir puerta auto",
  "abrir auto cerrado",
  "abrir auto sin llave",
  "abrir auto chapa",
  "abrir baul",
  "abrir baul auto",
  "abrir baul cerrado",
  "abrir puerta con ganzua",
  "abrir cerradura con ganzua",
  "abrir cerradura complicada",
  "abrir cerradura de baño",
  "abrir cerradura de dormitorio",
  "abrir cerradura de cocina",
  "abrir cerradura de oficina",
  "cambiar cerradura de baño",
  "cambiar cerradura de dormitorio",
  "cambiar cerradura de cocina",
  "cambiar cerradura de oficina",
  "cambiar cerradura de puerta metalica",
  "cambiar cerradura de puerta madera",
  "cambiar cerradura de puerta vidrio",
  "cambiar cerradura embutida",
  "cambiar cerradura multipunto",
  "cambiar cerradura pomo",
  "cambiar cerradura pomo puerta",
  "cambiar cerradura pomo metal",
  "instalar cerradura",
  "instalar cerradura nueva",
  "instalar cerradura blindada",
  "instalar cerradura digital",
  "instalar cerradura electronica",
  "instalar cerradura puerta",
  "instalar cerradura puerta metalica",
  "instalar cerradura puerta madera",
  "instalar cerradura multipunto",
  "instalar cerradura pomo",
  "instalar cerradura embutida",
  "instalar cerradura de seguridad",
  "instalar cerradura moderna",
  "instalar cerradura antigua",
  "cambiar bombin puerta",
  "cambiar bombin seguridad",
  "cambiar bombin blindado",
  "cambiar bombin puerta metalica",
  "cambiar bombin puerta madera",
  "cambiar bombin puerta vidrio",
  "arreglar cerradura",
  "arreglar cerradura atascada",
  "arreglar cerradura rota",
  "arreglar cerradura de puerta",
  "arreglar cerradura antigua",
  "arreglar cerradura digital",
  "arreglar cerradura blindada",
  "arreglar cerradura de seguridad",
  "arreglar puerta",
  "arreglar puerta trabada",
  "arreglar puerta que no cierra",
  "arreglar puerta que no abre",
  "arreglar puerta metalica",
  "arreglar puerta madera",
  "arreglar puerta blindada",
  "arreglar puerta chapa",
  "arreglar puerta vieja",
  "arreglar porton",
  "arreglar porton metalico",
  "arreglar porton automatico",
  "arreglar porton electrico",
  "reparar cerradura",
  "reparar cerradura vieja",
  "reparar cerradura digital",
  "reparar cerradura blindada",
  "reparar cerradura multipunto",
  "reparar cerradura de seguridad",
  "reparar bombin",
  "reparar bombin puerta",
  "reparar bombin blindado",
  "reparar bombin antigua",
  "reparar llave",
  "reparar llave rota",
  "reparar llave vieja",
  "reparar llave de seguridad",
  "abrir persiana",
  "abrir persiana metalica",
  "abrir persiana enrollable",
  "abrir persiana chapa",
  "abrir reja metalica",
  "abrir reja puerta",
  "abrir reja de seguridad",
  "abrir porton corredizo",
  "abrir porton levadizo",
  "abrir porton manual",
  "abrir porton chapa",
  "cambiar manija",
  "cambiar pomo",
  "cambiar picaporte",
  "cambiar picaporte puerta",
  "cambiar picaporte metalico",
  "cambiar picaporte madera",
  "instalar picaporte",
  "instalar pomo",
  "instalar manija",
  "instalar manija puerta",
  "instalar manija metalica",
  "instalar manija madera",
  "duplicar llave auto",
  "duplicar llave codificada",
  "duplicar llave magnética",
  "duplicar llave de seguridad",
  "hacer llave codificada",
  "hacer llave magnética",
  "abrir caja fuerte",
  "abrir caja fuerte digital",
  "abrir caja fuerte electronica",
  "abrir caja fuerte combinacion",
  "abrir caja fuerte antigua",
  "abrir caja fuerte mecánica",
  "abrir caja fuerte pequeña",
  "abrir caja fuerte grande",
  "abrir cajon con llave",
  "abrir cajon atascado",
  "abrir cajon cerrado",
  "abrir candado viejo",
  "abrir candado combinacion",
  "abrir candado sin llave",
  "abrir candado chapa",
  "abrir candado seguridad",
  "abrir candado puerta",
  "instalar cerradura caja fuerte",
  "instalar cerradura porton",
  "instalar cerradura reja",
  "instalar cerradura persiana",
  "instalar cerradura metalica",
  "instalar cerradura madera",
  "instalar cerradura blindada",
  "abrir puerta de chapa",
  "abrir puerta de madera",
  "abrir puerta con picaporte",
  "abrir puerta con pomo",
  "abrir puerta sin manija",
  "abrir puerta sin picaporte",
  "cambiar cilindro puerta",
  "cambiar cilindro cerradura",
  "cambiar cilindro bombin",
  "cambiar cilindro seguridad",
  "cambiar cilindro blindado",
  "reparar cilindro puerta",
  "reparar cilindro bombin",
  "reparar cilindro cerradura",
  "reparar cilindro seguridad",
  "hacer llave bomba",
  "hacer llave cilindro",
  "hacer llave seguridad",
  "hacer llave antigua",
  "hacer llave moderna",
  "abrir puerta de oficina",
  "abrir puerta de departamento",
  "abrir puerta de local",
  "abrir puerta de comercio",
  "abrir puerta de negocio",
  "abrir puerta de casa",
  "abrir puerta de garage",
  "abrir puerta de taller",
  "abrir puerta de consultorio",
  "abrir puerta de edificio",
  "abrir cerradura multipunto",
  "abrir cerradura antigua",
  "abrir cerradura moderna",
  "abrir cerradura digital",
  "abrir cerradura electronica",
  "abrir cerradura embutida",
  "abrir cerradura de alta seguridad",
  "abrir cerradura complicada",
  "abrir cerradura difícil",
  "abrir cerradura de oficina",
  "abrir cerradura de negocio",
  "abrir cerradura de casa",
  "abrir cerradura de local",
  "abrir cerradura de taller",
  "abrir cerradura de garage",
  "abrir cerradura con ganzua",
  "abrir cerradura con destornillador",
  "abrir cerradura con lima",
  "abrir cerradura con herramienta",
  "abrir cerradura con metodo rapido",
  "abrir cerradura sin romper",
  "abrir cerradura sin dañar",
  "abrir cerradura sin llave original",
  "abrir cerradura con copia",
  "abrir cerradura perdida",
  "abrir cerradura rota",
  "abrir cerradura vieja",
  "abrir cerradura nueva",
  "abrir cerradura automatica",
  "abrir cerradura mecanica",
  "abrir cerradura metalica",
  "abrir cerradura de madera",
  "abrir cerradura de vidrio",
  "abrir cerradura de porton",
  "abrir cerradura de reja",
  "abrir cerradura de persiana",
  "abrir cerradura de caja fuerte",
  "abrir cerradura de candado",
  "abrir cerradura de pomos",
  "abrir cerradura de manijas",
  "abrir cerradura complicada",
  "abrir cerradura multipunto",
  "abrir cerradura de seguridad",
  "abrir cerradura de alta seguridad",
  "abrir cerradura codificada",
  "abrir cerradura electronica",
  "abrir cerradura magnetica",
  "abrir cerradura digital",
  "abrir cerradura moderna",
  "abrir cerradura antigua",
  "abrir cerradura blindada",
  "abrir cerradura de lujo",
  "abrir cerradura de diseño",
  "abrir cerradura de oficina",
  "abrir cerradura de comercio",
  "abrir cerradura de negocio",
  "abrir cerradura de hogar",
  "abrir cerradura de edificio",
  "abrir cerradura de departamento",
  "abrir cerradura de casa",
  "abrir cerradura de local",
  "abrir cerradura de taller",
  "abrir cerradura de garage",
  "abrir cerradura de consultorio",
  "abrir cerradura de habitacion",
  "abrir cerradura de dormitorio",
  "abrir cerradura de cocina",
  "abrir cerradura de baño",
  "abrir cerradura de puerta principal",
  "abrir cerradura de puerta trasera",
  "abrir cerradura de patio",
  "abrir cerradura de balcon",
  "abrir cerradura de terraza",
  "abrir cerradura de sotano",
  "abrir cerradura de altillo",
  "abrir cerradura de habitacion secundaria",
  "abrir cerradura de sala",
  "abrir cerradura de comedor",
  "abrir cerradura de vestidor",
  "abrir cerradura de deposito"
];
