// src/lib/keywords/clases.ts
export const CLASES_KEYWORDS = [
  "Clases de fútbol",
  "Entrenamiento de fútbol",
  "Clases de básquet",
  "Entrenamiento de básquet",
  "Clases de vóley",
  "Entrenamiento de vóley",
  "Clases de tenis",
  "Entrenamiento de tenis",
  "Clases de paddle",
  "Entrenamiento de paddle",
  "Clases de natación",
  "Entrenamiento de natación",
  "Clases de hockey",
  "Entrenamiento de hockey",
  "Clases de rugby",
  "Entrenamiento de rugby",
  "Clases de atletismo",
  "Entrenamiento de atletismo",
  "Clases de boxeo",
  "Entrenamiento de boxeo",
  "Clases de artes marciales",
  "Entrenamiento de artes marciales",
  "Clases de judo",
  "Entrenamiento de judo",
  "Clases de taekwondo",
  "Entrenamiento de taekwondo",
  "Clases de karate",
  "Entrenamiento de karate",
  "Clases de kickboxing",
  "Entrenamiento de kickboxing",
  "Clases de pilates",
  "Entrenamiento de pilates",
  "Clases de yoga",
  "Entrenamiento de yoga",
  "Clases de zumba",
  "Entrenamiento de zumba",
  "Clases de spinning",
  "Entrenamiento de spinning",
  "Clases de crossfit",
  "Entrenamiento de crossfit",
  "Clases de musculación",
  "Entrenamiento de musculación",
  "Clases de entrenamiento funcional",
  "Entrenamiento funcional",
  "Clases de baile",
  "Clases de tango",
  "Clases de salsa",
  "Clases de bachata",
  "Clases de hip hop",
  "Clases de reggaetón",
  "Clases de danza contemporánea",
  "Clases de ballet",
  "Clases de danza clásica",
  "Clases de flamenco",
  "Clases de jazz",
  "Clases de folklore",
  "Clases de ritmos latinos",
  "Clases de percusión",
  "Clases de guitarra",
  "Clases de piano",
  "Clases de batería",
  "Clases de violín",
  "Clases de canto",
  "Clases de canto moderno",
  "Clases de canto lírico",
  "Clases de música",
  "Clases de teatro",
  "Clases de actuación",
  "Clases de expresión corporal",
  "Clases de improvisación",
  "Clases de clown",
  "Clases de magia",
  "Clases de manualidades",
  "Taller de manualidades",
  "Taller de dibujo",
  "Clases de pintura",
  "Clases de acuarela",
  "Clases de óleo",
  "Clases de pastel",
  "Clases de dibujo digital",
  "Clases de fotografía",
  "Clases de edición de fotos",
  "Clases de edición de video",
  "Clases de informática",
  "Clases de computación",
  "Clases de programación",
  "Clases de robótica",
  "Clases de idiomas",
  "Clases de inglés",
  "Clases de portugués",
  "Clases de francés",
  "Clases de alemán",
  "Clases de italiano",
  "Clases de chino",
  "Clases de japonés",
  "Clases de ruso",
  "Clases de árabe",
  "Clases de apoyo escolar",
  "Clases de matemáticas",
  "Clases de física",
  "Clases de química",
  "Clases de biología",
  "Clases de historia",
  "Clases de geografía",
  "Clases de literatura",
  "Clases de lengua",
  "Clases de filosofía",
  "Clases de ciencias sociales",
  "Clases de educación cívica",
  "Clases de economía",
  "Clases de contabilidad",
  "Clases de administración",
  "Clases de derecho",
  "Clases de preparación universitaria",
  "Clases de ingreso a facultad",
  "Clases de preparación secundaria",
  "Clases de apoyo primario",
  "Clases de refuerzo escolar",
  "Clases de técnicas de estudio",
  "Clases de orientación vocacional",
  "Clases de escritura",
  "Clases de redacción",
  "Clases de poesía",
  "Clases de narrativa",
  "Clases de cine",
  "Clases de guion",
  "Clases de dirección teatral",
  "Clases de actuación para cine",
  "Clases de maquillaje artístico",
  "Clases de maquillaje profesional",
  "Clases de peluquería",
  "Clases de estilismo",
  "Clases de estética",
  "Clases de cuidado personal",
  "Clases de manicura",
  "Clases de pedicura",
  "Clases de depilación",
  "Clases de barbería",
  "Clases de cosmetología",
  "Clases de masaje",
  "Clases de masoterapia",
  "Clases de reflexología",
  "Clases de reiki",
  "Clases de meditación",
  "Clases de mindfulness",
  "Clases de desarrollo personal",
  "Clases de coaching",
  "Clases de liderazgo",
  "Clases de motivación",
  "Clases de oratoria",
  "Clases de comunicación",
  "Clases de negociación",
  "Clases de venta",
  "Clases de marketing",
  "Clases de social media",
  "Clases de community manager",
  "Clases de diseño gráfico",
  "Clases de Photoshop",
  "Clases de Illustrator",
  "Clases de After Effects",
  "Clases de Premiere",
  "Clases de Final Cut",
  "Clases de animación",
  "Clases de 3D",
  "Clases de Blender",
  "Clases de AutoCAD",
  "Clases de SketchUp",
  "Clases de arquitectura",
  "Clases de diseño de interiores",
  "Clases de decoración",
  "Clases de jardinería",
  "Clases de huerta",
  "Clases de cocina",
  "Clases de repostería",
  "Clases de panadería",
  "Clases de pastelería",
  "Clases de sushi",
  "Clases de parrilla",
  "Clases de asado",
  "Clases de gastronomía",
  "Clases de café",
  "Clases de coctelería",
  "Clases de barista",
  "Clases de vinos",
  "Clases de sommelería",
  "Clases de cerveza artesanal",
  "Clases de yoga",
  "Clases de pilates",
  "Clases de meditación",
  "Clases de stretching",
  "Clases de funcional",
  "Clases de crossfit",
  "Clases de gym",
  "Clases de musculación",
  "Clases de cardio",
  "Clases de aeróbica",
  "Clases de danza",
  "Clases de tango",
  "Clases de folklore",
  "Clases de salsa",
  "Clases de bachata",
  "Clases de hip hop",
  "Clases de reggaetón",
  "Clases de break dance",
  "Clases de danza urbana",
  "Clases de ballet",
  "Clases de danza clásica",
  "Clases de flamenco",
  "Clases de jazz",
  "Clases de danza contemporánea",
  "Clases de circo",
  "Clases de acrobacia",
  "Clases de malabares",
  "Clases de trapecio",
  "Clases de payasos",
  "Clases de teatro",
  "Clases de improvisación",
  "Clases de actuación",
  "Clases de expresión corporal",
  "Clases de canto",
  "Clases de guitarra",
  "Clases de piano",
  "Clases de batería",
  "Clases de violín",
  "Clases de canto moderno",
  "Clases de canto lírico",
  "Clases de música",
  "Clases de producción musical",
  "Clases de DJ",
  "Clases de música electrónica",
  "Clases de beatmaking",
  "Clases de producción de audio",
  "Clases de sonido",
  "Clases de ingeniería de sonido",
  "Clases de fotografía",
  "Clases de video",
  "Clases de edición de video",
  "Clases de filmación",
  "Clases de cine",
  "Clases de guion",
  "Clases de dirección",
  "Clases de producción",
  "Clases de locución",
  "Clases de radio",
  "Clases de podcast",
  "Clases de storytelling",
  "Clases de escritura creativa",
  "Clases de literatura",
  "Clases de poesía",
  "Clases de narrativa",
  "Clases de narrativa infantil",
  "Clases de cuento",
  "Clases de novela",
  "Clases de ensayo",
  "Clases de escritura profesional",
  "Clases de comunicación",
  "Clases de marketing",
  "Clases de publicidad",
  "Clases de diseño",
  "Clases de ilustración",
  "Clases de dibujo",
  "Clases de pintura",
  "Clases de acuarela",
  "Clases de óleo",
  "Clases de pastel",
  "Clases de mural",
  "Clases de graffiti",
  "Clases de escultura",
  "Clases de cerámica",
  "Clases de barro",
  "Clases de porcelana fría",
  "Clases de reciclaje creativo",
  "Clases de origami",
  "Clases de tejido",
  "Clases de crochet",
  "Clases de bordado",
  "Clases de macramé",
  "Clases de patchwork",
  "Clases de costura",
  "Clases de confección",
  "Clases de moda",
  "Clases de diseño de indumentaria",
  "Clases de patronaje",
  "Clases de estilismo",
  "Clases de maquillaje",
  "Clases de barbería",
  "Clases de estética",
  "Clases de masajes",
  "Clases de reiki",
  "Clases de meditación",
  "Clases de mindfulness",
  "Clases de desarrollo personal",
  "Clases de coaching",
  "Clases de liderazgo",
  "Clases de motivación",
  "Clases de oratoria",
  "Clases de comunicación efectiva",
  "Clases de negociación",
  "Clases de ventas",
  "Clases de emprendimiento"
];
