// src/lib/keywords/control-de-plagas.ts
export const CONTROL_DE_PLAGAS_KEYWORDS = [
  "fumigación",
  "fumigación hogar",
  "fumigación empresa",
  "fumigación comercio",
  "fumigación depto",
  "fumigación oficina",
  "fumigar cucarachas",
  "fumigar ratas",
  "fumigar ratones",
  "fumigar hormigas",
  "fumigar mosquitos",
  "fumigar arañas",
  "fumigar pulgas",
  "fumigar chinches",
  "fumigar alacranes",
  "fumigar vinchucas",
  "fumigar avispones",
  "fumigar moscas",
  "fumigar palomas",
  "fumigar aves",
  "fumigar insectos",
  "control de plagas",
  "control de plagas hogar",
  "control de plagas empresa",
  "control de plagas comercio",
  "control de ratas",
  "control de ratones",
  "control de cucarachas",
  "control de hormigas",
  "control de mosquitos",
  "control de arañas",
  "control de chinches",
  "control de pulgas",
  "control de alacranes",
  "control de vinchucas",
  "control de avispones",
  "control de moscas",
  "desratización",
  "desratización hogar",
  "desratización comercio",
  "desratización empresa",
  "desinsectación",
  "desinsectación hogar",
  "desinsectación comercio",
  "desinsectación empresa",
  "limpieza de nidos de avispa",
  "limpieza de nidos de abeja",
  "eliminar ratas",
  "eliminar ratones",
  "eliminar cucarachas",
  "eliminar hormigas",
  "eliminar mosquitos",
  "eliminar arañas",
  "eliminar chinches",
  "eliminar pulgas",
  "eliminar alacranes",
  "eliminar vinchucas",
  "eliminar avispones",
  "eliminar moscas",
  "control de insectos",
  "control de roedores",
  "control de aves",
  "plagas urgentes",
  "plagas en casa",
  "plagas en depto",
  "plagas en oficina",
  "plagas en comercio",
  "plagas en empresa",
  "fumigación barata",
  "fumigación profesional",
  "fumigación urgente",
  "fumigación a domicilio",
  "control de plagas urgente",
  "control de plagas profesional",
  "control de plagas a domicilio",
  "control de plagas económico",
  "desratización urgente",
  "desratización profesional",
  "desinsectación urgente",
  "desinsectación profesional",
  "fumigar hogar",
  "fumigar negocio",
  "fumigar comercio",
  "fumigar oficina",
  "fumigar depto",
  "fumigar vivienda",
  "fumigar industria",
  "fumigar local",
  "fumigar patio",
  "fumigar terraza",
  "fumigar balcón",
  "fumigar jardín",
  "fumigar cocina",
  "fumigar baño",
  "fumigar sótano",
  "fumigar garaje",
  "fumigar muebles",
  "fumigar colchón",
  "fumigar alfombra",
  "fumigar cortinas",
];
