// src/lib/keywords/cuidado-de-personas.ts
export const CUIDADO_DE_PERSONAS_KEYWORDS = [
  "cuidado de personas",
  "cuidado de adultos mayores",
  "asistencia a domicilio",
  "acompañamiento de adultos",
  "cuidado en casa",
  "alguien que acompañe a los abuelos",
  "compañía para personas mayores",
  "ayuda a los mayores",
  "cuidado de ancianos",
  "enfermería a domicilio",
  "asistencia para viejos",
  "cuidado diario de abuelos",
  "acompañamiento en casa",
  "cuidador de adultos mayores",
  "enfermero a domicilio",
  "acompañante para mayores",
  "ayuda en casa para adultos",
  "cuidado de pacientes en casa",
  "asistencia personal",
  "cuidado de personas dependientes",
  "niñera",
  "niñera de día",
  "niñera de noche",
  "cuidado de niños",
  "cuidado de bebés",
  "babysitter",
  "niñera de confianza",
  "niñera para bebés",
  "cuidado de chicos",
  "cuidado infantil",
  "acompañamiento de niños",
  "niñera a domicilio",
  "cuidado de niños en casa",
  "ayuda con los niños",
  "niñera flexible",
  "cuidado nocturno de niños",
  "niñera por horas",
  "niñera para bebés recién nacidos",
  "niñera full time",
  "niñera part time",
  "cuidado de enfermos",
  "enfermería a domicilio",
  "enfermero particular",
  "asistencia a enfermos",
  "acompañamiento de pacientes",
  "cuidado de personas con discapacidad",
  "cuidado postoperatorio",
  "ayuda en casa para enfermos",
  "cuidador de pacientes",
  "enfermería domiciliaria",
  "asistencia a personas dependientes",
  "enfermería particular",
  "cuidado de personas con movilidad reducida",
  "asistencia a enfermos crónicos",
  "acompañante sanitario",
  "cuidado en casa de enfermos",
  "enfermero para adultos mayores",
  "ayuda para personas con enfermedad",
  "cuidado de personas con Alzheimer",
  "acompañamiento en hospital a domicilio",
  "alguien que cuide a los viejos",
  "niñera para tus pibes",
  "ayuda a los abuelos",
  "cuidado de los viejos",
  "alguien que cuide a los chicos",
  "niñera copada",
  "cuidador piola",
  "compañía para los abuelos",
  "alguien que acompañe a tus viejos",
  "cuidado de chicos en casa",
  "niñera y cuidado de adultos mayores",
  "cuidado integral en casa",
  "asistencia a niños y mayores",
  "compañía y cuidado en casa",
  "cuidado de bebés y abuelos",
  "niñera + enfermería a domicilio",
  "cuidado de personas mayores y enfermos",
  "asistencia completa a domicilio",
  "acompañamiento y cuidado personal",
  "cuidado de niños y adultos dependientes"
];
