// src/lib/keywords/diseno-remodelaciones.ts
export const DISENO_REMODELACIONES_KEYWORDS = [
  "diseño de interiores",
  "diseño de ambientes",
  "renovación del hogar",
  "remodelación de interiores",
  "refacción de casas",
  "cambio de pisos",
  "colocación de pisos flotantes",
  "colocación de pisos vinílicos",
  "colocación de pisos cerámicos",
  "colocación de porcelanatos",
  "colocación de pisos símil madera",
  "colocación de pisos SPC",
  "pisos modernos para casa",
  "renovación de cocinas",
  "renovación de baños",
  "rediseño de espacios",
  "diseño de livings",
  "diseño de dormitorios",
  "decoración moderna",
  "ambientación de hogares",
  "diseño minimalista",
  "diseño rústico moderno",
  "interiorismo contemporáneo",
  "cambio de estilo en casa",
  "mejoras en el hogar",
  "renovación de departamentos",
  "modernización de interiores",
  "actualización de ambientes",
  "diseño de espacios pequeños",
  "asesoramiento en diseño interior",
];
