// src/lib/keywords/electricista.ts
export const ELECTRICISTA_KEYWORDS = [
	"Electricista a domicilio",
	"Instalación de enchufes",
	"Arreglo de cortocircuitos",
	"Reparación de cables",
	"Instalación de lámparas",
	"Instalación de luces LED",
	"Reparación de tablero eléctrico",
	"Mantenimiento eléctrico",
	"Instalación de ventiladores de techo",
	"Reparación de ventiladores",
	"Electricista de urgencia",
	"Cambio de disyuntores",
	"Cambio de termotanque",
	"Instalación de termotanque eléctrico",
	"Reparación de termotanque",
	"Instalación de calefones",
	"Reparación de calefones",
	"Instalación de lámparas de emergencia",
	"Reparación de lámparas de emergencia",
	"Electricista industrial",
	"Instalación de tableros eléctricos",
	"Instalación de circuitos",
	"Reparación de cortinas eléctricas",
	"Instalación de portones eléctricos",
	"Reparación de portones eléctricos",
	"Instalación de automatización",
	"Instalación de cámaras de seguridad",
	"Reparación de cámaras de seguridad",
	"Instalación de timbres eléctricos",
	"Reparación de timbres eléctricos",
	"Instalación de citófonos",
	"Reparación de citófonos",
	"Instalación de apliques",
	"Reparación de apliques",
	"Electricista para comercio",
	"Electricista para oficina",
	"Arreglo de cables pelados",
	"Cambio de tomas",
	"Cambio de enchufes",
	"Instalación de tomas adicionales",
	"Instalación de interruptores",
	"Reparación de interruptores",
	"Instalación de sensores de movimiento",
	"Reparación de sensores",
	"Instalación de porteros eléctricos",
	"Reparación de porteros eléctricos",
	"Instalación de reflectores",
	"Reparación de reflectores",
	"Electricista matriculado",
	"Electricista certificado",
	"Instalación de luminarias",
	"Reparación de luminarias",
	"Instalación de tubos fluorescentes",
	"Reparación de tubos fluorescentes",
	"Instalación de focos halógenos",
	"Reparación de focos halógenos",
	"Instalación de luces exteriores",
	"Reparación de luces exteriores",
	"Instalación de luces interiores",
	"Reparación de luces interiores",
	"Arreglo de cortocircuitos en casa",
	"Arreglo de cortocircuitos en comercio",
	"Instalación de enchufes múltiples",
	"Instalación de regletas",
	"Electricista residencial",
	"Electricista para departamentos",
	"Electricista para casas",
	"Instalación de cableado nuevo",
	"Reparación de cableado viejo",
	"Mantenimiento de instalaciones eléctricas",
	"Revisión de instalaciones eléctricas",
	"Instalación de disyuntores",
	"Reparación de disyuntores",
	"Instalación de breakers",
	"Reparación de breakers",
	"Instalación de tablero general",
	"Reparación de tablero general",
	"Instalación de luces de emergencia",
	"Reparación de luces de emergencia",
	"Instalación de alarmas",
	"Reparación de alarmas",
	"Instalación de detectores de humo",
	"Reparación de detectores de humo",
	"Instalación de luces de jardín",
	"Reparación de luces de jardín",
	"Instalación de cables subterráneos",
	"Reparación de cables subterráneos",
	"Instalación de cables aéreos",
	"Reparación de cables aéreos",
	"Instalación de enchufes especiales",
	"Reparación de enchufes especiales",
	"Instalación de tomas de corriente",
	"Reparación de tomas de corriente",
	"Instalación de cableado para electrodomésticos",
	"Reparación de cableado de electrodomésticos",
	"Instalación de luces inteligentes",
	"Reparación de luces inteligentes",
	"Instalación de ventiladores de pared",
	"Reparación de ventiladores de pared",
	"Instalación de luces empotradas",
	"Reparación de luces empotradas",
	"Instalación de apliques de pared",
	"Reparación de apliques de pared",
	"Instalación de luces de techo",
	"Reparación de luces de techo",
	"Instalación de luces de pasillo",
	"Reparación de luces de pasillo",
	"Instalación de luces de cocina",
	"Reparación de luces de cocina",
	"Instalación de luces de baño",
	"Reparación de luces de baño",
	"Instalación de luces de living",
	"Reparación de luces de living",
	"Instalación de luces de dormitorio",
	"Reparación de luces de dormitorio",
	"Instalación de cableado para PC",
	"Reparación de cableado para PC",
	"Instalación de cableado de red",
	"Reparación de cableado de red",
	"Instalación de internet",
	"Reparación de internet",
	"Instalación de luces de seguridad",
	"Reparación de luces de seguridad",
	"Instalación de cortinas eléctricas",
	"Reparación de cortinas eléctricas",
	"Instalación de sistemas de seguridad",
	"Reparación de sistemas de seguridad",
	"Instalación de cámaras CCTV",
	"Reparación de cámaras CCTV",
	"Instalación de luces inteligentes",
	"Reparación de luces inteligentes",
	"Instalación de tableros eléctricos",
	"Reparación de tableros eléctricos",
	"Instalación de cableado interno",
	"Reparación de cableado interno",
	"Instalación de luces de emergencia",
	"Reparación de luces de emergencia",
	"Instalación de sensores de presencia",
	"Reparación de sensores de presencia",
	"Instalación de portones eléctricos",
	"Reparación de portones eléctricos",
	"Instalación de porteros eléctricos",
	"Reparación de porteros eléctricos",
	"Instalación de timbres",
	"Reparación de timbres",
	"Instalación de reflectores de jardín",
	"Reparación de reflectores de jardín",
	"Instalación de iluminación interior",
	"Reparación de iluminación interior",
	"Instalación de iluminación exterior",
	"Reparación de iluminación exterior",
	"Instalación de cableado de red",
	"Reparación de cableado de red",
	"Instalación de enchufes",
	"Reparación de enchufes",
	"Instalación de interruptores",
	"Reparación de interruptores",
	"Instalación de breakers",
	"Reparación de breakers",
	"Instalación de disyuntores",
	"Reparación de disyuntores",
	"Instalación de luces de emergencia",
	"Reparación de luces de emergencia",
	"Instalación de luces LED",
	"Reparación de luces LED",
	"Instalación de luces RGB",
	"Reparación de luces RGB",
	"Instalación de iluminación interior",
	"Reparación de iluminación interior",
	"Instalación de iluminación exterior",
	"Reparación de iluminación exterior",
	"Instalación de ventiladores de pared",
	"Reparación de ventiladores de pared",
	"Instalación de luces de cocina",
	"Reparación de luces de cocina",
	"Instalación de luces de baño",
	"Reparación de luces de baño",
	"Instalación de luces de living",
	"Reparación de luces de living",
	"Instalación de luces de dormitorio",
	"Reparación de luces de dormitorio",
	"Instalación de luces de pasillo",
	"Reparación de luces de pasillo",
	"Instalación de cableado para PC",
	"Reparación de cableado para PC",
	"Instalación de cableado de red",
	"Reparación de cableado de red",
	"Instalación de internet",
	"Reparación de internet",
	"Instalación de luces de seguridad",
	"Reparación de luces de seguridad",
	"Instalación de tableros",
	"Reparación de tableros",
	"Instalación de interruptores",
	"Reparación de interruptores",
	"Instalación de breakers",
	"Reparación de breakers",
	"Instalación de disyuntores",
	"Reparación de disyuntores",
	"Instalación de luces de emergencia",
	"Reparación de luces de emergencia",
	"Instalación de luces inteligentes",
	"Reparación de luces inteligentes",
	"Instalación de porteros eléctricos",
	"Reparación de porteros eléctricos",
	"Instalación de timbres",
	"Reparación de timbres",
	"Instalación de cámaras CCTV",
	"Reparación de cámaras CCTV",
	"Instalación de sensores",
	"Reparación de sensores",
	"Instalación de sistemas de seguridad",
];
