// src/lib/keywords/entrenadores.ts
export const ENTRENADORES_KEYWORDS = [
  'Entrenador personal',
  'Entrenador físico',
  'Preparador físico',
  'Coach deportivo',
  'Entrenador de fútbol',
  'Entrenamiento de fútbol',
  'Entrenador de básquet',
  'Entrenamiento de básquet',
  'Entrenador de vóley',
  'Entrenamiento de vóley',
  'Entrenador de tenis',
  'Entrenamiento de tenis',
  'Entrenador de paddle',
  'Entrenamiento de paddle',
  'Entrenador de natación',
  'Entrenamiento de natación',
  'Entrenador de hockey',
  'Entrenamiento de hockey',
  'Entrenador de rugby',
  'Entrenamiento de rugby',
  'Entrenador de atletismo',
  'Entrenamiento de atletismo',
  'Entrenador de boxeo',
  'Entrenamiento de boxeo',
  'Entrenador de artes marciales',
  'Entrenamiento de artes marciales',
  'Entrenador de judo',
  'Entrenamiento de judo',
  'Entrenador de taekwondo',
  'Entrenamiento de taekwondo',
  'Entrenador de karate',
  'Entrenamiento de karate',
  'Entrenador de kickboxing',
  'Entrenamiento de kickboxing',
  'Entrenador de pilates',
  'Entrenamiento de pilates',
  'Entrenador de yoga',
  'Entrenamiento de yoga',
  'Entrenador de zumba',
  'Entrenamiento de zumba',
  'Entrenador de spinning',
  'Entrenamiento de spinning',
  'Entrenador de crossfit',
  'Entrenamiento de crossfit',
  'Entrenador de musculación',
  'Entrenamiento de musculación',
  'Entrenador funcional',
  'Entrenamiento funcional',
  'Entrenador de gym',
  'Entrenamiento en gimnasio',
  'Entrenador de fitness',
  'Entrenamiento fitness',
  'Entrenador de fuerza',
  'Entrenamiento de fuerza',
  'Entrenador de resistencia',
  'Entrenamiento de resistencia',
  'Entrenador de cardio',
  'Entrenamiento de cardio',
  'Entrenador de baile',
  'Entrenamiento de baile',
  'Entrenador de tango',
  'Entrenamiento de tango',
  'Entrenador de salsa',
  'Entrenamiento de salsa',
  'Entrenador de bachata',
  'Entrenamiento de bachata',
  'Entrenador de hip hop',
  'Entrenamiento de hip hop',
  'Entrenador de reggaetón',
  'Entrenamiento de reggaetón',
  'Entrenador de danza contemporánea',
  'Entrenamiento de danza contemporánea',
  'Entrenador de ballet',
  'Entrenamiento de ballet',
  'Entrenador de danza clásica',
  'Entrenamiento de danza clásica',
  'Entrenador de flamenco',
  'Entrenamiento de flamenco',
  'Entrenador de jazz',
  'Entrenamiento de jazz',
  'Entrenador de folklore',
  'Entrenamiento de folklore',
  'Entrenador de ritmos latinos',
  'Entrenamiento de ritmos latinos',
  'Entrenador de percusión',
  'Entrenamiento de percusión',
  'Entrenador de guitarra',
  'Entrenamiento de guitarra',
  'Entrenador de piano',
  'Entrenamiento de piano',
  'Entrenador de batería',
  'Entrenamiento de batería',
  'Entrenador de violín',
  'Entrenamiento de violín',
  'Entrenador de canto',
  'Entrenamiento de canto',
  'Entrenador de canto moderno',
  'Entrenamiento de canto moderno',
  'Entrenador de canto lírico',
  'Entrenamiento de canto lírico',
  'Coach de running',
  'Entrenamiento de running',
  'Coach de triatlón',
  'Entrenamiento de triatlón',
  'Coach de ciclismo',
  'Entrenamiento de ciclismo',
  'Coach de trail running',
  'Entrenamiento de trail running',
  'Entrenador de escalada',
  'Entrenamiento de escalada',
  'Entrenador de surf',
  'Entrenamiento de surf',
  'Entrenador de skate',
  'Entrenamiento de skate',
  'Entrenador de parkour',
  'Entrenamiento de parkour',
  'Entrenador de deportes extremos',
  'Entrenamiento de deportes extremos',
  'Entrenador de snowboard',
  'Entrenamiento de snowboard',
  'Entrenador de esquí',
  'Entrenamiento de esquí',
  'Entrenador de remo',
  'Entrenamiento de remo',
  'Entrenador de kayak',
  'Entrenamiento de kayak',
  'Entrenador de surfskate',
  'Entrenamiento de surfskate',
  'Entrenador de natación sincronizada',
  'Entrenamiento de natación sincronizada',
  'Entrenador de waterpolo',
  'Entrenamiento de waterpolo',
  'Entrenador de vela',
  'Entrenamiento de vela',
  'Entrenador de pesca deportiva',
  'Entrenamiento de pesca deportiva',
  'Entrenador de golf',
  'Entrenamiento de golf',
  'Entrenador de tenis de mesa',
  'Entrenamiento de tenis de mesa',
  'Entrenador de billar',
  'Entrenamiento de billar',
  'Entrenador de ajedrez',
  'Entrenamiento de ajedrez',
  'Entrenador de e-sports',
  'Entrenamiento de e-sports',
  'Entrenador personal a domicilio',
  'Entrenamiento personalizado',
  'Entrenador online',
  'Entrenamiento online',
  'Coach de vida',
  'Entrenamiento de vida saludable',
  'Entrenador de hábitos',
  'Coaching de hábitos',
  'Entrenador de alimentación',
  'Coach nutricional',
  'Entrenador de dieta',
  'Plan nutricional',
  'Entrenador de pérdida de peso',
  'Entrenamiento de pérdida de peso',
  'Entrenador de ganancia de masa',
  'Entrenamiento de ganancia de masa',
  'Entrenador de hipertrofia',
  'Entrenamiento de hipertrofia',
  'Entrenador de fuerza máxima',
  'Entrenamiento de fuerza máxima',
  'Entrenador de resistencia aeróbica',
  'Entrenamiento de resistencia aeróbica',
  'Entrenador de resistencia anaeróbica',
  'Entrenamiento de resistencia anaeróbica',
  'Entrenador de flexibilidad',
  'Entrenamiento de flexibilidad',
  'Entrenador de movilidad',
  'Entrenamiento de movilidad',
  'Entrenador de coordinación',
  'Entrenamiento de coordinación',
  'Entrenador de agilidad',
  'Entrenamiento de agilidad',
  'Entrenador de equilibrio',
  'Entrenamiento de equilibrio',
  'Entrenador de velocidad',
  'Entrenamiento de velocidad',
  'Entrenador de potencia',
  'Entrenamiento de potencia',
  'Entrenador de salto',
  'Entrenamiento de salto',
  'Entrenador de reacción',
  'Entrenamiento de reacción',
  'Entrenador de habilidades deportivas',
  'Entrenamiento de habilidades deportivas',
  'Entrenador de técnica',
  'Entrenamiento técnico',
  'Entrenador táctico',
  'Entrenamiento táctico',
  'Entrenador de equipo',
  'Entrenamiento de equipo',
  'Entrenador de grupo',
  'Entrenamiento grupal',
  'Entrenador de mini grupos',
  'Entrenamiento funcional grupal',
  'Entrenador de bootcamp',
  'Entrenamiento de bootcamp',
  'Entrenador de outdoor',
  'Entrenamiento al aire libre',
  'Entrenador en parque',
  'Entrenamiento en parque',
  'Entrenador en plaza',
  'Entrenamiento en plaza',
  'Entrenador en gimnasio',
  'Entrenamiento en gimnasio',
  'Entrenador de calle',
  'Entrenamiento callejero',
  'Entrenador de rutina',
  'Plan de entrenamiento',
  'Entrenador de programa',
  'Programa de ejercicios',
  'Entrenador de stretching',
  'Entrenamiento de stretching',
  'Entrenador de calentamiento',
  'Entrenamiento de calentamiento',
  'Entrenador de enfriamiento',
  'Entrenamiento de enfriamiento',
  'Entrenador de core',
  'Entrenamiento de core',
  'Entrenador de abdominales',
  'Entrenamiento de abdominales',
  'Entrenador de espalda',
  'Entrenamiento de espalda',
  'Entrenador de piernas',
  'Entrenamiento de piernas',
  'Entrenador de brazos',
  'Entrenamiento de brazos',
  'Entrenador de pecho',
  'Entrenamiento de pecho',
  'Entrenador de hombros',
  'Entrenamiento de hombros',
  'Entrenador de glúteos',
  'Entrenamiento de glúteos',
  'Entrenador de cadera',
  'Entrenamiento de cadera',
  'Entrenador de coordinación motora',
  'Entrenamiento de coordinación motora',
  'Entrenador de equilibrio',
  'Entrenamiento de equilibrio',
  'Entrenador de resistencia mental',
  'Entrenamiento de resistencia mental',
  'Entrenador de motivación',
  'Coaching motivacional',
  'Entrenador de superación',
  'Entrenamiento de superación',
  'Entrenador de hábitos saludables',
  'Coaching de hábitos saludables',
  'Entrenador de bienestar',
  'Coaching de bienestar',
  'Entrenador de estilo de vida',
  'Coaching de estilo de vida',
  'Entrenador de desarrollo personal',
  'Coaching de desarrollo personal',
  'Entrenador de confianza',
  'Coaching de confianza',
  'Entrenador de liderazgo',
  'Coaching de liderazgo',
  'Entrenador de comunicación',
  'Coaching de comunicación',
  'Entrenador de trabajo en equipo',
  'Coaching de equipo',
  'Entrenador de rendimiento',
  'Coaching de rendimiento',
  'Entrenador de potenciación',
  'Coaching de potenciación',
  'Entrenador de mindfulness',
  'Entrenamiento mindfulness',
  'Entrenador de relajación',
  'Entrenamiento de relajación',
  'Entrenador de respiración',
  'Entrenamiento de respiración',
  'Entrenador de equilibrio emocional',
  'Entrenamiento emocional',
  'Entrenador de resiliencia',
  'Entrenamiento de resiliencia',
  'Entrenador de concentración',
  'Entrenamiento de concentración',
  'Entrenador de enfoque',
  'Entrenamiento de enfoque',
  'Entrenador de visualización',
  'Entrenamiento de visualización',
  'Entrenador de meditación activa',
  'Entrenamiento de meditación activa',
  'Entrenador de stretching funcional',
  'Entrenamiento de stretching funcional',
  'Entrenador de calentamiento funcional',
  'Entrenamiento de calentamiento funcional',
  'Entrenador de enfriamiento funcional',
  'Entrenamiento de enfriamiento funcional',
  'Entrenador de circuito',
  'Entrenamiento de circuito',
  'Entrenador de HIIT',
  'Entrenamiento HIIT',
  'Entrenador de intervalos',
  'Entrenamiento por intervalos',
];
