// src/lib/keywords/eventos.ts
export const EVENTOS_KEYWORDS = [
  "Alquiler de salón",
  "Alquiler de quincho",
  "Alquiler de casa para fiesta",
  "Alquiler de espacio para evento",
  "Salón para cumpleaños",
  "Salón para casamiento",
  "Salón para boda",
  "Salón para 15 años",
  "Salón para aniversario",
  "Casa para cumpleaños",
  "Casa para fiesta",
  "Casa para evento",
  "Quincho para cumpleaños",
  "Quincho para fiesta",
  "Quincho para evento",
  "Salón con pileta",
  "Salón con jardín",
  "Salón con patio",
  "Espacio al aire libre",
  "Alquiler de terraza",
  "Alquiler de parque",
  "Fiesta en parque",
  "Salón con parrilla",
  "Fiesta con asado",
  "Fiesta temática",
  "Fiesta infantil",
  "Fiesta de adolescentes",
  "Fiesta de adultos",
  "Fiesta de egresados",
  "Fiesta de fin de año",
  "Fiesta de Navidad",
  "Fiesta de Año Nuevo",
  "Fiesta de Halloween",
  "Fiesta de Carnaval",
  "Fiesta sorpresa",
  "Fiesta íntima",
  "Fiesta familiar",
  "Fiesta privada",
  "Fiesta al aire libre",
  "Fiesta con catering",
  "Servicio de catering",
  "Catering para cumpleaños",
  "Catering para casamiento",
  "Catering para boda",
  "Catering para 15 años",
  "Catering para aniversario",
  "Catering para eventos",
  "Catering de comida casera",
  "Catering de comida internacional",
  "Catering de buffet",
  "Catering de parrilla",
  "Catering con postres",
  "Catering con torta",
  "Catering con bebidas",
  "Barra de tragos",
  "Barra libre",
  "Cocktail para evento",
  "Coctelería",
  "Bartender para fiesta",
  "DJ para fiesta",
  "DJ para cumpleaños",
  "DJ para casamiento",
  "DJ para boda",
  "DJ para 15 años",
  "DJ para aniversario",
  "Animador para fiesta",
  "Animación infantil",
  "Animación de adultos",
  "Show en vivo",
  "Banda en vivo",
  "Música en vivo",
  "Grupo musical",
  "Orquesta",
  "Mago para fiesta",
  "Payaso para fiesta",
  "Personaje para fiesta",
  "Disfraz para animación",
  "Cotillón para fiesta",
  "Decoración para evento",
  "Decoración de cumpleaños",
  "Decoración de casamiento",
  "Decoración de boda",
  "Decoración de 15 años",
  "Decoración de aniversario",
  "Decoración temática",
  "Decoración con globos",
  "Arco de globos",
  "Centros de mesa",
  "Guirnaldas",
  "Cartelería para fiesta",
  "Photobooth",
  "Cabina de fotos",
  "Fotógrafo para evento",
  "Fotografía de cumpleaños",
  "Fotografía de casamiento",
  "Fotografía de boda",
  "Fotografía de 15 años",
  "Fotografía de aniversario",
  "Video para evento",
  "Video de cumpleaños",
  "Video de casamiento",
  "Video de boda",
  "Video de 15 años",
  "Video de aniversario",
  "Streaming de evento",
  "Transmisión en vivo",
  "Iluminación para evento",
  "Luces para fiesta",
  "Luces led",
  "Luces de colores",
  "Efectos de luz",
  "Proyector para evento",
  "Pantalla para evento",
  "Sonido para evento",
  "Equipo de sonido",
  "Micrófono para evento",
  "Parlantes para fiesta",
  "Alquiler de sillas",
  "Alquiler de mesas",
  "Alquiler de manteles",
  "Alquiler de vajilla",
  "Alquiler de cubiertos",
  "Alquiler de copas",
  "Alquiler de cristalería",
  "Alquiler de decoración",
  "Alquiler de pista de baile",
  "Pista de baile",
  "Pista iluminada",
  "Pista de LED",
  "Alquiler de inflables",
  "Inflables para niños",
  "Inflables para fiesta",
  "Tobogán inflable",
  "Castillos inflables",
  "Juegos inflables",
  "Alquiler de sillas altas",
  "Tronas para niños",
  "Juegos para niños",
  "Animación de payasos",
  "Personajes para fiesta",
  "Show de magia",
  "Talleres infantiles",
  "Talleres creativos",
  "Talleres de pintura",
  "Talleres de manualidades",
  "Talleres de cocina",
  "Talleres de baile",
  "Talleres de música",
  "Talleres recreativos",
  "Espacio para recreación",
  "Espacio para talleres",
  "Espacio para juego",
  "Juegos de destreza",
  "Gymkanas",
  "Búsqueda del tesoro",
  "Show de baile",
  "Show de música",
  "Show infantil",
  "Show de humor",
  "Show de talentos",
  "Karaoke para fiesta",
  "Trivia para fiesta",
  "Juegos de mesa para evento",
  "Juegos temáticos",
  "Juegos de rol",
  "Juegos interactivos",
  "Actividades recreativas",
  "Actividades para niños",
  "Actividades para adultos",
  "Actividades de integración",
  "Actividades deportivas",
  "Deportes para fiesta",
  "Juegos al aire libre",
  "Competencias deportivas",
  "Torneos de fútbol",
  "Torneos de vóley",
  "Torneos de básquet",
  "Torneos de tenis",
  "Torneos de paddle",
  "Torneos de cartas",
  "Torneos de mesa",
  "Juegos de agua",
  "Piscina para fiesta",
  "Alquiler de pileta",
  "Juegos de arena",
  "Fiesta en jardín",
  "Fiesta en terraza",
  "Fiesta en patio",
  "Fiesta en quincho",
  "Fiesta en salón",
  "Fiesta en casa",
  "Fiesta temática infantil",
  "Fiesta temática juvenil",
  "Fiesta temática adulta",
  "Fiesta de disfraces",
  "Fiesta de carnaval",
  "Fiesta de Halloween",
  "Fiesta de Navidad",
  "Fiesta de Año Nuevo",
  "Fiesta sorpresa",
  "Fiesta privada",
  "Fiesta VIP",
  "Fiesta corporativa",
  "Fiesta empresarial",
  "Fiesta de lanzamiento",
  "Evento de lanzamiento",
  "Evento de presentación",
  "Evento social",
  "Evento cultural",
  "Evento deportivo",
  "Evento recreativo",
  "Evento de integración",
  "Evento temático",
  "Evento infantil",
  "Evento juvenil",
  "Evento adulto",
  "Evento familiar",
  "Evento con catering",
  "Evento con música",
  "Evento con animación",
  "Evento con show",
  "Evento con fotografía",
  "Evento con video",
  "Evento con streaming",
  "Evento con luces",
  "Evento con sonido",
  "Evento al aire libre",
  "Evento en interiores",
  "Evento en salón",
  "Evento en casa",
  "Evento en quincho",
  "Evento en terraza",
  "Evento en parque",
  "Fiesta de cumpleaños",
  "Fiesta de casamiento",
  "Fiesta de boda",
  "Fiesta de 15 años",
  "Fiesta de aniversario",
  "Fiesta familiar",
  "Fiesta de amigos",
  "Fiesta de colegas",
  "Fiesta temática",
  "Fiesta de disfraces",
  "Fiesta de Navidad",
  "Fiesta de Año Nuevo",
  "Fiesta de carnaval",
  "Fiesta de Halloween",
  "Fiesta sorpresa",
  "Fiesta íntima",
  "Fiesta privada",
  "Fiesta con catering",
  "Fiesta con DJ",
  "Fiesta con música en vivo",
  "Fiesta con show",
  "Fiesta con animación",
  "Fiesta con payasos",
  "Fiesta con magos",
  "Fiesta con personajes",
  "Fiesta con cotillón",
  "Fiesta con decoración",
  "Fiesta con globos",
  "Fiesta con centros de mesa",
  "Fiesta con arco de globos",
  "Fiesta con guirnaldas",
  "Fiesta con cartelería",
  "Fiesta con photobooth",
  "Fiesta con cabina de fotos",
  "Fiesta con fotógrafo",
  "Fiesta con video",
  "Fiesta con streaming",
  "Fiesta con iluminación",
  "Fiesta con luces LED",
  "Fiesta con efectos de luz",
  "Fiesta con proyector",
  "Fiesta con pantalla",
  "Fiesta con sonido",
  "Fiesta con parlantes",
  "Fiesta con micrófono",
  "Fiesta con equipo de sonido",
  "Fiesta con alquiler de mesas",
  "Fiesta con alquiler de sillas",
  "Fiesta con alquiler de manteles",
  "Fiesta con alquiler de vajilla",
  "Fiesta con alquiler de cubiertos",
  "Fiesta con alquiler de copas",
  "Fiesta con alquiler de cristalería",
  "Fiesta con alquiler de pista de baile",
  "Fiesta con pista iluminada",
  "Fiesta con pista de LED",
  "Fiesta con inflables",
  "Fiesta con tobogán inflable",
  "Fiesta con castillos inflables",
  "Fiesta con juegos inflables",
  "Fiesta con tronas para niños",
  "Fiesta con juegos para niños",
  "Fiesta con taller infantil",
  "Fiesta con taller creativo",
  "Fiesta con taller de pintura",
  "Fiesta con taller de manualidades",
  "Fiesta con taller de cocina",
];
