// src/lib/keywords/fotografia.ts
export const FOTOGRAFIA_KEYWORDS = [
  "Fotógrafo a domicilio",
  "Fotografía de eventos",
  "Fotos para cumpleaños",
  "Fotos de casamiento",
  "Fotos de boda",
  "Sesión de fotos familiar",
  "Sesión de fotos infantil",
  "Sesión de fotos de embarazada",
  "Fotos newborn",
  "Fotos de bebés",
  "Sesión de fotos para chicos",
  "Fotografía de quinceañeras",
  "Fotografía de 15 años",
  "Fotos de graduación",
  "Fotos de egresados",
  "Fotos de fiesta",
  "Fotos de aniversario",
  "Sesión de fotos pareja",
  "Fotos de amor",
  "Sesión de fotos romántica",
  "Fotos en exteriores",
  "Fotos en estudio",
  "Fotos con fondo neutro",
  "Fotos de retrato",
  "Fotos profesionales",
  "Fotografía corporativa",
  "Fotos de producto",
  "Fotografía de producto",
  "Fotos para redes sociales",
  "Fotografía para Instagram",
  "Fotos para Facebook",
  "Fotografía publicitaria",
  "Fotografía artística",
  "Sesión de fotos artística",
  "Fotos creativas",
  "Fotos originales",
  "Sesión fotográfica",
  "Book fotográfico",
  "Book de fotos",
  "Fotos de perfil",
  "Fotos para CV",
  "Fotos de modelo",
  "Book de modelo",
  "Fotos fashion",
  "Fotografía de moda",
  "Fotos de lookbook",
  "Fotos de catálogo",
  "Fotografía de catálogo",
  "Fotografía gastronómica",
  "Fotos de comida",
  "Fotos de platos",
  "Fotografía de restaurantes",
  "Fotos para menú",
  "Fotos de eventos sociales",
  "Fotos de cumpleaños infantil",
  "Fotos de baby shower",
  "Fotos de bautismo",
  "Fotos de comunión",
  "Fotos de bar mitzvah",
  "Fotos de confirmación",
  "Fotos de eventos corporativos",
  "Fotos de reunión",
  "Fotos de conferencia",
  "Fotografía de conferencias",
  "Fotos de workshop",
  "Fotos de taller",
  "Fotos de seminario",
  "Fotos de exposición",
  "Fotografía de exposición",
  "Fotos de feria",
  "Fotos de festival",
  "Fotos de recital",
  "Fotografía de concierto",
  "Fotos de show",
  "Fotos de teatro",
  "Fotografía teatral",
  "Fotos de danza",
  "Fotografía de danza",
  "Fotos de ballet",
  "Fotos de coreografía",
  "Fotos de grupo",
  "Fotos de equipo",
  "Fotos de club",
  "Fotografía deportiva",
  "Fotos de fútbol",
  "Fotos de básquet",
  "Fotos de vóley",
  "Fotos de natación",
  "Fotos de entrenamiento",
  "Fotos de partido",
  "Fotos de torneo",
  "Fotos de campeonato",
  "Fotografía de acción",
  "Fotos de street",
  "Fotografía urbana",
  "Fotos callejeras",
  "Fotografía lifestyle",
  "Fotos de lifestyle",
  "Fotografía de paisaje",
  "Fotos de naturaleza",
  "Fotografía de exteriores",
  "Fotos de ciudad",
  "Fotos de parque",
  "Fotos de plaza",
  "Fotografía de monumentos",
  "Fotos de arquitectura",
  "Fotografía arquitectónica",
  "Fotos de edificios",
  "Fotos de interiores",
  "Fotografía de interiores",
  "Fotos de decoración",
  "Fotos de living",
  "Fotos de cocina",
  "Fotos de baño",
  "Fotos de habitación",
  "Fotografía inmobiliaria",
  "Fotos de casa",
  "Fotos de departamento",
  "Fotos de propiedad",
  "Fotos de terreno",
  "Fotos de barrio",
  "Fotografía de bienes raíces",
  "Fotos de hotel",
  "Fotos de hostel",
  "Fotos de cabaña",
  "Fotos de alquiler temporario",
  "Fotografía de turismo",
  "Fotos de viaje",
  "Fotos de vacaciones",
  "Fotos de paseo",
  "Fotografía de aventura",
  "Fotos de trekking",
  "Fotos de montaña",
  "Fotos de río",
  "Fotos de lago",
  "Fotos de playa",
  "Fotografía de naturaleza",
  "Fotos de fauna",
  "Fotos de flora",
  "Fotografía macro",
  "Fotos close-up",
  "Fotografía de detalle",
  "Fotos de texturas",
  "Fotos de paisaje urbano",
  "Fotos de ciudad",
  "Fotos de atardecer",
  "Fotos de amanecer",
  "Fotos de noche",
  "Fotografía nocturna",
  "Fotos de luces",
  "Fotos con flash",
  "Fotos sin flash",
  "Fotos en interiores",
  "Fotos en exteriores",
  "Fotos en estudio",
  "Sesión de fotos profesional",
  "Fotografía profesional",
  "Fotos de calidad",
  "Fotos HD",
  "Fotos en alta resolución",
  "Fotos imprimibles",
  "Fotos para impresión",
  "Impresión de fotos",
  "Revelado de fotos",
  "Revelado digital",
  "Impresión digital",
  "Fotos en papel fotográfico",
  "Fotos en lienzo",
  "Fotos en marco",
  "Fotos en poster",
  "Fotos en cuadro",
  "Álbum de fotos",
  "Book de fotos impreso",
  "Fotos para regalo",
  "Fotos para souvenir",
  "Fotos personalizadas",
  "Sesión fotográfica a medida",
  "Fotos a pedido",
  "Fotografía personalizada",
  "Fotos creativas",
  "Fotografía artística",
  "Sesión de fotos creativa",
  "Sesión de fotos artística",
  "Fotografía temática",
  "Fotos temáticas",
  "Fotografía infantil",
  "Fotos de bebés",
  "Fotos de niños",
  "Fotos de niñas",
  "Fotos de chicos",
  "Fotos de adolescentes",
  "Fotografía de adolescentes",
  "Fotos de familia",
  "Fotografía familiar",
  "Fotos de pareja",
  "Fotografía de pareja",
  "Fotos de amigos",
  "Fotos de grupo",
  "Fotos de mascota",
  "Fotografía de mascotas",
  "Fotos de perro",
  "Fotos de gato",
  "Fotos de animales domésticos",
  "Fotos de animales",
  "Fotografía de animales",
  "Fotos de eventos familiares",
  "Fotos de fiestas",
  "Fotografía de fiestas",
  "Fotos de cumpleaños",
  "Fotos de 15 años",
  "Fotos de casamiento",
  "Fotos de boda",
  "Fotos de aniversario",
  "Fotos de compromiso",
  "Fotografía de eventos",
  "Sesión de fotos evento",
  "Fotos de catering",
  "Fotografía gastronómica",
  "Fotos de comida",
  "Fotos de plato",
  "Fotos de menú",
  "Fotos de bebida",
  "Fotos de bar",
  "Fotografía de restaurante",
  "Fotografía de cafetería",
  "Fotografía de pastelería",
  "Fotos de torta",
  "Fotos de postre",
  "Fotos de mesa dulce",
  "Fotografía de producto",
  "Fotos de productos",
  "Fotos para e-commerce",
  "Fotos para catálogo",
  "Fotos para comercio",
  "Fotos publicitarias",
  "Fotografía publicitaria",
  "Fotos de publicidad",
  "Fotografía para marcas",
  "Fotos para redes",
  "Fotografía social media",
  "Fotos Instagram",
  "Fotos Facebook",
  "Fotos TikTok",
  "Fotografía de campaña",
  "Fotos de promo",
  "Fotos de evento corporativo",
  "Fotografía corporativa",
  "Fotos para empresa",
  "Fotos institucionales",
  "Fotografía institucional",
  "Fotos de reunión",
  "Fotografía de staff",
  "Fotos de personal",
  "Fotos de equipo",
  "Sesión de fotos laboral",
  "Fotografía profesional",
  "Fotos headshot",
  "Fotos carnet",
  "Fotos pasaporte",
  "Fotografía de identidad",
  "Fotos para DNI",
  "Fotos para documento",
  "Fotos escolares",
  "Fotografía escolar",
  "Fotos de graduación",
  "Sesión de fotos escolar",
  "Fotos de egresados",
  "Fotografía de egresados",
  "Fotos para revista escolar",
  "Fotos para memoria anual",
  "Fotografía comunitaria",
  "Fotos de evento social",
  "Fotografía de actividad",
  "Fotos recreativas",
  "Fotos deportivas",
  "Fotografía de deporte",
  "Fotos de partido",
  "Fotos Polaroid",
  "Fotos de entrenamiento",
  "Cuadros con fotos",
  "Fotografía educativa",
  "Fotos para folleto",
  "Fotos para catálogo",
  "Fotos para web",
  "Fotografía web",
  "Fotos para ecommerce",
  "Fotografía digital",
  "Fotos digitales",
  "Fotos online",
  "Sesión de fotos virtual",
  "Sesión de fotos remota",
  "Fotos impresas",
  "Fotos en papel",
  "Fotos laminadas",
  "Fotos para regalar",
  "Fotos souvenir",
  "Álbum fotográfico",
  "Fotos collage",
  "Montaje de fotos",
  "Fotografía y revelado",
];
