// src/lib/keywords/gasista.ts
export const GASISTA_KEYWORDS = [
  "fuga de gas en cocina",
  "calefón no prende",
  "caño de gas roto",
  "cocina a gas que no enciende",
  "fuga en calefón",
  "tubo de gas flojo",
  "regulador de gas que no funciona",
  "cocina que apesta a gas",
  "calefón con llama baja",
  "caño de gas picado",
  "cocina que corta el gas",
  "conexión de calefón floja",
  "fuga de gas en caño externo",
  "regulador que pita",
  "calefón que corta el gas",
  "caño de gas enterrado con fuga",
  "hornalla que no enciende",
  "caño de gas con presión baja",
  "calefón con olor a gas",
  "caño de cocina flojo",
  "cocina a gas que corta llama",
  "calefón que no calienta",
  "tubo de gas flojo en calefón",
  "fuga de gas en horno",
  "cocina a gas con llama amarilla",
  "tubería de gas corroída",
  "regulador de gas flojo",
  "calefón que corta llama",
  "cocina que no llega gas",
  "caño de gas picado o agujereado",
  "fuga de gas en calefón externo",
  "hornalla que no prende bien",
  "cocina que corta gas sola",
  "regulador que no mantiene presión",
  "calefón con llama inestable",
  "caño de gas con fuga interna",
  "cocina que no calienta ollas",
  "fuga de gas en horno externo",
  "calefón que corta gas externo",
  "caño de gas flojo en cocina",
  "hornalla que corta llama",
  "cocina con olor a gas",
  "calefón que no prende externo",
  "tubería de gas vieja",
  "regulador de gas que pita",
  "caño de gas que vibra",
  "fuga de gas cerca de cocina",
  "calefón que no prende llama",
  "hornalla que corta gas interna",
  "cocina a gas con llama irregular",
  "caño de gas enterrado con fuga",
  "regulador de gas defectuoso",
  "calefón con olor a gas",
  "caño de cocina corroído",
  "fuga de gas interna",
  "hornalla que no prende externa",
  "cocina con fuga de gas externa",
  "obra de gas nueva cocina",
  "obra de gas calefón",
  "ampliación de gas en departamento",
  "caños de gas nuevos",
  "cambio de caños de gas",
  "obra de gas para horno",
  "instalación de gas exterior",
  "conexión de gas nueva",
  "obra de gas en edificio",
  "ampliación de hornallas",
];
