// src/lib/keywords/herreria.ts
export const HERRERIA_KEYWORDS = [
  "Herrero a domicilio",
  "Herrería artesanal",
  "Herrería metálica",
  "Herrería de hierro",
  "Herrería de acero",
  "Herrería de aluminio",
  "Rejas",
  "Rejas para ventanas",
  "Rejas para puertas",
  "Rejas de seguridad",
  "Rejas decorativas",
  "Portones",
  "Portones de hierro",
  "Portones automáticos",
  "Portones corredizos",
  "Portones levadizos",
  "Portones peatonales",
  "Portones de entrada",
  "Portones para cocheras",
  "Barandas",
  "Barandas de escaleras",
  "Barandas de balcones",
  "Barandas de terrazas",
  "Barandas de seguridad",
  "Escaleras metálicas",
  "Escaleras de hierro",
  "Escaleras de acero",
  "Escaleras a medida",
  "Escaleras de interior",
  "Escaleras de exterior",
  "Escaleras de caracol",
  "Escaleras industriales",
  "Escaleras para depósitos",
  "Escaleras para casas",
  "Escaleras para edificios",
  "Portones de hierro forjado",
  "Portones de acero inoxidable",
  "Portones de aluminio",
  "Portones para barrios cerrados",
  "Portones automáticos con control remoto",
  "Cerramientos",
  "Cerramientos metálicos",
  "Cerramientos de hierro",
  "Cerramientos de acero",
  "Cerramientos de aluminio",
  "Cerramientos de patios",
  "Cerramientos de jardines",
  "Cerramientos de terrazas",
  "Cerramientos de balcones",
  "Cerramientos de locales",
  "Cerramientos de depósitos",
  "Cerramientos de galpones",
  "Cerramientos de cocheras",
  "Puertas metálicas",
  "Puertas de hierro",
  "Puertas de acero",
  "Puertas de aluminio",
  "Puertas automáticas",
  "Puertas corredizas",
  "Puertas batientes",
  "Puertas de seguridad",
  "Puertas decorativas",
  "Portones con motor",
  "Portones eléctricos",
  "Portones manuales",
  "Portones de chapa",
  "Portones reforzados",
  "Barandas de hierro",
  "Barandas de acero inoxidable",
  "Barandas para escaleras",
  "Barandas para balcones",
  "Barandas para terrazas",
  "Barandas decorativas",
  "Barandas de seguridad",
  "Escaleras metálicas interiores",
  "Escaleras metálicas exteriores",
  "Escaleras industriales metálicas",
  "Escaleras de hierro fundido",
  "Escaleras de hierro reciclado",
  "Escaleras de acero inoxidable",
  "Escaleras personalizadas",
  "Escaleras a medida",
  "Escaleras de caracol metálicas",
  "Escaleras modernas",
  "Escaleras clásicas",
  "Escaleras para locales",
  "Escaleras para oficinas",
  "Escaleras para casas",
  "Escaleras para edificios",
  "Rejas de hierro",
  "Rejas de acero",
  "Rejas de aluminio",
  "Rejas para seguridad",
  "Rejas decorativas",
  "Rejas para ventanas",
  "Rejas para puertas",
  "Rejas para jardines",
  "Rejas para balcones",
  "Rejas para terrazas",
  "Rejas para locales",
  "Rejas para cocheras",
  "Rejas con diseño",
  "Rejas a medida",
  "Rejas con refuerzo",
  "Rejas plegables",
  "Rejas corredizas",
  "Rejas batientes",
  "Rejas automáticas",
  "Rejas manuales",
  "Portones de hierro forjado",
  "Portones de acero inoxidable",
  "Portones a medida",
  "Portones reforzados",
  "Portones decorativos",
  "Portones automáticos con control remoto",
  "Portones con motor eléctrico",
  "Portones manuales",
  "Portones para casas",
  "Portones para cocheras",
  "Portones para barrios cerrados",
  "Portones para locales",
  "Portones para depósitos",
  "Portones para galpones",
  "Cerramientos metálicos",
  "Cerramientos de hierro",
  "Cerramientos de acero",
  "Cerramientos de aluminio",
  "Cerramientos de patios",
  "Cerramientos de jardines",
  "Cerramientos de balcones",
  "Cerramientos de terrazas",
  "Cerramientos de locales",
  "Cerramientos de depósitos",
  "Cerramientos de galpones",
  "Cerramientos de cocheras",
  "Cerramientos a medida",
  "Cerramientos con rejas",
  "Cerramientos con puertas",
  "Cerramientos decorativos",
  "Cerramientos de seguridad",
  "Puertas de hierro",
  "Puertas de acero",
  "Puertas de aluminio",
  "Puertas automáticas",
  "Puertas corredizas",
  "Puertas batientes",
  "Puertas de seguridad",
  "Puertas decorativas",
  "Puertas reforzadas",
  "Puertas a medida",
  "Puertas de locales",
  "Puertas de casas",
  "Puertas de oficinas",
  "Puertas de galpones",
  "Puertas de depósitos",
  "Puertas de balcones",
  "Puertas de terrazas",
  "Portones metálicos",
  "Portones de hierro",
  "Portones de acero",
  "Portones de aluminio",
  "Portones automáticos",
  "Portones manuales",
  "Portones corredizos",
  "Portones batientes",
  "Portones de seguridad",
  "Portones decorativos",
  "Portones reforzados",
  "Portones a medida",
  "Portones para casas",
  "Portones para cocheras",
  "Portones para barrios cerrados",
  "Portones para locales",
  "Portones para depósitos",
  "Portones para galpones",
  "Barandas metálicas",
  "Barandas de hierro",
  "Barandas de acero inoxidable",
  "Barandas para escaleras",
  "Barandas para balcones",
  "Barandas para terrazas",
  "Barandas decorativas",
  "Barandas de seguridad",
  "Barandas a medida",
  "Barandas reforzadas",
  "Escaleras metálicas",
  "Escaleras de hierro",
  "Escaleras de acero",
  "Escaleras de aluminio",
  "Escaleras interiores",
  "Escaleras exteriores",
  "Escaleras a medida",
  "Escaleras personalizadas",
  "Escaleras modernas",
  "Escaleras clásicas",
  "Escaleras industriales",
  "Escaleras de caracol",
  "Escaleras con barandas",
  "Escaleras con peldaños metálicos",
  "Escaleras reforzadas",
  "Escaleras para casas",
  "Escaleras para oficinas",
  "Escaleras para locales",
  "Escaleras para depósitos",
  "Escaleras para galpones",
  "Escaleras para edificios",
  "Escaleras seguras",
  "Escaleras decorativas",
  "Escaleras resistentes",
  "Herrería artística",
  "Herrería decorativa",
  "Herrería de diseño",
  "Herrería personalizada",
  "Herrería a medida",
  "Herrería en hierro",
  "Herrería en acero",
  "Herrería en aluminio",
  "Herrería de jardín",
  "Herrería de balcón",
  "Herrería de terraza",
  "Herrería de escalera",
  "Herrería de puerta",
  "Herrería de portón",
  "Herrería de baranda",
  "Herrería de reja",
  "Herrería para locales",
  "Herrería para depósitos",
  "Herrería para galpones",
  "Herrería para casas",
  "Herrería para oficinas",
  "Herrería con pintura",
  "Herrería con esmalte",
  "Herrería con galvanizado",
  "Herrería inoxidable",
  "Herrería reforzada",
  "Herrería segura",
  "Herrería resistente",
  "Herrería artística a medida",
  "Herrería decorativa a medida",
  "Herrería para seguridad",
  "Herrería con diseño moderno",
  "Herrería con diseño clásico",
  "Herrería industrial",
  "Herrería residencial",
  "Herrería comercial",
  "Herrería de obra",
  "Herrería de mantenimiento",
  "Reparación de rejas",
  "Reparación de portones",
  "Reparación de barandas",
  "Reparación de escaleras",
  "Reparación de puertas",
  "Reparación de cerramientos",
  "Reparación de herrería en general",
  "Mantenimiento de rejas",
  "Mantenimiento de portones",
  "Mantenimiento de barandas",
  "Mantenimiento de escaleras",
  "Mantenimiento de puertas",
  "Mantenimiento de cerramientos",
  "Mantenimiento de herrería en general",
  "Colocación de rejas",
  "Colocación de portones",
  "Colocación de barandas",
  "Colocación de escaleras",
  "Colocación de puertas",
  "Colocación de cerramientos",
  "Colocación de herrería en general",
  "Instalación de rejas",
  "Instalación de portones",
];
