// src/lib/keywords/jardineria.ts
export const JARDINERIA_KEYWORDS = [
  "Jardinero a domicilio",
  "Mantenimiento de jardines",
  "Cortar el pasto",
  "Podar árboles",
  "Podar arbustos",
  "Riego de jardines",
  "Fertilización de plantas",
  "Plantación de flores",
  "Diseño de jardines",
  "Mantenimiento de césped",
  "Sembrar césped",
  "Corte de césped",
  "Limpieza de hojas",
  "Limpieza de ramas",
  "Plantación de árboles",
  "Plantación de arbustos",
  "Poda de setos",
  "Poda de palmeras",
  "Tala de árboles",
  "Retiro de escombros de jardín",
  "Retiro de ramas",
  "Retiro de hojas",
  "Mantener huerta",
  "Plantación de hortalizas",
  "Mantenimiento de huerta",
  "Diseño de huerta",
  "Fertilizante natural",
  "Fertilizante químico",
  "Compostaje",
  "Colocación de riego por goteo",
  "Mantenimiento de riego",
  "Instalación de sistema de riego",
  "Reparación de riego",
  "Plantación de césped natural",
  "Plantación de césped artificial",
  "Corte de césped artificial",
  "Corte de césped natural",
  "Escarda de jardín",
  "Escarda de huerta",
  "Abono orgánico",
  "Abono químico",
  "Colocación de mulch",
  "Mantenimiento de mulch",
  "Colocación de piedras decorativas",
  "Colocación de piedras de jardín",
  "Colocación de piedras para senderos",
  "Colocación de plantas en macetas",
  "Trasplante de plantas",
  "Trasplante de árboles",
  "Trasplante de arbustos",
  "Diseño de canteros",
  "Limpieza de canteros",
  "Corte de setos",
  "Poda de rosales",
  "Pulverización de plantas",
  "Limpieza de jardines",
  "Barrido de hojas",
  "Recolección de hojas",
  "Recolección de ramas",
  "Retiro de ramas caídas",
  "Retiro de hojas caídas",
  "Recolección de escombros",
  "Retiro de basura de jardín",
  "Colocación de tepes de césped",
  "Instalación de tepes",
  "Riego manual",
  "Riego automático",
  "Instalación de aspersores",
  "Mantenimiento de aspersores",
  "Corte de palmeras",
  "Tala de palmeras",
  "Desmalezado",
  "Escardado manual",
  "Escardado con herramientas",
  "Escardado mecánico",
  "Nivelación de terreno",
  "Acondicionamiento de suelo",
  "Aireado de césped",
  "Aireado de jardín",
  "Fertilización de césped",
  "Fertilización de huerta",
  "Fertilización de árboles",
  "Fertilización de arbustos",
  "Fertilización de plantas",
  "Colocación de bordes de jardín",
  "Colocación de bordes de canteros",
  "Colocación de bordes de senderos",
  "Limpieza de canaletas de jardín",
  "Limpieza de desagües",
  "Mantenimiento de canaletas",
  "Plantación de flores anuales",
  "Plantación de flores perennes",
  "Plantación de plantas aromáticas",
  "Plantación de hierbas",
  "Plantación de hortalizas",
  "Diseño de huerta orgánica",
  "Cuidado de huerta orgánica",
  "Poda de frutales",
  "Poda de árboles frutales",
  "Poda de árboles ornamentales",
  "Poda de arbustos ornamentales",
  "Corte de ramas secas",
  "Corte de ramas enfermas",
  "Retiro de ramas secas",
  "Retiro de ramas enfermas",
  "Mulching",
  "Colocación de mulch decorativo",
  "Colocación de mulch orgánico",
  "Colocación de mulch vegetal",
  "Colocación de mulch inorgánico",
  "Riego por goteo",
  "Instalación de riego por goteo",
  "Mantenimiento de riego por goteo",
  "Instalación de cañerías para riego",
  "Mantenimiento de cañerías",
  "Limpieza de cañerías",
  "Reposición de plantas",
  "Reposición de césped",
  "Reposición de flores",
  "Reposición de arbustos",
  "Reposición de árboles",
  "Cuidado de plantas",
  "Cuidado de flores",
  "Cuidado de arbustos",
  "Cuidado de árboles",
  "Poda de arbustos bajos",
  "Poda de arbustos altos",
  "Poda de setos decorativos",
  "Poda de setos frutales",
  "Corte de árboles pequeños",
  "Corte de árboles medianos",
  "Corte de árboles grandes",
  "Plantación de árboles frutales",
  "Plantación de árboles ornamentales",
  "Plantación de arbustos ornamentales",
  "Colocación de césped en rollo",
  "Colocación de césped en tepes",
  "Reemplazo de césped",
  "Reemplazo de plantas",
  "Diseño de jardines residenciales",
  "Diseño de jardines comerciales",
  "Mantenimiento de jardines residenciales",
  "Mantenimiento de jardines comerciales",
  "Plantación de plantas trepadoras",
  "Mantenimiento de plantas trepadoras",
  "Colocación de enrejados para plantas trepadoras",
  "Cuidado de plantas en macetas",
  "Trasplante de plantas en macetas",
  "Fertilización de plantas en macetas",
  "Podar plantas en macetas",
  "Diseño de senderos",
  "Colocación de senderos de piedra",
  "Colocación de senderos de madera",
  "Colocación de senderos de ladrillo",
  "Colocación de senderos de cemento",
  "Instalación de sistemas de riego subterráneo",
  "Instalación de sistemas de riego superficial",
  "Mantenimiento de sistemas de riego",
  "Reparación de sistemas de riego",
  "Colocación de maceteros grandes",
  "Colocación de maceteros pequeños",
  "Decoración de jardines con maceteros",
  "Mantenimiento de maceteros",
  "Plantación de flores en maceteros",
  "Plantación de arbustos en maceteros",
  "Plantación de árboles en maceteros",
  "Limpieza de maceteros",
  "Corte de césped de parques",
  "Mantenimiento de parques",
  "Diseño de parques",
  "Plantación de césped en parques",
  "Plantación de árboles en parques",
  "Plantación de arbustos en parques",
  "Poda de árboles en parques",
  "Poda de arbustos en parques",
  "Colocación de bancos de jardín",
  "Colocación de mesas de jardín",
  "Colocación de pérgolas",
  "Colocación de sombras",
  "Colocación de luces de jardín",
  "Mantenimiento de luces de jardín",
  "Instalación de iluminación de jardín",
  "Diseño de iluminación de jardín",
  "Corte de pasto en parques",
  "Corte de pasto en jardines residenciales",
  "Corte de pasto en jardines comerciales",
  "Aireado de césped de parques",
  "Aireado de césped de jardines",
  "Fertilización de césped de parques",
  "Fertilización de césped de jardines",
  "Trasplante de césped",
  "Trasplante de flores",
  "Trasplante de arbustos",
  "Trasplante de árboles",
  "Reposición de césped",
  "Reposición de flores",
  "Reposición de arbustos",
  "Reposición de árboles",
  "Colocación de piedra decorativa en jardines",
  "Colocación de piedra decorativa en canteros",
  "Colocación de piedra decorativa en senderos",
  "Colocación de mulch en canteros",
  "Colocación de mulch en senderos",
  "Colocación de mulch en jardines",
  "Limpieza de piedras decorativas",
  "Limpieza de senderos",
  "Limpieza de canteros",
  "Limpieza de macetas",
  "Poda de setos en parques",
  "Poda de rosales en jardines",
  "Poda de rosales en macetas",
  "Corte de palmeras en jardines",
  "Tala de palmeras en jardines",
  "Instalación de riego manual",
  "Instalación de riego automático",
  "Instalación de aspersores manuales",
  "Instalación de aspersores automáticos",
  "Mantenimiento de aspersores manuales",
  "Mantenimiento de aspersores automáticos",
  "Colocación de tepes en jardines",
  "Colocación de tepes en parques",
  "Colocación de tepes en huertas",
  "Reposición de tepes",
  "Corte de setos decorativos",
  "Corte de setos frutales",
  "Corte de setos ornamentales",
  "Diseño de canteros",
  "Diseño de senderos",
  "Diseño de jardines verticales",
  "Plantación de jardines verticales",
  "Mantenimiento de jardines verticales",
  "Fertilización de jardines verticales",
  "Riego de jardines verticales",
  "Trasplante de plantas en jardines verticales",
  "Colocación de maceteros en jardines verticales",
  "Poda de plantas en jardines verticales",
  "Plantación de flores de temporada",
  "Plantación de flores perennes",
  "Plantación de plantas aromáticas",
  "Plantación de hortalizas en huertas",
  "Cuidado de hortalizas",
  "Cuidado de plantas aromáticas",
  "Trasplante de hortalizas",
  "Trasplante de plantas aromáticas",
  "Diseño de huertas urbanas",
  "Diseño de huertas residenciales",
  "Diseño de huertas comerciales",
  "Instalación de riego en huertas",
  "Mantenimiento de huertas urbanas",
  "Mantenimiento de huertas residenciales",
  "Mantenimiento de huertas comerciales",
  "Corte de arbustos bajos",
  "Corte de arbustos altos",
  "Corte de setos ornamentales",
  "Corte de setos frutales",
  "Reposición de arbustos bajos",
  "Reposición de arbustos altos",
  "Reposición de arbustos ornamentales",
  "Reposición de arbustos frutales",
  "Trasplante de arbustos bajos",
  "Trasplante de arbustos altos",
  "Trasplante de arbustos ornamentales",
  "Trasplante de arbustos frutales",
  "Plantación de árboles pequeños",
  "Plantación de árboles medianos",
  "Plantación de árboles grandes",
  "Poda de árboles pequeños",
  "Poda de árboles medianos",
  "Poda de árboles grandes",
  "Reposición de árboles pequeños",
  "Reposición de árboles medianos",
  "Reposición de árboles grandes",
  "Trasplante de árboles pequeños",
  "Trasplante de árboles medianos",
  "Trasplante de árboles grandes",
  "Diseño de espacios verdes",
  "Mantenimiento de espacios verdes",
  "Plantación de flores en espacios verdes",
  "Plantación de arbustos en espacios verdes",
  "Plantación de árboles en espacios verdes",
  "Poda de flores en espacios verdes",
  "Poda de arbustos en espacios verdes",
  "Poda de árboles en espacios verdes",
  "Corte de césped en espacios verdes",
  "Fertilización en espacios verdes",
  "Trasplante en espacios verdes",
  "Colocación de mulch en espacios verdes",
  "Colocación de piedras decorativas en espacios verdes",
  "Instalación de riego en espacios verdes",
  "Mantenimiento de riego en espacios verdes",
  "Limpieza de espacios verdes",
  "Aireado de césped en espacios verdes",
  "Nivelación de terreno en espacios verdes",
  "Acondicionamiento de suelo en espacios verdes",
  "Diseño de senderos en espacios verdes",
  "Colocación de bordes en espacios verdes",
  "Colocación de maceteros en espacios verdes",
  "Plantación de flores en maceteros de espacios verdes",
  "Plantación de arbustos en maceteros de espacios verdes",
  "Plantación de árboles en maceteros de espacios verdes"
];
