// src/lib/keywords/limpieza.ts
export const LIMPIEZA_KEYWORDS = [
  "Limpieza a domicilio",
  "Limpieza de casas",
  "Limpieza de departamentos",
  "Limpieza de oficinas",
  "Limpieza de locales comerciales",
  "Limpieza profunda",
  "Limpieza general",
  "Limpieza de vidrios",
  "Limpieza de alfombras",
  "Limpieza de tapicerías",
  "Limpieza de cortinas",
  "Limpieza de muebles",
  "Limpieza de cocinas",
  "Limpieza de baños",
  "Limpieza de pisos",
  "Limpieza de pisos de madera",
  "Limpieza de pisos cerámicos",
  "Limpieza de pisos de cemento",
  "Limpieza de techos",
  "Limpieza de paredes",
  "Limpieza de garajes",
  "Limpieza de sótanos",
  "Limpieza de azoteas",
  "Limpieza de terrazas",
  "Limpieza post obra",
  "Limpieza después de mudanza",
  "Limpieza de edificios",
  "Limpieza de escalera",
  "Limpieza de ascensores",
  "Limpieza de locales gastronómicos",
  "Limpieza de restaurantes",
  "Limpieza de bares",
  "Limpieza de oficinas corporativas",
  "Limpieza de fábricas",
  "Limpieza industrial",
  "Limpieza de vidrieras",
  "Limpieza de escaparates",
  "Limpieza de cristales",
  "Limpieza de ventanas",
  "Limpieza de persianas",
  "Limpieza de toldos",
  "Limpieza de muebles de oficina",
  "Limpieza de escritorios",
  "Limpieza de sillas",
  "Limpieza de sillones",
  "Limpieza de colchones",
  "Limpieza de camas",
  "Limpieza de ropa blanca",
  "Limpieza de alfombras persas",
  "Limpieza de tapices",
  "Limpieza de cortinas de tela",
  "Limpieza de cortinas de vinilo",
  "Limpieza de cocinas industriales",
  "Limpieza de hornos",
  "Limpieza de campanas extractoras",
  "Limpieza de ventilación",
  "Limpieza de rejillas",
  "Limpieza de conductos",
  "Limpieza de baños públicos",
  "Limpieza de inodoros",
  "Limpieza de urinarios",
  "Limpieza de lavamanos",
  "Limpieza de duchas",
  "Limpieza de grifería",
  "Limpieza de espejos",
  "Limpieza de pisos de cerámica",
  "Limpieza de pisos de mármol",
  "Limpieza de pisos de granito",
  "Limpieza de pisos de parquet",
  "Limpieza de pisos flotantes",
  "Limpieza de pisos vinílicos",
  "Limpieza de garajes subterráneos",
  "Limpieza de estacionamientos",
  "Limpieza de escaleras comunes",
  "Limpieza de pasillos",
  "Limpieza de ascensores internos",
  "Limpieza de oficinas administrativas",
  "Limpieza de escritorios compartidos",
  "Limpieza de salas de reuniones",
  "Limpieza de salones de eventos",
  "Limpieza de gimnasios",
  "Limpieza de vestuarios",
  "Limpieza de saunas",
  "Limpieza de piscinas",
  "Limpieza de spa",
  "Limpieza de comedores",
  "Limpieza de cocinas de restaurantes",
  "Limpieza de hornos industriales",
  "Limpieza de freidoras",
  "Limpieza de parrillas",
  "Limpieza de campanas de extracción",
  "Limpieza de pisos industriales",
  "Limpieza de maquinarias",
  "Limpieza de talleres",
  "Limpieza de naves industriales",
  "Limpieza de depósitos",
  "Limpieza de almacenes",
  "Limpieza de vidrios grandes",
  "Limpieza de ventanas altas",
  "Limpieza de vitrinas comerciales",
  "Limpieza de escaparates de tiendas",
  "Limpieza de persianas de madera",
  "Limpieza de persianas metálicas",
  "Limpieza de toldos retráctiles",
  "Limpieza de cortinas enrollables",
  "Limpieza de sillones de cuero",
  "Limpieza de sillones de tela",
  "Limpieza de sillas de oficina",
  "Limpieza de sillas de comedor",
  "Limpieza de mesas",
  "Limpieza de escritorios de madera",
  "Limpieza de escritorios de metal",
  "Limpieza de colchones de matrimonio",
  "Limpieza de colchones individuales",
  "Limpieza de almohadas",
  "Limpieza de edredones",
  "Limpieza de mantas",
  "Limpieza de frazadas",
  "Limpieza de ropa de cama",
  "Limpieza de ropa blanca de hotel",
  "Limpieza de tapices de pared",
  "Limpieza de alfombras de salón",
  "Limpieza de alfombras de oficina",
  "Limpieza de alfombras de habitación",
  "Limpieza de cortinas blackout",
  "Limpieza de cortinas de tela ligera",
  "Limpieza de cortinas gruesas",
  "Limpieza de persianas verticales",
  "Limpieza de persianas horizontales",
  "Limpieza de paneles de ventana",
  "Limpieza de vidrios templados",
  "Limpieza de espejos grandes",
  "Limpieza de cristales de baño",
  "Limpieza de puertas de vidrio",
  "Limpieza de barandas de vidrio",
  "Limpieza de cocinas domésticas",
  "Limpieza de hornos de hogar",
  "Limpieza de microondas",
  "Limpieza de anafes",
  "Limpieza de campanas",
  "Limpieza de heladeras",
  "Limpieza de freezers",
  "Limpieza de lavavajillas",
  "Limpieza de utensilios de cocina",
  "Limpieza de pisos de cocina",
  "Limpieza de baños de casa",
  "Limpieza de baños de oficina",
  "Limpieza de grifería de cocina",
  "Limpieza de grifería de baño",
  "Limpieza de lavatorios",
  "Limpieza de duchas",
  "Limpieza de bañeras",
  "Limpieza de sanitarios",
  "Limpieza de espejos de baño",
  "Limpieza de pisos de baño",
  "Limpieza de pisos de living",
  "Limpieza de pisos de comedor",
  "Limpieza de pisos de dormitorio",
  "Limpieza de pisos de pasillo",
  "Limpieza de pisos de escalera",
  "Limpieza de pisos flotantes de madera",
  "Limpieza de pisos de parquet",
  "Limpieza de pisos de vinilo",
  "Limpieza de pisos de cerámica",
  "Limpieza de pisos de porcelanato",
  "Limpieza de oficinas administrativas",
  "Limpieza de salas de reuniones",
  "Limpieza de salones de eventos",
  "Limpieza de gimnasios",
  "Limpieza de vestuarios",
  "Limpieza de saunas",
  "Limpieza de piscinas",
  "Limpieza de spa",
  "Limpieza de comedores",
  "Limpieza de cocinas de restaurantes",
  "Limpieza de hornos industriales",
  "Limpieza de freidoras",
  "Limpieza de parrillas",
  "Limpieza de campanas extractoras",
  "Limpieza de pisos industriales",
  "Limpieza de maquinarias",
  "Limpieza de talleres",
  "Limpieza de naves industriales",
  "Limpieza de depósitos",
  "Limpieza de almacenes",
  "Limpieza de vidrios grandes",
  "Limpieza de ventanas altas",
  "Limpieza de vitrinas comerciales",
  "Limpieza de escaparates de tiendas",
  "Limpieza de persianas de madera",
  "Limpieza de persianas metálicas",
  "Limpieza de toldos retráctiles",
  "Limpieza de cortinas enrollables",
  "Limpieza de sillones de cuero",
  "Limpieza de sillones de tela",
  "Limpieza de sillas de oficina",
  "Limpieza de sillas de comedor",
  "Limpieza de mesas de comedor",
  "Limpieza de escritorios de madera",
  "Limpieza de escritorios de metal",
  "Limpieza de colchones",
  "Limpieza de almohadas",
  "Limpieza de edredones",
  "Limpieza de mantas",
  "Limpieza de frazadas",
  "Limpieza de ropa de cama",
  "Limpieza de ropa blanca de hotel",
  "Limpieza de tapices de pared",
  "Limpieza de alfombras de salón",
  "Limpieza de alfombras de oficina",
  "Limpieza de alfombras de habitación",
  "Limpieza de cortinas blackout",
  "Limpieza de cortinas de tela ligera",
  "Limpieza de cortinas gruesas",
  "Limpieza de persianas verticales",
  "Limpieza de persianas horizontales",
  "Limpieza de paneles de ventana",
  "Limpieza de vidrios templados",
  "Limpieza de espejos grandes",
  "Limpieza de cristales de baño",
  "Limpieza de puertas de vidrio",
  "Limpieza de barandas de vidrio",
  "Limpieza de cocinas domésticas",
  "Limpieza de hornos de hogar",
  "Limpieza de microondas",
  "Limpieza de anafes",
  "Limpieza de campanas",
  "Limpieza de heladeras",
  "Limpieza de freezers",
  "Limpieza de lavavajillas",
  "Limpieza de utensilios de cocina",
  "Limpieza de pisos de cocina",
  "Limpieza de baños de casa",
  "Limpieza de baños de oficina",
  "Limpieza de grifería de cocina",
  "Limpieza de grifería de baño",
  "Limpieza de lavatorios",
  "Limpieza de duchas"
];
