// src/lib/keywords/mascotas.ts
export const MASCOTAS_KEYWORDS = [
  "Peluquería canina",
  "Peluquería para perros",
  "Peluquería para gatos",
  "Corte de pelo perro",
  "Corte de pelo gato",
  "Baño para perros",
  "Baño para gatos",
  "Spa para perros",
  "Spa para gatos",
  "Corte de uñas perro",
  "Corte de uñas gato",
  "Limpieza de orejas perro",
  "Limpieza de orejas gato",
  "Desparasitación perro",
  "Desparasitación gato",
  "Vacunación perro",
  "Vacunación gato",
  "Veterinario a domicilio",
  "Veterinario cercano",
  "Consulta veterinaria",
  "Consulta vet",
  "Clínica veterinaria",
  "Hospital veterinario",
  "Medicina veterinaria",
  "Atención veterinaria",
  "Urgencias veterinarias",
  "Emergencias mascotas",
  "Paseador de perros",
  "Paseo de perros",
  "Dog walker",
  "Paseador de mascotas",
  "Guardería canina",
  "Guardería felina",
  "Guardería de mascotas",
  "Hotel para perros",
  "Hotel para gatos",
  "Residencia canina",
  "Residencia felina",
  "Cuidado de perros",
  "Cuidado de gatos",
  "Entrenador de perros",
  "Adiestrador de perros",
  "Obediencia canina",
  "Educador canino",
  "Clases de perros",
  "Clases de obediencia",
  "Entrenamiento de cachorros",
  "Socialización de perros",
  "Paseo perros barrio",
  "Paseo perros zona",
  "Alimentación perros",
  "Alimentación gatos",
  "Comida balanceada perro",
  "Comida balanceada gato",
  "Pienso para perros",
  "Pienso para gatos",
  "Snack perro",
  "Snack gato",
  "Galletitas perro",
  "Premios perro",
  "Premios gato",
  "Collares perro",
  "Collares gato",
  "Correas perro",
  "Arneses perro",
  "Juguetes para perros",
  "Juguetes para gatos",
  "Pelotas perro",
  "Huesos de juguete",
  "Ratones de juguete",
  "Rascadores gatos",
  "Camas perros",
  "Camas gatos",
  "Cucha perro",
  "Cucha gato",
  "Transporte mascotas",
  "Transportadora perro",
  "Transportadora gato",
  "Cuidado diario mascotas",
  "Cuidados especiales perro",
  "Cuidados especiales gato",
  "Guardería canina cercana",
  "Guardería de gatos",
  "Estética canina",
  "Spa para perros",
  "Spa felino",
  "Corte creativo perro",
  "Corte creativo gato",
  "Peluquería creativa",
  "Baño antipulgas",
  "Baño antiséptico perro",
  "Baño antiséptico gato",
  "Baño medicinal perro",
  "Baño medicinal gato",
  "Champú para perros",
  "Champú para gatos",
  "Productos grooming",
  "Grooming perros",
  "Grooming gatos",
  "Limpieza dentaria perro",
  "Limpieza dentaria gato",
  "Higiene oral mascotas",
  "Cepillado dientes perro",
  "Cepillado dientes gato",
  "Cepillado diario mascotas",
  "Peinado diario perro",
  "Peinado diario gato",
  "Secado perro",
  "Secado gato",
  "Corte pelo caniche",
  "Corte pelo schnauzer",
  "Corte pelo poodle",
  "Corte pelo yorkshire",
  "Corte pelo maltés",
  "Corte pelo shih tzu",
  "Corte pelo bulldog",
  "Corte pelo labrador",
  "Corte pelo golden",
  "Corte pelo pastor alemán",
  "Corte pelo rottweiler",
  "Corte pelo boxer",
  "Corte pelo beagle",
  "Corte pelo schnauzer mini",
  "Corte pelo caniche mini",
  "Corte pelo yorkie",
  "Corte pelo poodle toy",
  "Baño antipulgas",
  "Baño antifleas",
  "Control pulgas y garrapatas",
  "Productos antipulgas",
  "Spray antipulgas",
  "Pipetas antipulgas",
  "Collar antipulgas",
  "Desparasitante interno",
  "Desparasitante externo",
  "Vacuna antirrábica",
  "Vacuna trivalente",
  "Vacuna pentavalente",
  "Certificado veterinario",
  "Certificado salud mascota",
  "Chequeo anual perro",
  "Chequeo anual gato",
  "Controles periódicos mascotas",
  "Revisión general mascotas",
  "Vacunación cachorros",
  "Vacunación gatitos",
  "Control de peso perro",
  "Control de peso gato",
  "Nutrición canina",
  "Nutrición felina",
  "Dieta especial perro",
  "Dieta especial gato",
  "Comida light perro",
  "Comida light gato",
  "Comida hipoalergénica perro",
  "Comida hipoalergénica gato",
  "Snack natural perro",
  "Snack natural gato",
  "Snack casero perro",
  "Snack casero gato",
  "Entrenamiento cachorros",
  "Adiestramiento perros",
  "Socialización cachorros",
  "Modificación conductual perro",
  "Modificación conductual gato",
  "Consultoría conductual",
  "Terapia conductual mascotas",
  "Entrenamiento positivo",
  "Reforzamiento positivo",
  "Clases de obediencia básica",
  "Clases de obediencia avanzada",
  "Control ladrido",
  "Control agresividad",
  "Enseñanza trucos perro",
  "Enseñanza trucos gato",
  "Paseador diario perros",
  "Paseador horario",
  "Paseo perros individual",
  "Paseo perros grupo",
  "Paseo perros barrio",
  "Paseo perros parque",
  "Paseo perros plaza",
  "Paseo perros playa",
  "Dog sitting",
  "Cuidado mascotas domicilio",
  "Paseo de cachorros",
  "Paseo gatos",
  "Paseo felino",
  "Entrenamiento agility",
  "Curso agility perros",
  "Competencia agility",
  "Juegos de inteligencia perro",
  "Juegos de estimulación mental gato",
  "Juguetes interactivos perro",
  "Juguetes interactivos gato",
  "Rutas dog friendly",
  "Excursión perro",
  "Excursión gato",
  "Entrenamiento obediencia básica",
  "Entrenamiento obediencia avanzada",
  "Entrenamiento cachorros",
  "Adiestramiento positivo",
  "Reforzamiento positivo",
  "Técnicas clicker",
  "Entrenamiento clicker",
  "Socialización temprana cachorros",
  "Socialización gatitos",
  "Terapia comportamental perro",
  "Terapia comportamental gato",
  "Rehabilitación física perro",
  "Rehabilitación física gato",
  "Fisioterapia canina",
  "Fisioterapia felina",
  "Masaje terapéutico perro",
  "Masaje terapéutico gato",
  "Acupuntura mascotas",
  "Acupuntura perros",
  "Acupuntura gatos",
  "Reiki mascotas",
  "Reiki perros",
  "Reiki gatos",
  "Consulta nutricional mascotas",
  "Plan nutricional perro",
  "Plan nutricional gato",
  "Dietista mascotas",
  "Dietista canina",
  "Dietista felina",
  "Entrenador de obediencia",
  "Educador canino",
  "Coach de mascotas",
  "Clases de adiestramiento",
  "Clases de entrenamiento",
  "Curso de obediencia",
  "Curso de adiestramiento",
  "Curso de comportamiento",
  "Seminario de comportamiento",
  "Taller de mascotas",
  "Taller de adiestramiento",
  "Taller de comportamiento",
  "Taller de socialización",
  "Actividades recreativas perros",
  "Actividades recreativas gatos",
  "Juegos de estimulación",
  "Paseo recreativo perros",
  "Paseo recreativo gatos",
  "Picnic perros",
  "Picnic gatos",
  "Excursión recreativa",
  "Excursión educativa perros",
  "Excursión educativa gatos",
  "Guardería canina full day",
  "Guardería canina half day",
  "Guardería felina full day",
  "Guardería felina half day",
  "Pet sitter",
  "Niñera de mascotas",
  "Cuidador de mascotas",
  "Paseador profesional",
  "Entrenador a domicilio",
  "Clases individuales perro",
  "Clases individuales gato",
  "Clases grupales perros",
  "Clases grupales gatos",
  "Consultoría veterinaria",
  "Chequeo general mascotas",
  "Control de salud perro",
  "Control de salud gato",
  "Seguimiento veterinario",
  "Seguimiento nutricional",
  "Seguimiento entrenamiento",
  "Evaluación comportamiento perro",
  "Evaluación comportamiento gato",
  "Terapia conducta perro",
  "Terapia conducta gato",
  "Modificación conductual",
  "Modificación hábitos mascotas",
  "Corrección de conducta perro",
  "Corrección de conducta gato",
  "Terapia adiestramiento",
  "Terapia socialización",
  "Estimulación mental perro",
  "Estimulación mental gato",
  "Juegos educativos perros",
  "Juegos educativos gatos",
  "Entrenamiento cognitivo perros",
  "Entrenamiento cognitivo gatos",
  "Socialización social perros",
  "Socialización social gatos",
  "Grupo de juego perros",
  "Grupo de juego gatos",
  "Entrenamiento físico perro",
  "Entrenamiento físico gato",
  "Ejercicio diario perro",
  "Ejercicio diario gato",
  "Actividad física perros",
  "Actividad física gatos",
  "Clases de agility",
  "Curso de agility",
  "Taller de agility",
  "Competencia agility perros",
];
