// src/lib/keywords/mecanica.ts
export const MECANICA_KEYWORDS = [
  "cambiar aceite motor",
  "cambio de aceite auto",
  "cambio de aceite moto",
  "aceite sintético",
  "aceite mineral",
  "filtro de aceite",
  "cambiar filtro de aceite",
  "filtro de aire",
  "cambiar filtro de aire",
  "filtro de combustible",
  "cambiar filtro de combustible",
  "bujías",
  "cambiar bujías",
  "bujías moto",
  "batería auto",
  "cambiar batería",
  "batería moto",
  "cargar batería",
  "alternador",
  "reparar alternador",
  "cambiar alternador",
  "motor de arranque",
  "reparar motor de arranque",
  "cambiar motor de arranque",
  "correa de distribución",
  "cambiar correa de distribución",
  "correa de accesorios",
  "cambiar correa de accesorios",
  "amortiguadores",
  "cambiar amortiguadores",
  "amortiguador delantero",
  "amortiguador trasero",
  "tren delantero",
  "tren trasero",
  "bujes",
  "cambiar bujes",
  "rótulas",
  "cambiar rótulas",
  "terminales de dirección",
  "cambiar terminales",
  "frenos",
  "pastillas de freno",
  "cambiar pastillas",
  "discos de freno",
  "cambiar discos",
  "líquido de frenos",
  "cambiar líquido de frenos",
  "frenos ABS",
  "bomba de freno",
  "reparar freno",
  "freno de mano",
  "reparar freno de mano",
  "freno a disco",
  "freno a tambor",
  "tambor de freno",
  "cambiar tambor de freno",
  "bomba de embrague",
  "cambiar bomba de embrague",
  "líquido de embrague",
  "cambiar líquido de embrague",
  "embrague",
  "cambiar embrague",
  "disco de embrague",
  "plato de embrague",
  "collarín",
  "pedal de embrague",
  "caja de cambios",
  "reparar caja de cambios",
  "caja manual",
  "caja automática",
  "transmisión",
  "reparar transmisión",
  "cardán",
  "reparar cardán",
  "palier",
  "reparar palier",
  "homocinética",
  "cambiar homocinética",
  "eje trasero",
  "eje delantero",
  "diferencial",
  "reparar diferencial",
  "cambiar diferencial",
  "junta homocinética",
  "cambiar junta homocinética",
  "amortiguador moto",
  "suspensión moto",
  "horquilla delantera",
  "reparar horquilla",
  "aceite horquilla",
  "rueda delantera",
  "rueda trasera",
  "cambiar rueda",
  "cubiertas",
  "cambiar cubierta",
  "neumático",
  "cambiar neumático",
  "balanceo",
  "alineación",
  "alineación 3D",
  "balanceo moto",
  "batería moto",
  "alternador moto",
  "arranque moto",
  "arranque eléctrico moto",
  "cadena de transmisión",
  "ajustar cadena",
  "lubricar cadena",
  "piñón",
  "cambiar piñón",
  "corona moto",
  "ajustar suspensión",
  "amortiguador trasero moto",
  "amortiguador delantero moto",
  "freno delantero",
  "freno trasero",
  "discos delanteros",
  "discos traseros",
  "pastillas delanteras",
  "pastillas traseras",
  "bomba de freno moto",
  "líquido de frenos moto",
  "embrague moto",
  "disco de embrague moto",
  "plato de embrague moto",
  "collarín moto",
  "bujías moto",
  "filtro de aire moto",
  "filtro de aceite moto",
  "filtro de combustible moto",
  "carburador",
  "limpiar carburador",
  "ajustar carburador",
  "inyección electrónica",
  "reparar inyección",
  "inyectores",
  "limpiar inyectores",
  "bomba de nafta",
  "cambiar bomba de nafta",
  "bomba de combustible",
  "nafta",
  "ajustar motor",
  "revisión motor",
  "reparación motor",
  "tapa de cilindros",
  "cambiar tapa de cilindros",
  "juntas motor",
  "cambiar juntas",
  "culata",
  "reparar culata",
  "cilindros",
  "pistones",
  "cambiar pistones",
  "anillos de pistón",
  "cigüeñal",
  "reparar cigüeñal",
  "cambiar cigüeñal",
  "biela",
  "reparar biela",
  "cambiar biela",
  "aceite caja automática",
  "cambio de aceite caja automática",
  "líquido transmisión automática",
  "filtro de caja automática",
  "reparar caja automática",
  "reparar caja manual",
  "sincronizadores",
  "reparar sincronizadores",
  "rodamientos",
  "cambiar rodamientos",
  "rulemanes",
  "cambiar rulemanes",
  "buje de suspensión",
  "cambiar buje suspensión",
  "barra estabilizadora",
  "cambiar barra estabilizadora",
  "reparación dirección",
  "dirección hidráulica",
  "dirección asistida",
  "bomba dirección",
  "reparar bomba dirección",
  "cremallera",
  "cambiar cremallera",
  "terminal de dirección",
  "cambiar terminal dirección",
  "rótula de dirección",
  "cambiar rótula dirección",
  "reparación frenos",
  "freno hidráulico",
  "reparación freno hidráulico",
  "bomba freno",
  "calibrar freno",
  "ajustar freno",
  "purgar freno",
  "freno de disco",
  "freno tambor",
  "cambiar disco",
  "cambiar pastilla",
  "cambiar tambor",
  "pedal freno",
  "pedal embrague",
  "pedal acelerador",
  "cable acelerador",
  "cable embrague",
  "motor eléctrico",
  "motor arranque",
  "reparacion motor arranque",
  "alternador auto",
  "alternador moto",
  "correa alternador",
  "tensión correa",
  "cambiar correa alternador",
  "bomba agua",
  "cambiar bomba de agua",
  "reparación bomba agua",
  "refrigerante",
  "agua radiador",
  "anticongelante",
  "purgar radiador",
  "radiador",
  "reparar radiador",
  "cambiar radiador",
  "mangueras radiador",
  "cambiar mangueras",
  "ventilador radiador",
  "sensor temperatura",
  "cambiar sensor",
  "termostato",
  "cambiar termostato",
  "bomba aceite",
  "reparar bomba aceite",
  "cambiar bomba aceite",
  "tapa válvulas",
  "cambiar tapa válvulas",
  "juntas tapa válvulas",
  "válvulas",
  "ajustar válvulas",
  "culata moto",
  "reparación culata moto",
  "cilindro moto",
  "pistón moto",
  "cambio de pistón moto",
  "embrague moto",
  "disco de embrague moto",
  "plato de embrague moto",
  "collarín moto",
  "cadena moto",
  "ajustar cadena moto",
  "piñón moto",
  "corona moto",
  "lubricar cadena moto",
  "balanceo moto",
  "alineación moto",
  "amortiguador moto",
  "horquilla delantera",
  "aceite horquilla",
  "freno delantero moto",
  "freno trasero moto",
  "disco delantero moto",
  "disco trasero moto",
  "pastilla delantera moto",
  "pastilla trasera moto",
  "bomba freno moto",
  "líquido de frenos moto",
  "carburador moto",
  "limpiar carburador moto",
  "ajustar carburador moto",
  "inyectores moto",
  "limpiar inyectores moto",
  "bomba de nafta moto",
  "ajustar motor moto",
  "revisión motor moto",
  "reparación motor moto",
  "tapa cilindros moto",
  "cambiar juntas moto",
  "culata moto",
  "pistón moto",
  "anillos de pistón moto",
  "cigüeñal moto",
  "biela moto",
  "sincronizadores moto",
  "rodamientos moto",
  "rulemanes moto",
  "buje suspensión moto",
  "barra estabilizadora moto",
  "dirección moto",
  "cremallera moto",
  "terminal dirección moto",
  "rótula dirección moto",
  "reparación frenos moto",
  "freno hidráulico moto",
  "purgar freno moto",
  "pedal freno moto",
  "pedal embrague moto",
  "pedal acelerador moto",
  "cable acelerador moto",
  "cable embrague moto",
  "motor arranque moto",
  "alternador moto",
  "correa alternador moto",
];
