// src/lib/keywords/mecanico-moto.ts
export const MECANICO_MOTO_KEYWORDS = [
  "cambio de aceite moto",
  "cambiar filtro de aceite moto",
  "cambiar filtro de aire moto",
  "cambiar filtro de combustible moto",
  "cambiar bujías moto",
  "bujías moto",
  "batería moto",
  "cambiar batería moto",
  "cargar batería moto",
  "alternador moto",
  "reparar alternador moto",
  "arranque moto",
  "arranque eléctrico moto",
  "reparar motor de arranque moto",
  "cadena de transmisión",
  "ajustar cadena",
  "lubricar cadena",
  "cambio de cadena",
  "piñón",
  "cambiar piñón",
  "corona moto",
  "cambiar corona",
  "ajuste de válvulas",
  "amortiguador moto",
  "suspensión moto",
  "ajustar suspensión",
  "horquilla delantera",
  "reparar horquilla",
  "aceite horquilla",
  "amortiguador trasero moto",
  "amortiguador delantero moto",
  "freno delantero moto",
  "freno trasero moto",
  "discos delanteros moto",
  "discos traseros moto",
  "pastillas delanteras moto",
  "pastillas traseras moto",
  "bomba de freno moto",
  "líquido de frenos moto",
  "purgar freno moto",
  "embrague moto",
  "cambio de embrague",
  "disco de embrague moto",
  "plato de embrague moto",
  "collarín moto",
  "cable embrague moto",
  "carburador",
  "limpieza de carburador",
  "ajustar carburador",
  "carburación",
  "regulación de ralentí",
  "inyectores moto",
  "limpiar inyectores moto",
  "bomba de nafta moto",
  "puesta a punto",
  "reparación de motor",
  "ajustar motor moto",
  "revisión motor moto",
  "reparación motor moto",
  "tapa cilindros moto",
  "cambiar juntas moto",
  "culata moto",
  "rectificación",
  "cilindro moto",
  "pistón moto",
  "cambio de pistón",
  "cambio de aros",
  "anillos de pistón moto",
  "cigüeñal moto",
  "biela moto",
  "distribución",
  "sincronizadores moto",
  "rodamientos moto",
  "rulemanes moto",
  "buje suspensión moto",
  "dirección moto",
  "cremallera moto",
  "terminal dirección moto",
  "rótula dirección moto"
];
