// src/lib/keywords/mudanzas.ts
export const MUDANZAS_KEYWORDS = [
  "Mudanzas a domicilio",
  "Mudanzas de departamento",
  "Mudanzas de casa",
  "Mudanzas de oficina",
  "Mudanzas locales",
  "Mudanzas nacionales",
  "Mudanzas internacionales",
  "Mudanzas exprés",
  "Mudanzas urgentes",
  "Traslado de muebles",
  "Traslado de electrodomésticos",
  "Traslado de cajas",
  "Traslado de objetos pesados",
  "Traslado de pianos",
  "Traslado de camas",
  "Traslado de sofás",
  "Traslado de sillas",
  "Traslado de mesas",
  "Desarmado de muebles",
  "Armado de muebles",
  "Embalaje de muebles",
  "Embalaje de cuadros",
  "Embalaje de vajilla",
  "Embalaje de ropa",
  "Embalaje de libros",
  "Embalaje de objetos frágiles",
  "Cajas para mudanza",
  "Cintas para mudanza",
  "Film para embalaje",
  "Plástico burbuja para mudanza",
  "Mudanzas económicas",
  "Mudanzas baratas",
  "Mudanzas premium",
  "Mudanzas seguras",
  "Mudanzas con seguro",
  "Mudanzas de corta distancia",
  "Mudanzas de larga distancia",
  "Mudanzas interprovinciales",
  "Mudanzas a barrios",
  "Mudanzas a edificios",
  "Mudanzas a casas bajas",
  "Mudanzas a pisos altos",
  "Mudanzas con ascensor",
  "Mudanzas sin ascensor",
  "Mudanzas con escalera",
  "Mudanzas con flete",
  "Mudanzas con camión",
  "Mudanzas con camioneta",
  "Mudanzas con chofer",
  "Mudanzas con equipo",
  "Mudanzas por hora",
  "Mudanzas completas",
  "Mudanzas parciales",
  "Mudanzas de fin de semana",
  "Mudanzas de día",
  "Mudanzas de noche",
  "Mudanzas con mudanceros",
  "Mudanzas con chicos de mudanza",
  "Mudanzas con profesional",
  "Mudanzas rápidas",
  "Mudanzas de empresas",
  "Mudanzas de oficinas grandes",
  "Mudanzas de oficinas pequeñas",
  "Mudanzas de locales comerciales",
  "Mudanzas de fábricas",
  "Mudanzas de talleres",
  "Mudanzas de escuelas",
  "Mudanzas de colegios",
  "Mudanzas de hospitales",
  "Mudanzas de clínicas",
  "Mudanzas de laboratorios",
  "Mudanzas de laboratorios médicos",
  "Mudanzas de laboratorios químicos",
  "Mudanzas de laboratorios industriales",
  "Mudanzas de bibliotecas",
  "Mudanzas de archivos",
  "Mudanzas de depósitos",
  "Mudanzas de galpones",
  "Mudanzas de empresas privadas",
  "Mudanzas de empresas públicas",
  "Mudanzas con protección de muebles",
  "Mudanzas con mantas",
  "Mudanzas con frazadas",
  "Mudanzas con gomas protectoras",
  "Mudanzas con cuerdas",
  "Mudanzas con soga",
  "Mudanzas con palets",
  "Mudanzas con camilla",
  "Mudanzas con elevador",
  "Mudanzas con grúa",
  "Mudanzas con pluma",
  "Mudanzas con montacargas",
  "Mudanzas con plataforma",
  "Mudanzas con carretilla",
  "Mudanzas con mano de obra",
  "Mudanzas con equipo profesional",
  "Mudanzas de muebles antiguos",
  "Mudanzas de muebles de diseño",
  "Mudanzas de muebles de madera",
  "Mudanzas de muebles de metal",
  "Mudanzas de muebles de plástico",
  "Mudanzas de muebles de jardín",
  "Mudanzas de muebles de living",
  "Mudanzas de muebles de comedor",
  "Mudanzas de muebles de dormitorio",
  "Mudanzas de muebles de cocina",
  "Mudanzas de muebles de baño",
  "Mudanzas de electrodomésticos grandes",
  "Mudanzas de electrodomésticos chicos",
  "Mudanzas de heladeras",
  "Mudanzas de freezers",
  "Mudanzas de cocinas",
  "Mudanzas de hornos",
  "Mudanzas de lavarropas",
  "Mudanzas de secarropas",
  "Mudanzas de microondas",
  "Mudanzas de lavavajillas",
  "Mudanzas de televisores",
  "Mudanzas de equipos de audio",
  "Mudanzas de computadoras",
  "Mudanzas de impresoras",
  "Mudanzas de equipos electrónicos",
  "Mudanzas de cuadros",
  "Mudanzas de esculturas",
  "Mudanzas de objetos de arte",
  "Mudanzas de vajilla",
  "Mudanzas de cristalería",
  "Mudanzas de cubiertos",
  "Mudanzas de ropa",
  "Mudanzas de zapatos",
  "Mudanzas de bolsos",
  "Mudanzas de mochilas",
  "Mudanzas de juguetes",
  "Mudanzas de instrumentos musicales",
  "Mudanzas de guitarras",
  "Mudanzas de pianos",
  "Mudanzas de baterías",
  "Mudanzas de violines",
  "Mudanzas de saxofones",
  "Mudanzas de trompetas",
  "Mudanzas de flautas",
  "Mudanzas de violonchelos",
  "Mudanzas de objetos frágiles",
  "Mudanzas de objetos delicados",
  "Mudanzas de objetos pesados",
  "Mudanzas de cajas grandes",
  "Mudanzas de cajas medianas",
  "Mudanzas de cajas chicas",
  "Mudanzas con embalaje profesional",
  "Mudanzas con material de embalaje",
  "Mudanzas con burbujas",
  "Mudanzas con film stretch",
  "Mudanzas con film plástico",
  "Mudanzas con cinta adhesiva",
  "Mudanzas con cartón",
  "Mudanzas con cajas",
  "Mudanzas con cajas de cartón",
  "Mudanzas con cajas reforzadas",
  "Mudanzas con cajas especiales",
  "Mudanzas con cajas de libros",
  "Mudanzas con cajas de ropa",
  "Mudanzas con cajas de vajilla",
  "Mudanzas con cajas de objetos frágiles",
  "Mudanzas con etiquetado",
  "Mudanzas con numeración",
  "Mudanzas con inventario",
  "Mudanzas con seguimiento",
  "Mudanzas con control de objetos",
  "Mudanzas con supervisión",
  "Mudanzas con seguro de muebles",
  "Mudanzas con seguro de electrodomésticos",
  "Mudanzas con seguro de objetos frágiles",
  "Mudanzas con seguro de transporte",
  "Mudanzas con seguro integral",
  "Mudanzas con seguro opcional",
  "Mudanzas con flete económico",
  "Mudanzas con flete express",
  "Mudanzas con flete premium",
  "Mudanzas con camión chico",
  "Mudanzas con camión mediano",
  "Mudanzas con camión grande",
  "Mudanzas con camioneta chica",
  "Mudanzas con camioneta grande",
  "Mudanzas con equipo de carga",
  "Mudanzas con equipo de descarga",
  "Mudanzas con ayuda de mudanceros",
  "Mudanzas con personal",
  "Mudanzas con profesionales",
  "Mudanzas con experiencia",
  "Mudanzas con referencias",
  "Mudanzas de barrios privados",
  "Mudanzas de barrios cerrados",
  "Mudanzas de departamentos céntricos",
  "Mudanzas de departamentos periféricos",
  "Mudanzas de casas en zona urbana",
  "Mudanzas de casas en zona rural",
  "Mudanzas de casas bajas",
  "Mudanzas de casas altas",
  "Mudanzas de edificios",
  "Mudanzas de oficinas corporativas",
  "Mudanzas de locales comerciales",
  "Mudanzas de fábricas",
  "Mudanzas de talleres",
  "Mudanzas de hospitales",
  "Mudanzas de clínicas",
  "Mudanzas de escuelas",
  "Mudanzas de colegios",
  "Mudanzas de laboratorios",
  "Mudanzas de depósitos",
  "Mudanzas de galpones",
  "Mudanzas de empresas privadas",
  "Mudanzas de empresas públicas",
  "Mudanzas de organismos estatales",
  "Mudanzas de instituciones educativas",
  "Mudanzas de instituciones de salud",
  "Mudanzas de instituciones culturales",
  "Mudanzas de instituciones religiosas",
  "Mudanzas con servicio completo",
  "Mudanzas con servicio parcial",
  "Mudanzas con carga y descarga",
  "Mudanzas con embalaje y desembalaje",
  "Mudanzas con transporte seguro",
  "Mudanzas con entrega puntual",
  "Mudanzas con mudanceros confiables",
  "Mudanzas con mudanceros profesionales",
  "Mudanzas con mudanceros responsables",
  "Mudanzas con mudanceros experimentados",
  "Mudanzas con vehículos equipados",
  "Mudanzas con camión con rampa",
  "Mudanzas con camioneta con caja",
  "Mudanzas con camión cerrado",
  "Mudanzas con camión abierto",
  "Mudanzas con camioneta cerrada",
  "Mudanzas con camioneta abierta",
  "Mudanzas con servicio de embalaje",
  "Mudanzas con servicio de transporte",
  "Mudanzas con servicio de carga",
  "Mudanzas con servicio de descarga",
  "Mudanzas con servicio de desarmado",
  "Mudanzas con servicio de armado",
  "Mudanzas con servicio integral",
  "Mudanzas con servicio parcial",
  "Mudanzas con seguimiento online",
  "Mudanzas con seguimiento telefónico",
  "Mudanzas con atención personalizada",
  "Mudanzas con presupuesto",
  "Mudanzas con cotización",
  "Mudanzas con reserva",
  "Mudanzas con confirmación",
  "Mudanzas con logística",
  "Mudanzas con planificación",
  "Mudanzas con coordinación",
  "Mudanzas con organización",
  "Mudanzas con embalaje especializado",
  "Mudanzas con embalaje de lujo",
  "Mudanzas con embalaje económico",
  "Mudanzas con embalaje personalizado",
  "Mudanzas con embalaje seguro",
  "Mudanzas con embalaje resistente",
  "Mudanzas con embalaje profesional",
  "Mudanzas con protección",
  "Mudanzas con mantas protectoras",
  "Mudanzas con film de protección",
  "Mudanzas con cuerdas de seguridad",
  "Mudanzas con sogas",
  "Mudanzas con gomas",
  "Mudanzas con cinchas",
  "Mudanzas con plataformas",
  "Mudanzas con carretillas",
  "Mudanzas con elevadores",
  "Mudanzas con montacargas",
  "Mudanzas con grúas",
  "Mudanzas con plumas",
  "Mudanzas con transporte especializado",
  "Mudanzas con traslado seguro",
  "Mudanzas con embalaje de cristalería",
  "Mudanzas con embalaje de vajilla",
  "Mudanzas con embalaje de objetos frágiles",
  "Mudanzas con embalaje de cuadros",
  "Mudanzas con embalaje de instrumentos",
  "Mudanzas con embalaje de libros",
  "Mudanzas con embalaje de ropa",
  "Mudanzas con embalaje de calzado",
  "Mudanzas con embalaje de muebles",
  "Mudanzas con embalaje de electrodomésticos",
  "Mudanzas con embalaje de equipos electrónicos",
  "Mudanzas con embalaje de equipos de oficina",
  "Mudanzas con embalaje de archivos",
  "Mudanzas con embalaje de documentos",
  "Mudanzas con embalaje de máquinas",
  "Mudanzas con embalaje de herramientas",
  "Mudanzas con embalaje de equipos deportivos",
  "Mudanzas con embalaje de bicicletas",
  "Mudanzas con embalaje de motocicletas",
  "Mudanzas con embalaje de pianos",
  "Mudanzas con embalaje de instrumentos musicales",
  "Mudanzas con embalaje de arte",
  "Mudanzas con embalaje de antigüedades",
  "Mudanzas con embalaje de objetos de valor",
  "Mudanzas con embalaje integral",
];
