// src/lib/keywords/pc-consolas.ts
export const PC_CONSOLAS_KEYWORDS = [
  "arreglo de PC",
  "reparación de PC",
  "service de PC",
  "mantenimiento de PC",
  "limpieza de PC",
  "formateo",
  "instalación de sistema operativo",
  "actualización de Windows",
  "instalación de programas",
  "eliminación de virus",
  "recuperación de datos",
  "reparación de notebook",
  "cambio de disco rígido",
  "cambio a SSD",
  "ampliación de memoria RAM",
  "reparación de fuente",
  "armado de PC",
  "reparación de consolas",
  "arreglo de consolas",
  "service de consolas",
  "reparación de PlayStation",
  "reparación de PS4",
  "reparación de PS5",
  "reparación de Xbox",
  "reparación de Nintendo",
  "cambio de pasta térmica",
  "limpieza interna",
  "reparación de joystick",
  "drift de joystick",
  "cambio de lector",
  "cambio de HDMI",
  "problemas de encendido",
  "actualización de software",
  "flasheo",
];
