// src/lib/keywords/piletas.ts
export const PILETAS_KEYWORDS = [
  "limpieza de piletas",
  "mantenimiento de piletas",
  "piletero",
  "limpieza de piscinas",
  "mantenimiento de piscinas",
  "control de cloro",
  "control de ph",
  "revisión de filtros de pileta",
  "cambio de arena de filtros",
  "reparación de bombas de pileta",
  "reemplazo de skimmers",
  "desinfección de agua de pileta",
  "mantenimiento de equipos de piscina",
  "arreglo de filtración de pileta",
  "instalación de piletas nuevas",
  "revestimiento de piletas",
  "pintura de piletas",
  "revisión de luces de pileta",
  "reparación de cañerías de piscina",
  "limpieza de borde de pileta",
  "control de temperatura del agua",
  "ajuste de niveles de agua",
  "vaciado y llenado de piletas",
  "mantenimiento preventivo de piletas",
  "restauración de piletas antiguas",
  "tratamientos de choque para agua",
  "piletero a domicilio",
  "servicio para piletas",
  "agua verde pileta",
  "agua turbia pileta"
];
