// src/lib/keywords/pintores.ts
export const PINTORES_KEYWORDS = [
  "pintar pared interior",
  "pintar pared exterior",
  "retoque de pared",
  "pintura descascarada",
  "pared con humedad",
  "techo que gotea pintura",
  "pintura de puerta",
  "pintura de ventana",
  "mueble pintado",
  "arreglo de rayones",
  "pintar cocina",
  "pintar baño",
  "pintura vieja",
  "pintar sala",
  "pintura que se pela",
  "pared con manchas",
  "retoque de pintura",
  "pintar dormitorio",
  "pintura en techo",
  "pintura exterior fachada",
  "pintura interior",
  "pintura de oficina",
  "pintar rejas",
  "puerta con pintura descascarada",
  "pintura de puerta de madera",
  "retoque de mueble",
  "pintura de armario",
  "pintura de closet",
  "pintar living",
  "pintura que se agrieta",
  "pintura con hongos",
  "pared manchada",
  "pintura de escalera",
  "pintura de balcón",
  "arreglo de pintura techo",
  "pintura exterior casa",
  "pintura interior departamento",
  "pintar pared de ladrillo",
  "pintar pared de yeso",
  "pintar pared de durlock",
  "pintura pared descascarada",
  "retoque pintura techo",
  "pintar marco de ventana",
  "pintar puerta metálica",
  "pintura de muebles viejos",
  "pintar puerta interior",
  "pintar puerta exterior",
  "pintura de baranda",
  "pintura de baranda de escalera",
  "pintar mueble de madera",
  "pintar placard",
  "pintura pared dormitorio",
  "pintura pared cocina",
  "pintura pared baño",
  "retoque de manchas en pared",
  "pintura enyesada",
  "pintar pared con gotelé",
  "pintura muro exterior",
  "pintar pared exterior casa",
  "pintar pared interior departamento",
];
