// src/lib/keywords/plomeria.ts
export const PLOMERIA_KEYWORDS = [
  "caño del tanque roto",
  "pileta de lavadero obstruida",
  "pileta de cocina tapada",
  "lavamanos flojo",
  "cambio de canilla",
  "fuga en caño de jardín",
  "desagüe externo tapado",
  "caño del lavarropas filtrando",
  "cambio de cuerito en canilla",
  "inodoro que gotea",
  "arreglo de videt",
  "tanque de agua obstruido",
  "caño de calefón roto",
  "desagüe lento en baño",
  "pileta de baño tapada",
  "ducha que gotea",
  "caño flexible del lavarropas roto",
  "cisterna que gotea",
  "válvula de paso rota",
  "inodoro flojo en piso",
  "cambio de inodoro completo",
  "desagüe de cocina lento",
  "lavabo con fuga",
  "cambio de grifería",
  "videt flojo",
  "tubería oxidada",
  "caño de pileta roto",
  "ducha con fuga interna",
  "caño de baño tapado",
  "lavamanos atascado",
  "arreglo de canilla",
  "caño que hace ruido",
  "tanque elevado que pierde",
  "bomba de agua sin presión",
  "caño de calefón que gotea",
  "cambio de cuerito en inodoro",
  "videt con fuga",
  "pileta tapada",
  "lavamanos flojo con grifo",
  "ducha con poca presión",
  "inodoro que no descarga",
  "tanque de agua con sedimentos",
  "desagüe de terraza tapado",
  "caño de baño con fuga",
  "lavamanos que no drena",
  "cambio de grifo de cocina",
  "arreglo de ducha",
  "inodoro que gotea",
  "cambio de cuerito en canilla",
  "pileta de baño lenta",
  "tanque de agua con fuga",
  "bomba de agua que no arranca",
  "caño flexible roto",
  "caño de calefón obstruido",
  "lavadero tapado",
  "cambio de inodoro",
  "arreglo de inodoro",
  "videt tapado",
  "ducha con poca presión",
  "tanque elevado que pierde",
  "bomba sumergible rota",
  "sifón tapado",
  "lavamanos que gotea",
  "caño que hace ruido",
  "desagüe externo lento",
  "caño de baño oxidado",
  "videt flojo con fuga",
  "lavadero con desagüe lento",
  "pileta de cocina goteando",
  "caño enterrado con fuga",
  "desagüe de terraza lento",
  "lavamanos tapado con residuos",
  "cambio de grifería completa",
  "arreglo de caño de cocina",
  "ducha tapada con residuos",
  "pileta del baño obstruida",
  "lavadero obstruido",
  "Cambio cuerito del baño"
];
