// src/lib/keywords/reparaciones.ts
export const REPARACIONES_KEYWORDS = [
    "reparar persiana",
    "arreglar persiana",
    "cambiar cinta de persiana",
    "persiana trabada",
    "persiana no sube",
    "persiana no baja",
    "persianista",
    "arreglar manija",
    "reparar puerta",
    "puerta no cierra",
    "puerta trabada",
    "cambiar cerradura",
    "arreglar cerradura",
    "reparar ventana",
    "ventana no cierra",
    "ventana rota",
    "cambiar vidrio",
    "reparar mueble",
    "mueble roto",
    "pata de silla rota",
    "pata de mesa rota",
    "armar mueble",
    "armado de muebles",
    "montaje de muebles",
    "instalador de muebles",
    "colgar cuadros",
    "instalar estantes",
    "colgar espejo",
    "instalar soporte de tv",
    "colgar televisor",
    "fijar a la pared",
    "reparar grifo",
    "grifo que gotea",
    "cambiar cuerito",
    "destapar cañeria",
    "destapar inodoro",
    "destapar bacha",
    "reparar perdida de agua",
    "filtracion de agua",
    "sellar junta",
    "silicona para baño",
    "silicona para cocina",
    "arreglar enchufe",
    "enchufe no funciona",
    "cambiar enchufe",
    "instalar enchufe",
    "reparar lampara",
    "cambiar lampara",
    "instalar lampara",
    "arreglar timbre",
    "cambiar timbre",
    "reparar electrodomestico",
    "arreglar heladera",
    "arreglar lavarropas",
    "arreglar secarropas",
    "arreglar microondas",
    "arreglar horno electrico",
    "mantenimiento general",
    "arreglos del hogar",
    "manitas a domicilio",
    "handyman",
    "pequeños arreglos",
    "changa",
    "changas",
    "trabajos menores",
    "ayuda en casa",
    "lavadora no enciende",
    "lavadora no centrifuga",
    "lavarropas no centrifuga",
    "lavadora no carga agua",
    "lavadora hace ruido",
    "lavadora gotea agua",
    "tambor de lavadora atascado",
    "lavarropas no lava bien",
    "lavadora con mal olor",
    "extractor no enciende",
    "campana no aspira",
    "cafetera no funciona",
    "licuadora no enciende",
    "procesadora hace ruido",
    "aspiradora no succiona",
    "aspiradora se apaga",
    "plancha no calienta",
    "plancha gotea agua"
];
