// src/lib/keywords/tecnologia.ts
export const TECNOLOGIA_KEYWORDS = [
  "Reparación de computadoras",
  "Servicio técnico PC",
  "Arreglo de notebooks",
  "Reparación de laptops",
  "Formateo de PC",
  "Instalación Windows",
  "Instalación Linux",
  "Instalación Mac OS",
  "Mantenimiento computadoras",
  "Optimización PC",
  "Limpieza interna PC",
  "Limpieza interna notebook",
  "Cambio de disco rígido",
  "Cambio SSD",
  "Actualización de RAM",
  "Actualización hardware",
  "Instalación de programas",
  "Instalación Office",
  "Instalación antivirus",
  "Instalación drivers",
  "Instalación impresoras",
  "Configuración de impresora",
  "Reparación impresoras",
  "Servicio técnico impresoras",
  "Instalación de routers",
  "Configuración Wi-Fi",
  "Arreglo de Wi-Fi",
  "Reparación de routers",
  "Instalación de redes",
  "Cableado de red",
  "Optimización de red",
  "Backup de datos",
  "Recuperación de archivos",
  "Recuperación de fotos",
  "Recuperación de videos",
  "Reparación de celulares",
  "Servicio técnico celulares",
  "Arreglo de teléfonos",
  "Cambio de pantalla celular",
  "Cambio de batería celular",
  "Reparación de tablet",
  "Servicio técnico tablet",
  "Arreglo tablet",
  "Instalación aplicaciones",
  "Instalación apps Android",
  "Instalación apps iOS",
  "Configuración de celular",
  "Configuración tablet",
  "Reparación de cargadores",
  "Arreglo de cargadores",
  "Cambio de pantallas",
  "Cambio de pantallas touch",
  "Reparación de touch",
  "Reemplazo de batería",
  "Cambio de batería iPhone",
  "Cambio de batería Samsung",
  "Cambio de batería Xiaomi",
  "Cambio de batería Motorola",
  "Actualización iOS",
  "Actualización Android",
  "Actualización software",
  "Configuración Gmail",
  "Configuración Outlook",
  "Configuración correo electrónico",
  "Recuperación de contraseñas",
  "Recuperación Gmail",
  "Recuperación Hotmail",
  "Recuperación Outlook",
  "Reparación de notebooks",
  "Limpieza de notebooks",
  "Instalación programas notebook",
  "Instalación antivirus notebook",
  "Mantenimiento de notebook",
  "Optimización de notebook",
  "Reparación hardware PC",
  "Arreglo hardware PC",
  "Cambio de placa madre",
  "Cambio de fuente PC",
  "Cambio de tarjeta gráfica",
  "Instalación tarjeta gráfica",
  "Configuración gráfica PC",
  "Arreglo tarjeta gráfica",
  "Reparación de monitores",
  "Reparación LCD",
  "Reparación LED",
  "Reparación de teclados",
  "Arreglo teclado laptop",
  "Cambio de teclado laptop",
  "Reparación de mouse",
  "Arreglo mouse",
  "Configuración mouse",
  "Instalación periféricos",
  "Arreglo periféricos",
  "Venta de computadoras",
  "Venta de notebooks",
  "Venta de PCs",
  "Venta de hardware",
  "Venta de accesorios PC",
  "Venta de teclados",
  "Venta de mouses",
  "Venta de monitores",
  "Instalación de programas antivirus",
  "Configuración antivirus",
  "Eliminación de virus",
  "Eliminación de malware",
  "Eliminación de spyware",
  "Limpieza virus PC",
  "Limpieza malware PC",
  "Optimización antivirus",
  "Reparación de laptops lentas",
  "Optimización de laptops",
  "Arreglo de notebooks lentas",
  "Reparación de PC lenta",
  "Optimización de PC lenta",
  "Actualización de software",
  "Actualización de programas",
  "Instalación de Windows 10",
  "Instalación de Windows 11",
  "Instalación de Linux Ubuntu",
  "Instalación Linux Mint",
  "Instalación de Mac OS",
  "Configuración de Mac",
  "Instalación de aplicaciones Mac",
  "Configuración de aplicaciones Mac",
  "Configuración de sistema Mac",
  "Configuración de seguridad Mac",
  "Configuración firewall Mac",
  "Instalación de firewall",
  "Configuración firewall PC",
  "Instalación de antivirus gratuito",
  "Instalación de antivirus pago",
  "Configuración antivirus gratuito",
  "Configuración antivirus pago",
  "Escaneo de virus PC",
  "Escaneo malware PC",
  "Eliminación troyanos",
  "Eliminación ransomwares",
  "Configuración backup",
  "Creación backup PC",
  "Creación backup notebook",
  "Configuración nube",
  "Backup en la nube",
  "Sincronización nube",
  "Configuración Google Drive",
  "Configuración OneDrive",
  "Configuración Dropbox",
  "Configuración iCloud",
  "Configuración Mega",
  "Configuración pCloud",
  "Recuperación de archivos borrados",
  "Recuperación archivos formato",
  "Recuperación archivos dañados",
  "Recuperación fotos borradas",
  "Recuperación videos borrados",
  "Recuperación documentos",
  "Recuperación archivos Word",
  "Recuperación Excel",
  "Recuperación PowerPoint",
  "Reparación celular mojado",
  "Arreglo celular mojado",
  "Secado celular",
  "Reparación placa celular",
  "Cambio pantalla celular",
  "Cambio pantalla iPhone",
  "Cambio pantalla Samsung",
  "Cambio pantalla Motorola",
  "Cambio pantalla Xiaomi",
  "Reparación táctil celular",
  "Reparación botones celular",
  "Arreglo botones celular",
  "Cambio botones celular",
  "Reparación altavoz celular",
  "Arreglo altavoz celular",
  "Reparación micrófono celular",
  "Arreglo micrófono celular",
  "Reparación cámara celular",
  "Arreglo cámara celular",
  "Configuración cámara celular",
  "Reparación software celular",
  "Instalación apps celular",
  "Configuración apps celular",
  "Configuración WhatsApp",
  "Configuración Telegram",
  "Configuración Instagram",
  "Configuración Facebook",
  "Configuración Twitter",
  "Configuración TikTok",
  "Configuración LinkedIn",
  "Configuración Zoom",
  "Configuración Meet",
  "Configuración Teams",
  "Instalación Teams",
  "Instalación Zoom",
  "Instalación Meet",
  "Reparación de tablet",
  "Arreglo de tablet",
  "Reparación tablet Android",
  "Reparación tablet iPad",
  "Cambio pantalla tablet",
  "Cambio batería tablet",
  "Instalación apps tablet",
  "Configuración apps tablet",
  "Reparación táctil tablet",
  "Arreglo táctil tablet",
  "Reparación botones tablet",
  "Arreglo botones tablet",
  "Cambio botones tablet",
  "Reparación micrófono tablet",
  "Arreglo micrófono tablet",
  "Reparación altavoz tablet",
  "Arreglo altavoz tablet",
  "Instalación router",
  "Configuración router",
  "Arreglo router",
  "Reparación router",
  "Instalación Wi-Fi",
  "Configuración Wi-Fi",
  "Optimización Wi-Fi",
  "Cambiar contraseña Wi-Fi",
  "Configuración contraseña Wi-Fi",
  "Instalar repetidor Wi-Fi",
  "Arreglo repetidor Wi-Fi",
  "Configuración repetidor Wi-Fi",
  "Instalación red doméstica",
  "Configuración red doméstica",
  "Cableado red doméstica",
  "Optimización red doméstica",
  "Instalación red oficina",
  "Configuración red oficina",
  "Cableado red oficina",
  "Optimización red oficina",
  "Seguridad informática",
  "Seguridad PC",
  "Seguridad notebook",
  "Seguridad celular",
  "Seguridad tablet",
  "Antivirus PC",
  "Antivirus notebook",
  "Antivirus celular",
  "Antivirus tablet",
  "Seguridad internet",
  "Seguridad red Wi-Fi",
  "Configuración firewall",
  "Reparación malware",
  "Reparación spyware",
  "Eliminación malware",
  "Eliminación spyware",
  "Limpieza virus notebook",
  "Limpieza malware notebook",
  "Optimización software",
  "Optimización Windows",
  "Optimización Linux",
  "Optimización Mac",
  "Reparación sistema operativo",
  "Instalación sistema operativo",
  "Configuración sistema operativo",
  "Actualización sistema operativo",
  "Arreglo PC lento",
  "Arreglo notebook lento",
  "Reparación hardware PC",
  "Reparación hardware notebook",
  "Cambio placa madre PC",
  "Cambio placa madre notebook",
  "Cambio tarjeta gráfica",
  "Cambio fuente PC",
  "Cambio fuente notebook",
  "Reparación tarjeta gráfica",
  "Instalación tarjeta gráfica",
  "Configuración tarjeta gráfica",
  "Configuración BIOS",
  "Actualización BIOS",
  "Arreglo BIOS",
  "Reparación de monitores",
  "Reparación LED",
  "Reparación LCD",
  "Arreglo monitores",
  "Instalación monitor",
  "Configuración monitor",
  "Venta computadoras",
  "Venta notebooks",
  "Venta PC",
  "Venta hardware",
  "Venta accesorios",
  "Venta mouses",
  "Venta teclados",
  "Venta monitores",
  "Venta impresoras",
  "Instalación periféricos",
  "Reparación periféricos",
  "Configuración periféricos",
  "Configuración teclado",
  "Configuración mouse",
  "Configuración monitor",
  "Reparación hardware periféricos",
  "Actualización hardware periféricos",
  "Optimización periféricos",
  "Servicio técnico PC a domicilio",
  "Servicio técnico notebook a domicilio",
  "Servicio técnico celulares a domicilio",
  "Servicio técnico tablet a domicilio",
];
