// src/lib/keywords/textiles.ts
export const TEXTILES_KEYWORDS = [
"Arreglos de ropa",
"Reparación de prendas",
"Confección a medida",
"Modificación de ropa",
"Ajuste de pantalones",
"Ajuste de camisas",
"Arreglo de vestidos",
"Arreglo de trajes",
"Arreglo de chaquetas",
"Coser botones",
"Coser cierres",
"Cambiar cierres",
"Cambiar botones",
"Dobladillo de pantalón",
"Dobladillo de falda",
"Arreglo de uniformes",
"Ajuste de ropa de oficina",
"Arreglo de ropa de trabajo",
"Remodelación de ropa",
"Transformación de ropa vieja",
"Reparación de costuras",
"Parches para ropa",
"Bordado de prendas",
"Personalización de ropa",
"Arreglo de ropa de cuero",
"Arreglo de ropa de jean",
"Arreglo de ropa delicada",
"Arreglo de ropa de niños",
"Ajuste de ropa de bebés",
"Arreglo de ropa deportiva",
"Reparación de ropa deportiva",
"Ajuste de camisas formales",
"Ajuste de pantalones formales",
"Cambiar forro de chaquetas",
"Arreglo de chaquetas de cuero",
"Arreglo de abrigos",
"Arreglo de mantas",
"Arreglo de cortinas",
"Arreglo de tapicería",
"Arreglo de cojines",
"Arreglo de edredones",
"Costura rápida",
"Servicio de costura",
"Taller de arreglos",
"Ajuste de ropa de moda",
"Arreglo de vestidos de fiesta",
"Arreglo de ropa vintage",
"Arreglo de trajes de boda",
"Arreglo de ropa interior",
"Arreglo de pantalones vaqueros"
];
