// src/lib/keywords/vidrieria.ts
export const VIDRIERIA_KEYWORDS = [
  "cambiar vidrio",
  "cambiar vidrio roto",
  "cambiar vidrio ventana",
  "cambiar vidrio puerta",
  "cambiar vidrio templado",
  "cambiar vidrio laminado",
  "cambiar vidrio blindex",
  "cambiar vidrio balcón",
  "cambiar vidrio cocina",
  "cambiar vidrio baño",
  "cambiar vidrio espejo",
  "cambiar vidrio antiguas",
  "cambiar vidrio bajo costo",
  "reemplazar vidrio",
  "reemplazar vidrio roto",
  "reemplazar vidrio ventana",
  "reemplazar vidrio puerta",
  "reemplazar vidrio templado",
  "reemplazar vidrio laminado",
  "reemplazar vidrio blindex",
  "instalar vidrio nuevo",
  "instalar vidrio templado",
  "instalar vidrio laminado",
  "instalar vidrio blindex",
  "instalar vidrio en ventana",
  "instalar vidrio en puerta",
  "instalar vidrio en balcón",
  "instalar vidrio espejo",
  "instalar mampara de vidrio",
  "instalar puerta de vidrio",
  "instalar ventana de vidrio",
  "instalar vidriera comercial",
  "instalar vidrio cocina",
  "instalar vidrio baño",
  "colocar vidrio",
  "colocar vidrio roto",
  "colocar vidrio templado",
  "colocar vidrio laminado",
  "colocar vidrio blindex",
  "colocar vidriera",
  "colocar mampara de vidrio",
  "colocar espejo",
  "cortar vidrio",
  "cortar vidrio a medida",
  "cortar vidrio templado",
  "cortar vidrio laminado",
  "cortar vidrio blindex",
  "vidriero urgente",
  "vidriero a domicilio",
  "vidriero barato",
  "vidriero confiable",
  "vidriero económico",
  "vidriero profesional",
  "reparar vidrio",
  "reparar vidrio roto",
  "reparar vidriera",
  "reparar mampara de vidrio",
  "reparar ventana de vidrio",
  "reparar puerta de vidrio",
  "reparar espejo",
  "arreglar vidrio",
  "arreglar vidriera",
  "arreglar ventana de vidrio",
  "arreglar puerta de vidrio",
  "vidrio blindado",
  "vidrio de seguridad",
  "vidrio antirrobo",
  "vidrio laminado seguridad",
  "vidrio templado seguridad",
  "mampara de baño",
  "mampara de ducha",
  "mampara corrediza",
  "mampara vidrio templado",
  "mampara vidrio laminado",
  "espejo a medida",
  "espejo baño",
  "espejo grande",
  "espejo pared",
  "espejo decorativo",
  "espejo rectangular",
  "espejo cuadrado",
  "espejo redondo",
  "vidriera local",
  "vidriera comercio",
  "vidriera negocio",
  "vidrio ventana balcón",
  "vidrio puerta balcón",
  "vidrio fijo",
  "vidrio corredizo",
  "vidrio lateral",
  "vidrio decorativo",
  "vidrio grabado",
  "vidrio mateado",
  "vidrio esmerilado",
  "vidrio acidado",
  "vidrio pintado",
  "vidrio templado precio",
  "vidrio laminado precio",
  "vidriero hoy",
  "vidriero urgente a domicilio",
];
